EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/fpga_test/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/da_separate/
EXTRA_CFLAGS += -Idrivers/hisi/hifi_dsp/
EXTRA_CFLAGS += -Idrivers/hisi/da_separate/
EXTRA_CFLAGS += -Iinclude/linux/hisi/da_combine/

#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_audio_test.o
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_audio_test_dma.o
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_audio_test_file.o
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += da_combine_v5_codec_test
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_charlotte_codec_test.o
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_codecless_fifo_inter_test.o

#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_sio_test.o
#obj-$(CONFIG_SND_SOC_CODEC_STUB) += hi_soundwire_test.o

#obj-m += snd-soc-hi-audio-test-driver.o
#snd-soc-hi-audio-test-driver-y := hi_audio_test.o \
#		hi_audio_test_dma.o \
#		hi_audio_test_file.o \
#		hi_dsd_test.o \
#		da_separate_codec_test.o \
#		da_combine_v5_codec_test.o

