# IPP v320 Makefile

obj-$(CONFIG_HISPIPP_V320) += gf.o
obj-$(CONFIG_HISPIPP_V320) += orb.o
obj-$(CONFIG_HISPIPP_V320) += mc.o
obj-$(CONFIG_HISPIPP_V320) += vbk.o
obj-$(CONFIG_HISPIPP_V320) += reorder.o
obj-$(CONFIG_HISPIPP_V320) += compare.o
obj-$(CONFIG_HISPIPP_V320) += orb_enh.o

