// ******************************************************************************
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co., Ltd.
// File name     :  sub_ctrl_reg_offset_field.h
// Version       :  1.0
// Date          :  2018-07-02
// Description   :  Define all registers/tables for HiStarISP
// Others        :  Generated automatically by nManager V4.0
// ******************************************************************************

#ifndef __SUB_CTRL_REG_OFFSET_FIELD_CS_H__
#define __SUB_CTRL_REG_OFFSET_FIELD_CS_H__

#define SUB_CTRL_APB_OVERF_PROT_LEN                      2
#define SUB_CTRL_APB_OVERF_PROT_OFFSET                   19
#define SUB_CTRL_MST_PRIORITY_CVDR_LEN                   1
#define SUB_CTRL_MST_PRIORITY_CVDR_OFFSET                18
#define SUB_CTRL_MST_PRIORITY_FD_LEN                     1
#define SUB_CTRL_MST_PRIORITY_FD_OFFSET                  17
#define SUB_CTRL_CONTROL_DISABLE_AXI_DATA_PACKING_LEN    1
#define SUB_CTRL_CONTROL_DISABLE_AXI_DATA_PACKING_OFFSET 16
#define SUB_CTRL_JPG_TOP_APB_FORCE_CLK_ON_LEN            1
#define SUB_CTRL_JPG_TOP_APB_FORCE_CLK_ON_OFFSET         1
#define SUB_CTRL_JPG_DW_AXI_GATEDCLOCK_EN_LEN            1
#define SUB_CTRL_JPG_DW_AXI_GATEDCLOCK_EN_OFFSET         0

#define SUB_CTRL_CMDLST_SOFT_RST_LEN         1
#define SUB_CTRL_CMDLST_SOFT_RST_OFFSET      3
#define SUB_CTRL_SMMU_MASTER_SOFT_RST_LEN    1
#define SUB_CTRL_SMMU_MASTER_SOFT_RST_OFFSET 2
#define SUB_CTRL_SMMU_SOFT_RST_LEN           1
#define SUB_CTRL_SMMU_SOFT_RST_OFFSET        1
#define SUB_CTRL_CVDR_SOFT_RST_LEN           1
#define SUB_CTRL_CVDR_SOFT_RST_OFFSET        0

#define SUB_CTRL_MEM_CTRL_SP_LEN         29
#define SUB_CTRL_MEM_CTRL_SP_OFFSET      3
#define SUB_CTRL_CVDR_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_CVDR_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_MEM_CTRL_TP_LEN    29
#define SUB_CTRL_MEM_CTRL_TP_OFFSET 3

#define SUB_CTRL_CVDR_IRQ_CLR_LEN    8
#define SUB_CTRL_CVDR_IRQ_CLR_OFFSET 0

#define SUB_CTRL_CVDR_IRQ_MASK_LEN    8
#define SUB_CTRL_CVDR_IRQ_MASK_OFFSET 0

#define SUB_CTRL_CVDR_IRQ_STATE_RAW_LEN     8
#define SUB_CTRL_CVDR_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_CVDR_IRQ_STATE_MASK_LEN    8
#define SUB_CTRL_CVDR_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_CTRL_CHN7_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN7_OFFSET 21
#define SUB_CTRL_CMDLST_CTRL_CHN6_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN6_OFFSET 18
#define SUB_CTRL_CMDLST_CTRL_CHN5_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN5_OFFSET 15
#define SUB_CTRL_CMDLST_CTRL_CHN4_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN4_OFFSET 12
#define SUB_CTRL_CMDLST_CTRL_CHN3_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN3_OFFSET 9
#define SUB_CTRL_CMDLST_CTRL_CHN2_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN2_OFFSET 6
#define SUB_CTRL_CMDLST_CTRL_CHN1_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN1_OFFSET 3
#define SUB_CTRL_CMDLST_CTRL_CHN0_LEN    3
#define SUB_CTRL_CMDLST_CTRL_CHN0_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN0_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN0_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN1_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN1_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN2_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN2_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN3_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN3_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN4_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN4_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN5_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN5_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN6_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN6_OFFSET 0

#define SUB_CTRL_CMDLST_EOF_MASK_CHN7_LEN    2
#define SUB_CTRL_CMDLST_EOF_MASK_CHN7_OFFSET 0

#define SUB_CTRL_CMDLST_R8_IRQ_CLR_LEN    8
#define SUB_CTRL_CMDLST_R8_IRQ_CLR_OFFSET 0

#define SUB_CTRL_CMDLST_R8_IRQ_MASK_LEN    8
#define SUB_CTRL_CMDLST_R8_IRQ_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_R8_IRQ_STATE_RAW_LEN     8
#define SUB_CTRL_CMDLST_R8_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_CMDLST_R8_IRQ_STATE_MASK_LEN    8
#define SUB_CTRL_CMDLST_R8_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_ACPU_IRQ_CLR_LEN    8
#define SUB_CTRL_CMDLST_ACPU_IRQ_CLR_OFFSET 0

#define SUB_CTRL_CMDLST_ACPU_IRQ_MASK_LEN    8
#define SUB_CTRL_CMDLST_ACPU_IRQ_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_ACPU_IRQ_STATE_RAW_LEN     8
#define SUB_CTRL_CMDLST_ACPU_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_CMDLST_ACPU_IRQ_STATE_MASK_LEN    8
#define SUB_CTRL_CMDLST_ACPU_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_IVP_IRQ_CLR_LEN    8
#define SUB_CTRL_CMDLST_IVP_IRQ_CLR_OFFSET 0

#define SUB_CTRL_CMDLST_IVP_IRQ_MASK_LEN    8
#define SUB_CTRL_CMDLST_IVP_IRQ_MASK_OFFSET 0

#define SUB_CTRL_CMDLST_IVP_IRQ_STATE_RAW_LEN     8
#define SUB_CTRL_CMDLST_IVP_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_CMDLST_IVP_IRQ_STATE_MASK_LEN    8
#define SUB_CTRL_CMDLST_IVP_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_FLUX_CTRL0_CVDR_R_LEN    32
#define SUB_CTRL_FLUX_CTRL0_CVDR_R_OFFSET 0

#define SUB_CTRL_FLUX_CTRL1_CVDR_R_LEN    32
#define SUB_CTRL_FLUX_CTRL1_CVDR_R_OFFSET 0

#define SUB_CTRL_FLUX_CTRL0_CVDR_W_LEN    32
#define SUB_CTRL_FLUX_CTRL0_CVDR_W_OFFSET 0

#define SUB_CTRL_FLUX_CTRL1_CVDR_W_LEN    32
#define SUB_CTRL_FLUX_CTRL1_CVDR_W_OFFSET 0

#define SUB_CTRL_FLUX_CTRL0_FD_R_LEN    32
#define SUB_CTRL_FLUX_CTRL0_FD_R_OFFSET 0

#define SUB_CTRL_FLUX_CTRL1_FD_R_LEN    32
#define SUB_CTRL_FLUX_CTRL1_FD_R_OFFSET 0

#define SUB_CTRL_FLUX_CTRL0_FD_W_LEN    32
#define SUB_CTRL_FLUX_CTRL0_FD_W_OFFSET 0

#define SUB_CTRL_FLUX_CTRL1_FD_W_LEN    32
#define SUB_CTRL_FLUX_CTRL1_FD_W_OFFSET 0

#define SUB_CTRL_JPG_AXI_DLOCK_ID_LEN     8
#define SUB_CTRL_JPG_AXI_DLOCK_ID_OFFSET  20
#define SUB_CTRL_JPG_AXI_DLOCK_MST_LEN    1
#define SUB_CTRL_JPG_AXI_DLOCK_MST_OFFSET 19
#define SUB_CTRL_JPG_AXI_DLOCK_SLV_LEN    1
#define SUB_CTRL_JPG_AXI_DLOCK_SLV_OFFSET 18
#define SUB_CTRL_JPG_AXI_DLOCK_WR_LEN     1
#define SUB_CTRL_JPG_AXI_DLOCK_WR_OFFSET  17
#define SUB_CTRL_JPG_AXI_DLOCK_IRQ_LEN    1
#define SUB_CTRL_JPG_AXI_DLOCK_IRQ_OFFSET 16

#define SUB_CTRL_JPGENC_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_JPGENC_FORCE_CLK_ON_OFFSET 16
#define SUB_CTRL_JPGENC_CLKEN_LEN           1
#define SUB_CTRL_JPGENC_CLKEN_OFFSET        0

#define SUB_CTRL_JPGENC_SOFT_RST_LEN    1
#define SUB_CTRL_JPGENC_SOFT_RST_OFFSET 0

#define SUB_CTRL_JPGENC_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_JPGENC_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_JPGENC_PREFETCH_STOP_OK_LEN    1
#define SUB_CTRL_JPGENC_PREFETCH_STOP_OK_OFFSET 16
#define SUB_CTRL_JPGENC_PREFETCH_STOP_LEN       1
#define SUB_CTRL_JPGENC_PREFETCH_STOP_OFFSET    0

#define SUB_CTRL_JPGENC_IRQ_FORCE_LEN    5
#define SUB_CTRL_JPGENC_IRQ_FORCE_OFFSET 16
#define SUB_CTRL_JPGENC_IRQ_CLR_LEN      5
#define SUB_CTRL_JPGENC_IRQ_CLR_OFFSET   0

#define SUB_CTRL_JPGENC_IRQ_MASK_LEN    5
#define SUB_CTRL_JPGENC_IRQ_MASK_OFFSET 0

#define SUB_CTRL_JPGENC_IRQ_STATE_RAW_LEN     5
#define SUB_CTRL_JPGENC_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_JPGENC_IRQ_STATE_MASK_LEN    5
#define SUB_CTRL_JPGENC_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_JPGDEC_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_JPGDEC_FORCE_CLK_ON_OFFSET 16
#define SUB_CTRL_JPGDEC_CLKEN_LEN           1
#define SUB_CTRL_JPGDEC_CLKEN_OFFSET        0

#define SUB_CTRL_JPGDEC_SOFT_RST_LEN    1
#define SUB_CTRL_JPGDEC_SOFT_RST_OFFSET 0

#define SUB_CTRL_JPGDEC_MEM_CTRL_TP_LEN    3
#define SUB_CTRL_JPGDEC_MEM_CTRL_TP_OFFSET 4
#define SUB_CTRL_JPGDEC_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_JPGDEC_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_JPGDEC_PREFETCH_STOP_OK_LEN    1
#define SUB_CTRL_JPGDEC_PREFETCH_STOP_OK_OFFSET 16
#define SUB_CTRL_JPGDEC_PREFETCH_STOP_LEN       1
#define SUB_CTRL_JPGDEC_PREFETCH_STOP_OFFSET    0

#define SUB_CTRL_JPGDEC_IRQ_FORCE_LEN    4
#define SUB_CTRL_JPGDEC_IRQ_FORCE_OFFSET 16
#define SUB_CTRL_JPGDEC_IRQ_CLR_LEN      4
#define SUB_CTRL_JPGDEC_IRQ_CLR_OFFSET   0

#define SUB_CTRL_JPGDEC_IRQ_MASK_LEN    4
#define SUB_CTRL_JPGDEC_IRQ_MASK_OFFSET 0

#define SUB_CTRL_JPGDEC_IRQ_STATE_RAW_LEN     4
#define SUB_CTRL_JPGDEC_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_JPGDEC_IRQ_STATE_MASK_LEN    4
#define SUB_CTRL_JPGDEC_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_VBK_FORCE_CLK_ON_LEN     1
#define SUB_CTRL_VBK_FORCE_CLK_ON_OFFSET  18
#define SUB_CTRL_MFNR_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_MFNR_FORCE_CLK_ON_OFFSET 17
#define SUB_CTRL_MCF_FORCE_CLK_ON_LEN     1
#define SUB_CTRL_MCF_FORCE_CLK_ON_OFFSET  16
#define SUB_CTRL_VBK_CLKEN_LEN            1
#define SUB_CTRL_VBK_CLKEN_OFFSET         2
#define SUB_CTRL_MFNR_CLKEN_LEN           1
#define SUB_CTRL_MFNR_CLKEN_OFFSET        1
#define SUB_CTRL_MCF_CLKEN_LEN            1
#define SUB_CTRL_MCF_CLKEN_OFFSET         0

#define SUB_CTRL_VBK_SOFT_RST_LEN     1
#define SUB_CTRL_VBK_SOFT_RST_OFFSET  2
#define SUB_CTRL_MFNR_SOFT_RST_LEN    1
#define SUB_CTRL_MFNR_SOFT_RST_OFFSET 1
#define SUB_CTRL_MCF_SOFT_RST_LEN     1
#define SUB_CTRL_MCF_SOFT_RST_OFFSET  0

#define SUB_CTRL_VBK_MEM_CTRL_SP_LEN     3
#define SUB_CTRL_VBK_MEM_CTRL_SP_OFFSET  8
#define SUB_CTRL_MFNR_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_MFNR_MEM_CTRL_SP_OFFSET 4
#define SUB_CTRL_MCF_MEM_CTRL_SP_LEN     3
#define SUB_CTRL_MCF_MEM_CTRL_SP_OFFSET  0

#define SUB_CTRL_CPE_IRQ_CLR_LEN    23
#define SUB_CTRL_CPE_IRQ_CLR_OFFSET 0

#define SUB_CTRL_CPE_IRQ_MASK_LEN    23
#define SUB_CTRL_CPE_IRQ_MASK_OFFSET 0

#define SUB_CTRL_VBK_IRQ_OUTEN_LEN     2
#define SUB_CTRL_VBK_IRQ_OUTEN_OFFSET  4
#define SUB_CTRL_MFNR_IRQ_OUTEN_LEN    2
#define SUB_CTRL_MFNR_IRQ_OUTEN_OFFSET 2
#define SUB_CTRL_MCF_IRQ_OUTEN_LEN     2
#define SUB_CTRL_MCF_IRQ_OUTEN_OFFSET  0

#define SUB_CTRL_CPE_IRQ_STATE_MASK_LEN    23
#define SUB_CTRL_CPE_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_CPE_IRQ_STATE_RAW_LEN    23
#define SUB_CTRL_CPE_IRQ_STATE_RAW_OFFSET 0

#define SUB_CTRL_CPE_VPWR0_IHRIGHT_LEN    11
#define SUB_CTRL_CPE_VPWR0_IHRIGHT_OFFSET 16
#define SUB_CTRL_CPE_VPWR0_IHLEFT_LEN     11
#define SUB_CTRL_CPE_VPWR0_IHLEFT_OFFSET  0

#define SUB_CTRL_CPE_VPWR1_IHRIGHT_LEN    11
#define SUB_CTRL_CPE_VPWR1_IHRIGHT_OFFSET 16
#define SUB_CTRL_CPE_VPWR1_IHLEFT_LEN     11
#define SUB_CTRL_CPE_VPWR1_IHLEFT_OFFSET  0

#define SUB_CTRL_CPE_VPWR2_IHRIGHT_LEN    11
#define SUB_CTRL_CPE_VPWR2_IHRIGHT_OFFSET 16
#define SUB_CTRL_CPE_VPWR2_IHLEFT_LEN     11
#define SUB_CTRL_CPE_VPWR2_IHLEFT_OFFSET  0

#define SUB_CTRL_CPE_OP_MODE_LEN    2
#define SUB_CTRL_CPE_OP_MODE_OFFSET 0

#define SUB_CTRL_SLAM_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_SLAM_FORCE_CLK_ON_OFFSET 16
#define SUB_CTRL_SLAM_CLKEN_LEN           1
#define SUB_CTRL_SLAM_CLKEN_OFFSET        0

#define SUB_CTRL_SLAM_SOFT_RST_LEN    1
#define SUB_CTRL_SLAM_SOFT_RST_OFFSET 0

#define SUB_CTRL_SLAM_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_SLAM_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_SLAM_IRQ_FORCE_LEN    14
#define SUB_CTRL_SLAM_IRQ_FORCE_OFFSET 16
#define SUB_CTRL_SLAM_IRQ_CLR_LEN      14
#define SUB_CTRL_SLAM_IRQ_CLR_OFFSET   0

#define SUB_CTRL_SLAM_IRQ_OUTEN_LEN    2
#define SUB_CTRL_SLAM_IRQ_OUTEN_OFFSET 16
#define SUB_CTRL_SLAM_IRQ_MASK_LEN     14
#define SUB_CTRL_SLAM_IRQ_MASK_OFFSET  0

#define SUB_CTRL_SLAM_IRQ_STATE_RAW_LEN     14
#define SUB_CTRL_SLAM_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_SLAM_IRQ_STATE_MASK_LEN    14
#define SUB_CTRL_SLAM_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_RDR_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_RDR_FORCE_CLK_ON_OFFSET 16
#define SUB_CTRL_RDR_CLKEN_LEN           1
#define SUB_CTRL_RDR_CLKEN_OFFSET        0

#define SUB_CTRL_RDR_SOFT_RST_LEN    1
#define SUB_CTRL_RDR_SOFT_RST_OFFSET 0

#define SUB_CTRL_RDR_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_RDR_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_RDR_PREFETCH_STOP_OK_LEN    1
#define SUB_CTRL_RDR_PREFETCH_STOP_OK_OFFSET 16
#define SUB_CTRL_RDR_PREFETCH_STOP_LEN       1
#define SUB_CTRL_RDR_PREFETCH_STOP_OFFSET    0

#define SUB_CTRL_RDR_IRQ_FORCE_LEN    5
#define SUB_CTRL_RDR_IRQ_FORCE_OFFSET 16
#define SUB_CTRL_RDR_IRQ_CLR_LEN      5
#define SUB_CTRL_RDR_IRQ_CLR_OFFSET   0

#define SUB_CTRL_RDR_IRQ_OUTEN_LEN    2
#define SUB_CTRL_RDR_IRQ_OUTEN_OFFSET 16
#define SUB_CTRL_RDR_IRQ_MASK_LEN     5
#define SUB_CTRL_RDR_IRQ_MASK_OFFSET  0

#define SUB_CTRL_RDR_IRQ_STATE_RAW_LEN     5
#define SUB_CTRL_RDR_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_RDR_IRQ_STATE_MASK_LEN    5
#define SUB_CTRL_RDR_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_CMP_FORCE_CLK_ON_LEN    1
#define SUB_CTRL_CMP_FORCE_CLK_ON_OFFSET 16
#define SUB_CTRL_CMP_CLKEN_LEN           1
#define SUB_CTRL_CMP_CLKEN_OFFSET        0

#define SUB_CTRL_CMP_SOFT_RST_LEN    1
#define SUB_CTRL_CMP_SOFT_RST_OFFSET 0

#define SUB_CTRL_CMP_MEM_CTRL_SP_LEN    3
#define SUB_CTRL_CMP_MEM_CTRL_SP_OFFSET 0

#define SUB_CTRL_CMP_PREFETCH_STOP_OK_LEN    1
#define SUB_CTRL_CMP_PREFETCH_STOP_OK_OFFSET 16
#define SUB_CTRL_CMP_PREFETCH_STOP_LEN       1
#define SUB_CTRL_CMP_PREFETCH_STOP_OFFSET    0

#define SUB_CTRL_CMP_IRQ_FORCE_LEN    5
#define SUB_CTRL_CMP_IRQ_FORCE_OFFSET 16
#define SUB_CTRL_CMP_IRQ_CLR_LEN      5
#define SUB_CTRL_CMP_IRQ_CLR_OFFSET   0

#define SUB_CTRL_CMP_IRQ_OUTEN_LEN    2
#define SUB_CTRL_CMP_IRQ_OUTEN_OFFSET 16
#define SUB_CTRL_CMP_IRQ_MASK_LEN     5
#define SUB_CTRL_CMP_IRQ_MASK_OFFSET  0

#define SUB_CTRL_CMP_IRQ_STATE_RAW_LEN     5
#define SUB_CTRL_CMP_IRQ_STATE_RAW_OFFSET  16
#define SUB_CTRL_CMP_IRQ_STATE_MASK_LEN    5
#define SUB_CTRL_CMP_IRQ_STATE_MASK_OFFSET 0

#define SUB_CTRL_HIFD_CLKEN_LEN    1
#define SUB_CTRL_HIFD_CLKEN_OFFSET 0

#define SUB_CTRL_HIFD_SOFT_RST_LEN    1
#define SUB_CTRL_HIFD_SOFT_RST_OFFSET 0

#define SUB_CTRL_HIFD_ROM_CTRL_LEN        8
#define SUB_CTRL_HIFD_ROM_CTRL_OFFSET     16
#define SUB_CTRL_HIFD_MEM_CTRL_TP_LEN     3
#define SUB_CTRL_HIFD_MEM_CTRL_TP_OFFSET  8
#define SUB_CTRL_HIFD_MEM_CTRL_SP2_LEN    3
#define SUB_CTRL_HIFD_MEM_CTRL_SP2_OFFSET 4
#define SUB_CTRL_HIFD_MEM_CTRL_SP_LEN     3
#define SUB_CTRL_HIFD_MEM_CTRL_SP_OFFSET  0

#define SUB_CTRL_FD_PREFETCH_INITIAL_LEN    11
#define SUB_CTRL_FD_PREFETCH_INITIAL_OFFSET 0

#define SUB_CTRL_FD_STREAM_END_LEN    11
#define SUB_CTRL_FD_STREAM_END_OFFSET 0

#define SUB_CTRL_FD_STREAM_ACK_LEN    11
#define SUB_CTRL_FD_STREAM_ACK_OFFSET 0

#define SUB_CTRL_DEBUG_INFO_0_LEN    32
#define SUB_CTRL_DEBUG_INFO_0_OFFSET 0

#define SUB_CTRL_DEBUG_INFO_1_LEN    32
#define SUB_CTRL_DEBUG_INFO_1_OFFSET 0

#define SUB_CTRL_DEBUG_INFO_2_LEN    32
#define SUB_CTRL_DEBUG_INFO_2_OFFSET 0

#define SUB_CTRL_DEBUG_INFO_3_LEN    32
#define SUB_CTRL_DEBUG_INFO_3_OFFSET 0

#define SUB_CTRL_CMDLST_TZ_SECURE_N_LEN    1
#define SUB_CTRL_CMDLST_TZ_SECURE_N_OFFSET 7
#define SUB_CTRL_ORB_TZ_SECURE_N_LEN       1
#define SUB_CTRL_ORB_TZ_SECURE_N_OFFSET    6
#define SUB_CTRL_SLAM_TZ_SECURE_N_LEN      1
#define SUB_CTRL_SLAM_TZ_SECURE_N_OFFSET   5
#define SUB_CTRL_CPE_TZ_SECURE_N_LEN       1
#define SUB_CTRL_CPE_TZ_SECURE_N_OFFSET    4
#define SUB_CTRL_FD_TZ_SECURE_N_LEN        1
#define SUB_CTRL_FD_TZ_SECURE_N_OFFSET     3
#define SUB_CTRL_JPGDEC_TZ_SECURE_N_LEN    1
#define SUB_CTRL_JPGDEC_TZ_SECURE_N_OFFSET 2
#define SUB_CTRL_JPGENC_TZ_SECURE_N_LEN    1
#define SUB_CTRL_JPGENC_TZ_SECURE_N_OFFSET 1
#define SUB_CTRL_TOP_TZ_SECURE_N_LEN       1
#define SUB_CTRL_TOP_TZ_SECURE_N_OFFSET    0

#endif // __SUB_CTRL_REG_OFFSET_FIELD_CS_H__
