/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2020. All rights reserved.
 * foss@huawei.com
 *
 * If distributed as part of the Linux kernel, the following license terms
 * apply:
 *
 * * This program is free software; you can redistribute it and/or modify
 * * it under the terms of the GNU General Public License version 2 and
 * * only version 2 as published by the Free Software Foundation.
 * *
 * * This program is distributed in the hope that it will be useful,
 * * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * * GNU General Public License for more details.
 * *
 * * You should have received a copy of the GNU General Public License
 * * along with this program; if not, write to the Free Software
 * * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA
 *
 * Otherwise, the following license terms apply:
 *
 * * Redistribution and use in source and binary forms, with or without
 * * modification, are permitted provided that the following conditions
 * * are met:
 * * 1) Redistributions of source code must retain the above copyright
 * *    notice, this list of conditions and the following disclaimer.
 * * 2) Redistributions in binary form must reproduce the above copyright
 * *    notice, this list of conditions and the following disclaimer in the
 * *    documentation and/or other materials provided with the distribution.
 * * 3) Neither the name of Huawei nor the names of its contributors may
 * *    be used to endorse or promote products derived from this software
 * *    without specific prior written permission.
 *
 * * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef PS_LOG_GAS_FILE_ID_DEFINE_H
#define PS_LOG_GAS_FILE_ID_DEFINE_H

#include "ps_log_file_id_base.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

typedef enum
{
    PS_FILE_ID_GAS_NONE  = 0,
    PS_FILE_ID_GAS_FSM_C = GAS_TEAM_FILE_ID,
    PS_FILE_ID_GAS_COMM_C,
    PS_FILE_ID_GAS_GASM_C,
    PS_FILE_ID_GAS_GASMFUNC_C,
    PS_FILE_ID_GAS_GCOM_C,
    PS_FILE_ID_GAS_GCOM_DATA_COMM_C,
    PS_FILE_ID_GAS_GCOMC_C,
    PS_FILE_ID_GAS_GCOMCFSM_C,
    PS_FILE_ID_GAS_GCOMCFSMTBL_C,
    PS_FILE_ID_GAS_GCOMCL1FSM_C,
    PS_FILE_ID_GASGCOMCL2FSMBGWSEARCHG_C,
    PS_FILE_ID_GASGCOMCL2FSMBGGSEARCHG_C,
    PS_FILE_ID_GASGCOMCL2FSMBGGSEARCHW_C,
    PS_FILE_ID_GASGCOMCL2FSMBGPLMNLISTSEARCH_C,
    /* 此文件废弃,但是保留文件名的枚举,防止HIDS解析前后版本不兼容 */
    PS_FILE_ID_GASGCOMSISCELLNORMALBGNCELLBCCH_C,
    PS_FILE_ID_GASGCOMSIINACTIVEBGNCELLBCCH_C,
    PS_FILE_ID_GAS_GCOMCGPRSCELLRESELECTION_C,
    PS_FILE_ID_GAS_GCOMCGSMCELLRESELECTION_C,
    PS_FILE_ID_GAS_GCOMCMSGDISTRIBUTION_C,
    PS_FILE_ID_GAS_GCOMCPLMNSEARCH_C,
    PS_FILE_ID_GAS_GCOMCPUBLICCELLRESELECTION_C,
    PS_FILE_ID_GAS_GCOMCUTRANCELLRESELECTION_C,
    PS_FILE_ID_GAS_GCOMMAIN_C,
    PS_FILE_ID_GAS_GCOMMCOMMON_C,
    PS_FILE_ID_GAS_GCOMMGPRSNCMEAS_C,
    PS_FILE_ID_GAS_GCOMMGPRSPULBIC_C,
    PS_FILE_ID_GAS_GCOMMGPRSRESELMEAS_C,
    PS_FILE_ID_GAS_GCOMMGSMDEDICATEDMEAS_C,
    PS_FILE_ID_GAS_GCOMMGSMIDLEMEAS_C,
    PS_FILE_ID_GAS_GCOMMMAIN_C,
    PS_FILE_ID_GAS_GCOMSIMEASINFOMATION_C,
    PS_FILE_ID_GAS_GCOMPUBLIC_C,
    PS_FILE_ID_GAS_GCOMSICOMM_C,
    PS_FILE_ID_GAS_GCOMSIFSM_C,
    PS_FILE_ID_GAS_GCOMSINCELLBCCH_C,
    PS_FILE_ID_GAS_GCOMSINCELLNORMAL_C,
    PS_FILE_ID_GAS_GCOMSIPROCESSPSI_C,
    PS_FILE_ID_GAS_GCOMSIPROCESSSI_C,
    PS_FILE_ID_GAS_GCOMSISCELLBCCH_C,
    PS_FILE_ID_GAS_GCOMSISCELLBCCHGPRSPERIOD_C,
    PS_FILE_ID_GAS_GCOMSISCELLBCCHGSMPERIOD_C,
    PS_FILE_ID_GAS_GCOMSISCELLDEDICATE_C,
    PS_FILE_ID_GAS_GCOMSISCELLINACTIVE_C,
    PS_FILE_ID_GAS_GCOMSISCELLNORMAL_C,
    PS_FILE_ID_GAS_GCOMSISCELLPBCCH_C,
    PS_FILE_ID_GAS_GCOMSISCELLPACKETSISTATUS_C,
    PS_FILE_ID_GAS_GCOMSISCELLBCCHENHRECEIVE_C,
    PS_FILE_ID_GAS_GCOMSINETCTRLMEASPARAM_C,
    PS_FILE_ID_GAS_GCOMTOGRRPARAMS_C,
    PS_FILE_ID_GAS_GCOMTORRPARAMS_C,
    PS_FILE_ID_GAS_GRRBUILDMSG_C,
    PS_FILE_ID_GAS_GRRCOMM_C,
    PS_FILE_ID_GAS_GRRFSML1PROC_C,
    PS_FILE_ID_GAS_GRRFSML2ABNORMAL_C,
    PS_FILE_ID_GAS_GRRFSML2ACS_C,
    PS_FILE_ID_GAS_GRRFSML2INITACS_C,
    PS_FILE_ID_GAS_GRRFSML2TRANSF_C,
    PS_FILE_ID_GAS_GRRFSML3TRANSF_C,
    PS_FILE_ID_GAS_GRRIMMEDASSIGN_C,
    PS_FILE_ID_GAS_GRRMAIN_C,
    PS_FILE_ID_GAS_GRRPDCHASSIGN_C,
    PS_FILE_ID_GAS_GRRPKTDOWNLINKASSIGN_C,
    PS_FILE_ID_GAS_GRRPKTTIMESLOTRECFG_C,
    PS_FILE_ID_GAS_GRRPKTUPLINKASSIGN_C,
    PS_FILE_ID_GAS_GRRTBFCFG_C,
    PS_FILE_ID_GAS_GRRCTX_C,
    PS_FILE_ID_GAS_RRABNORMALRELEASE_C,
    PS_FILE_ID_GAS_RRASSIGNCMD_C,
    PS_FILE_ID_GAS_RRBUILDMSG_C,
    PS_FILE_ID_GAS_RRCELLCHANGEORDER_C,
    PS_FILE_ID_GAS_RRCHANNELMODEMODIFY_C,
    PS_FILE_ID_GAS_RRCHANNELRELEASE_C,
    PS_FILE_ID_GAS_RRCIPHERMODECMD_C,
    PS_FILE_ID_GAS_RRCOMMFUNC_C,
    PS_FILE_ID_GAS_RRCONNECTION_C,
    PS_FILE_ID_GAS_RRCONTEXTHANDLER_C,
    PS_FILE_ID_GAS_RRFREQREDEF_C,
    PS_FILE_ID_GAS_RRHANDOVER_C,
    PS_FILE_ID_GAS_RRHANDOVERTOGSM_C,
    PS_FILE_ID_GAS_RRHANDOVERTOUTRAN_C,
    PS_FILE_ID_GAS_RRMAIN_C,
    PS_FILE_ID_GAS_RRMMABORT_C,
    PS_FILE_ID_GAS_RRMMCHANNELRELEASE_C,
    PS_FILE_ID_GAS_RRMSGVALID_C,
    PS_FILE_ID_GAS_RRPDCHASSIGN_C,
    PS_FILE_ID_GAS_RRPHYRADIOLINKFAILURE_C,
    PS_FILE_ID_GAS_RRRADIOLINKFAILURE_C,
    PS_FILE_ID_GAS_RRSAP3EST_C,
    PS_FILE_ID_PS_GASHELP_C,
    PS_FILE_ID_GAS_GCOMCVPLMNBGSEARCH_C,
    PS_FILE_ID_GAS_GCOMMVPLMNBGSEARCH_C,
    PS_FILE_ID_GAS_GCOMSINCELLBCCHVPLMNBGSEARCH_C,
    PS_FILE_ID_GAS_GCBSMAIN_C,
    PS_FILE_ID_GAS_GCBSCOMMFUNC_C,
    PS_FILE_ID_GAS_GCBSFSMIDLE_C,
    PS_FILE_ID_GAS_GCBSFSMACTIVE_C,
    PS_FILE_ID_GAS_GCBSFSMINACTIVE_C,
    PS_FILE_ID_GAS_GCBSFSMTBL_C,
    PS_FILE_ID_GAS_GCBSFSML2ACTIVE_C,
    PS_FILE_ID_CSN1DATATYPES_C,
    PS_FILE_ID_CSN1LIB_C,
    PS_FILE_ID_DOWNLINK_RLC_MAC_C,
    PS_FILE_ID_ED_C_C,
    PS_FILE_ID_ED_C_RECOG_C,
    PS_FILE_ID_ED_LIB_C,
    PS_FILE_ID_UPLINK_RLC_MAC_C,
    PS_FILE_ID_USERDEFINEDDATATYPES_C,
    PS_FILE_ID_PLENDOWNLINK_C,
    PS_FILE_ID_L3DOWNLINK_C,
    PS_FILE_ID_L3UPLINK_C,
    PS_FILE_ID_GASGCOMCL2FSMRESELG2L_C,
    PS_FILE_ID_GASGCOMCL2FSMRESELL2G_C,
    PS_FILE_ID_GAS_GCOMCLTECELLRESELCOMM_C,
    PS_FILE_ID_GAS_GCOMMFSMTBL_C,
    PS_FILE_ID_GASGCOMML2FSMLTECONNECTMEAS_C,
    PS_FILE_ID_GASGCOMML2FSMLTEIDLEMEAS_C,
    PS_FILE_ID_GAS_GCOMSIPROCESSSIR8_C,
    PS_FILE_ID_GAS_GCOMSIPROCESSSIR9_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2LRESEL_C,
    PS_FILE_ID_GASGCOMCPREPROCESS_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2LREDIR_C,
    PS_FILE_ID_GAS_GCOMCL2FSMREDIRECTEDL2G_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2LCCO_C,
    PS_FILE_ID_GASGCOMCL2FSMSYSCFG_C,
    PS_FILE_ID_GASGCOMCL2FSMNASSUSP_C,
    PS_FILE_ID_GASGCOMCL2FSMPWROFF_C,
    PS_FILE_ID_GASGCOMCSNDGPHYMSG_C,
    PS_FILE_ID_GAS_GCOMCSNDINTERNALMSG_C,
    PS_FILE_ID_GASGCOMCSNDLRRCMSG_C,
    PS_FILE_ID_GASGCOMCL2FSMBGGSEARCHL_C,
    PS_FILE_ID_GAS_MNTN_C,
    PS_FILE_ID_GAS_GCOMCAPABILITY_C,
    PS_FILE_ID_GAS_GCOM_CTX_LTE_C,
    PS_FILE_ID_GAS_GCOM_PUBLIC_LTE_C,
    PS_FILE_ID_GAS_GCOMC_CMP_MSG_PRI_C,
    PS_FILE_ID_GAS_GCOMC_CMP_MSG_PRI_LTE_C,
    PS_FILE_ID_GAS_GCOMM_COMM_LTE_C,
    PS_FILE_ID_GAS_GCOMSI_CTX_LTE_C,
    PS_FILE_ID_GAS_GCOMSI_COMM_LTE_C,
    PS_FILE_ID_GASGCOMCSNDOMMSG_C,
    PS_FILE_ID_GASGCOMCSNDOMMSG_LTE_C,
    PS_FILE_ID_GASGCOMMSNDOMMSG_LTE_C,
    PS_FILE_ID_GASGCOMCL2FSMSLAVEMODELOWPOWER_C,
    PS_FILE_ID_GAS_GCOMCL2FSMLTEANRGSM_C,
    PS_FILE_ID_GASGCOMCSNDWPHYMSG_C,
    PS_FILE_ID_GASGCOMCSNDWRRMSG_C,
    PS_FILE_ID_GASGCOMCSNDNASMSG_C,
    PS_FILE_ID_GASGCOMCCTXLTE_C,
    PS_FILE_ID_GASGCOMCBUILDMSG_C,
    PS_FILE_ID_GASGCOMCBUILDMSGLTE_C,
    PS_FILE_ID_GASGRRPREPROCESS_C,
    PS_FILE_ID_PER_MAIN_COMM_C,
    PS_FILE_ID_PER_MAIN_GAS_C,
    PS_FILE_ID_GASASN1API_C,
    PS_FILE_ID_GASRRAPPINFO_C,
    PS_FILE_ID_GASRRPREPROCESS_C,
    PS_FILE_ID_GASLCSCTX_C,
    PS_FILE_ID_GASLCSCOMM_C,
    PS_FILE_ID_GASLCSMAIN_C,
    PS_FILE_ID_GASLCSFSMTBL_C,
    PS_FILE_ID_GASLCSSAVERRLPMSG_C,
    PS_FILE_ID_GASLCSFILLRRLPMSG_C,
    PS_FILE_ID_GASLCSSNDRRMSG_C,
    PS_FILE_ID_GASLCSSNDMTAMSG_C,
    PS_FILE_ID_GASLCSFSML1IDLE_C,
    PS_FILE_ID_GASLCSFSML1ASSISTDATADELIVERY_C,
    PS_FILE_ID_GASLCSFSML1LOCATION_C,
    PS_FILE_ID_GASDYNBUF_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2TRESEL_C,
    PS_FILE_ID_GAS_GCOMCL2FSMSLAVEMODECTRL_C,
    PS_FILE_ID_GASGCOMCSNDTRRCMSG_C,
    PS_FILE_ID_GASGCOMML2FSMTDSMEAS_C,
    PS_FILE_ID_GAS_GCOMCL2FSMX2GCCO_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2TCCO_C,
    PS_FILE_ID_GAS_RRL2FSMHANDOVERT2G_C,
    PS_FILE_ID_GASRRCMPMSGPRI_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2WRESEL_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2WCCO_C,
    PS_FILE_ID_GASGCOMCCOMM_C,
    PS_FILE_ID_GASGCOMSI_C,
    PS_FILE_ID_GASGCOMSISNDINTERNALMSG_C,
    PS_FILE_ID_GASGCOMSIL2FSMINACTIVESCELLBCCH_C,
    PS_FILE_ID_GASGCOMSIL2FSMINACTIVESEARCHINGBCCH_C,
    PS_FILE_ID_GAS_GCOMCL2FSMUTRANMODE_C,
    PS_FILE_ID_GASGCOMSICMPMSGPRI_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2TREDIR_C,
    PS_FILE_ID_GAS_ERRLOG_C,
    PS_FILE_ID_GAS_NET_MONITOR_C,
    PS_FILE_ID_GASGCOMCL2FSMGNETSCANG_C,
    PS_FILE_ID_GASGCOMCL2FSMGNETSCANW_C,
    PS_FILE_ID_GASGCOMCL2FSMWNETSCANG_C,
    PS_FILE_ID_GAS_RRL2FSMHANDOVERL2G_C,
    PS_FILE_ID_GASGCOMCL2FSMPLMNSPECSEARCH_C,
    PS_FILE_ID_GASGCOMCL2FSMGOOSSEARCH_C,
    PS_FILE_ID_GAS_GCOMCL2FSMPLMNLISTSEARCH_C,
    PS_FILE_ID_GAS_RFRESCTRL_C,
    PS_FILE_ID_GASGCOMCL2FSMRLFAILURESEARCH_C,
    PS_FILE_ID_GAS_GCOMCL2FSMREDIRECTEDG2G_C,
    PS_FILE_ID_GASGCOMCL2FSMXOOSSEARCH_C,
    PS_FILE_ID_GASGCOMCL2FSMREDIRW2G_C,
    PS_FILE_ID_GASGCOMML2FSMFDDMEAS_C,
    PS_FILE_ID_GASGCOMCL2FSMBGXSEARCHG_C,

    PS_FILE_ID_GAS_GCOMCL2FSMG2WREDIR_C,
    PS_FILE_ID_GAS_GCOMCL2FSMPLMNGETGEOSEARCH_C,
    PS_FILE_ID_GAS_MNTN_G2X_C,
    PS_FILE_ID_GAS_INTER_HO_ERRLOG_C,
    PS_FILE_ID_GAS_MNTN_L2G_C,
    PS_FILE_ID_GASGCOMSIL2FSMINACTIVEPARALLELSEARCH_C,
    PS_FILE_ID_GASGCOMCL2FSMRESELG2G_C,
    PS_FILE_ID_GASGCOMSIL2FSMNCELLPARALLELSEARCH_C,
    PS_FILE_ID_GASGCOMCSNDCSSMSG_C,
    PS_FILE_ID_GAS_MNTN_NW_SRCH_C,
    PS_FILE_ID_GAS_MNTN_RR_CONN_C,
    PS_FILE_ID_GASGCOMMPREPROCESS_C,
    PS_FILE_ID_ED_GSM_COMMON_ED_LIB_C,
    PS_FILE_ID_ED_GSM_COMMON_CSN1LIB_C,
    PS_FILE_ID_GAS_MNTN_CTX_C,
    PS_FILE_ID_GAS_MNTN_INTRA_HO_C,
    PS_FILE_ID_GAS_MNTN_AIR_MSG_C,
    PS_FILE_ID_GASGCOMCSNDIMSAMSG_C,
    PS_FILE_ID_GAS_MNTN_CELL_SPECIAL_INFO_C,
    PS_FILE_ID_GASGCOMMIRAT_C,
    PS_FILE_ID_GASGCOMMIRATFSM_C,
    PS_FILE_ID_GASGCOMMIRATPREPROCESS_C,
    PS_FILE_ID_GASGCOMMIRATMAIN_C,
    PS_FILE_ID_GASGCOMMIRATL1FSM_C,
    PS_FILE_ID_GASGCOMMIRATCOMM_C,
    PS_FILE_ID_GASGCOMMIRATFSMLTEMEAS_C,
    PS_FILE_ID_GASGCOMMIRATFSMUTRANMEAS_C,
    PS_FILE_ID_GAS_GCOMMCUSTOMIZATION_C,
    PS_FILE_ID_GAS_EXTERN_ALGORITHM_C,
    PS_FILE_ID_RRSHORTPD_C,
    PS_FILE_ID_RRSHORTPDUPLINK_C,
    PS_FILE_ID_ED_GSM_COMMON_CSN1CLIB_C,
    PS_FILE_ID_TS44018SUPPORT_C,
    PS_FILE_ID_GASGCOMCL2FSMC2RESELG2G_C,
    PS_FILE_ID_GAS_GCOMCL2FSMCCOG2G_C,
    PS_FILE_ID_GASGCOMCL2FSMSTARTINGUP_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2XREDIRINIT_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2XRESELINIT_C,
    PS_FILE_ID_GAS_GCOMCL2FSMG2XROLLBACK_C,
    PS_FILE_ID_GAS_GCOMCL2FSMX2GRESEL_C,

    GAS_FILE_ID_BUTT = CAS_TEAM_FILE_ID - 1

}GAS_FILE_ID_DEFINE_ENUM;

typedef unsigned long  GAS_FILE_ID_DEFINE_ENUM_UINT32;

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */


#endif


