/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2020. All rights reserved.
 * foss@huawei.com
 *
 * If distributed as part of the Linux kernel, the following license terms
 * apply:
 *
 * * This program is free software; you can redistribute it and/or modify
 * * it under the terms of the GNU General Public License version 2 and
 * * only version 2 as published by the Free Software Foundation.
 * *
 * * This program is distributed in the hope that it will be useful,
 * * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * * GNU General Public License for more details.
 * *
 * * You should have received a copy of the GNU General Public License
 * * along with this program; if not, write to the Free Software
 * * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
 *
 * Otherwise, the following license terms apply:
 *
 * * Redistribution and use in source and binary forms, with or without
 * * modification, are permitted provided that the following conditions
 * * are met:
 * * 1) Redistributions of source code must retain the above copyright
 * *    notice, this list of conditions and the following disclaimer.
 * * 2) Redistributions in binary form must reproduce the above copyright
 * *    notice, this list of conditions and the following disclaimer in the
 * *    documentation and/or other materials provided with the distribution.
 * * 3) Neither the name of Huawei nor the names of its contributors may
 * *    be used to endorse or promote products derived from this software
 * *    without specific prior written permission.
 *
 * * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef PS_LOG_LNAS_FILE_ID_DEFINE_H
#define PS_LOG_LNAS_FILE_ID_DEFINE_H

#include "ps_log_file_id_base.h"
#include "ps_log_print.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

typedef enum
{

    PS_FILE_ID_NASCOMMBUFFER_C = LNAS_TEAM_FILE_ID,

    PS_FILE_ID_NASCOMMDEBUG_C,
    PS_FILE_ID_NASCOMMPRINT_C,

    PS_FILE_ID_NASEMMPLMN_C,

    PS_FILE_ID_NASEMMPLMNPUBLIC_C,
    PS_FILE_ID_NASEMMPUBUCNMSGDECODE_C,
    PS_FILE_ID_NASEMMPUBSUSPEND_C,
    PS_FILE_ID_NASEMMPUBURESUME_C,

    PS_FILE_ID_NASEMMSECUAUTH_C,
    PS_FILE_ID_NASEMMSECUPROTECT_C,
    PS_FILE_ID_NASEMMSECUOM_C,
    PS_FILE_ID_NASEMMSECUSMC_C,
    PS_FILE_ID_NASEMMSECUSOFTUSIM_C,

    PS_FILE_ID_NASEMMCMAIN_C,

    PS_FILE_ID_NASEMMCPUBLIC_C,
    PS_FILE_ID_NASEMMCRCVMSG_C,
    PS_FILE_ID_NASEMMCSENDMSG_C,
    PS_FILE_ID_NASMMPUBLIC_C,

    PS_FILE_ID_NASMMPUBMFSM_C,
    PS_FILE_ID_NASMMPUBMNVIM_C,
    PS_FILE_ID_NASMMPUBMNVIMOSA_C,
    PS_FILE_ID_NASMMPUBMOM_C,
    PS_FILE_ID_NASMMPUBMPRINT_C,

    PS_FILE_ID_NASMMTEST_C,

    PS_FILE_ID_NAS_ESM_MAIN_C,
    PS_FILE_ID_NAS_ESM_PUBLIC_C,
    PS_FILE_ID_NAS_ESM_CTX_C,
    PS_FILE_ID_NAS_ESM_NV_PROC_C,
    PS_FILE_ID_NAS_ESM_BUFFER_PTI_PROC_C,
    PS_FILE_ID_NAS_ESM_BUFFER_NDIS_CONN_PROC_C,
    PS_FILE_ID_NAS_ESM_OM_C,
    PS_FILE_ID_NAS_ESM_CHR_C,
    PS_FILE_ID_NAS_ESM_LOG_FILTER_C,

    PS_FILE_ID_NAS_ESM_NW_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ACT_DEDICTD_BEARER_REQ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ACT_DEFLT_BEARER_REQ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ACT_DEFLT_BEARER_REQ_NR_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_RES_ALLOC_REJ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_RES_MOD_REJ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DEACT_BEARER_REQ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_MOD_BEARER_REQ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_MOD_BEARER_REQ_NR_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_PDN_CON_REJ_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_PDN_DISCON_REJ_PROC_C,

    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_ACT_DEFAULT_BEARER_REQ_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_BASE_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_BASE_PCO_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_BASE_PCO_NR_ITEM_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_BASE_QOS_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_DECODE_BASE_TFT_C,

    PS_FILE_ID_NAS_ESM_NW_MSG_ENCODE_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ENCODE_PDN_CONN_REQ_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ENCODE_PROC_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ENCODE_BASE_PCO_C,
    PS_FILE_ID_NAS_ESM_NW_MSG_ENCODE_BASE_TFT_C,

    PS_FILE_ID_NAS_ESM_TAF_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_TAF_MSG_GU_PDP_CTX_PROC_C,
    PS_FILE_ID_NAS_ESM_TAF_MSG_PDP_SETUP_PROC_C,
    PS_FILE_ID_NAS_ESM_TAF_MSG_PDP_REL_PROC_C,
    PS_FILE_ID_NAS_ESM_TAF_MSG_PDP_MOD_PROC_C,
    PS_FILE_ID_NAS_ESM_TAF_SND_MSG_C,
    PS_FILE_ID_NAS_ESM_DSM_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_EMM_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_EMM_MSG_PDN_CON_IND_PROC_C,
    PS_FILE_ID_NAS_ESM_EMM_MSG_AIR_SND_RSLT_PROC_C,
    PS_FILE_ID_NAS_ESM_EMM_SND_MSG_C,
    PS_FILE_ID_NAS_ESM_NRSM_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_NRSM_MSG_NON_N26_PROC_C,
    PS_FILE_ID_NAS_ESM_EHSM_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_RABM_MSG_PROC_C,
    PS_FILE_ID_NAS_ESM_TIMER_MSG_PROC_C,

    PS_FILE_ID_NAS_ESM_5G_ESCAPE_PROC_C,
    PS_FILE_ID_NAS_ESM_MBB_CONTROL_STRING_C,
    PS_FILE_ID_NAS_ESM_MBB_PROFILE_SWITCH_C,
    PS_FILE_ID_NAS_ESM_DSDS_PROC_C,
    PS_FILE_ID_NAS_ESM_THROT_PROC_C,
    PS_FILE_ID_NAS_ESM_CDMA_PROC_C,

    PS_FILE_ID_NASRABMAPPMSGPROC_C,
    PS_FILE_ID_NASRABMEMMMSGPROC_C,
    PS_FILE_ID_NASRABMESMMSGPROC_C,
    PS_FILE_ID_NASRABMIPFILTER_C,
    PS_FILE_ID_NASRABMIPFOM_C,

    PS_FILE_ID_NASRABMIPMSGPROC_C,
    PS_FILE_ID_NASRABMMAIN_C,
    PS_FILE_ID_NASRABMPDCPMSGPROC_C,
    PS_FILE_ID_NASRABMRRCMSGPROC_C,
    PS_FILE_ID_NASRABMTCMSGPROC_C,

    PS_FILE_ID_NASRABMTEST_C,
    PS_FILE_ID_NASRABMTIMERMSGPROC_C,
    PS_FILE_ID_IPIPMGLOBAL_C,
    PS_FILE_ID_IPIPMIFACE_C,

    PS_FILE_ID_IPIPMMSGPROC_C,
    PS_FILE_ID_IPIPMOM_C,
    PS_FILE_ID_NASTCEMMMSGPROC_C,
    PS_FILE_ID_NASTCMAIN_C,

    PS_FILE_ID_NASTCNWMSGDECODE_C,
    PS_FILE_ID_NASTCNWMSGENCODE_C,
    PS_FILE_ID_NASTCOMMSGPROC_C,
    PS_FILE_ID_NASTCPDCPMSGPROC_C,
    PS_FILE_ID_NASTCRABMMSGPROC_C,

    PS_FILE_ID_NASTCMTCMSGPROC_C,
    PS_FILE_ID_LNASREPLAYPROC_C,

    PS_FILE_ID_CSS_MAIN_C,
    PS_FILE_ID_CSS_PUBLIC_C,
    PS_FILE_ID_CSS_OM_COMM_C,
    PS_FILE_ID_CSS_OM_CLOUD_C,
    PS_FILE_ID_CSS_OM_SRCH_C,
    PS_FILE_ID_CSS_PROC_COMM_MSG_C,
    PS_FILE_ID_CSS_PROC_TIMER_MSG_C,
    PS_FILE_ID_CSS_PROC_AT_MSG_C,
    PS_FILE_ID_CSS_PROC_IMSA_MSG_C,
    PS_FILE_ID_CSS_PROC_MTA_MSG_C,
    PS_FILE_ID_CSS_PROC_MMC_MSG_C,
    PS_FILE_ID_CSS_PROC_NRRC_MSG_C,
    PS_FILE_ID_CSS_PROC_TRRC_MSG_C,

    PS_FILE_ID_CSS_SRCH_API_C,
    PS_FILE_ID_CSS_SRCH_LPHY_MSG_PROC_C,
    PS_FILE_ID_CSS_SRCH_PUBLIC_C,
    PS_FILE_ID_CSS_SRCH_RAT_RECOG_C,
    PS_FILE_ID_CSS_SRCH_SND_LPHY_MSG_C,

    PS_FILE_ID_CSS_HISTORY_FREQ_API_C,
    PS_FILE_ID_CSS_HISTORY_FREQ_AS_MSG_PROC_C,
    PS_FILE_ID_CSS_HISTORY_FREQ_PUBLIC_C,

    PS_FILE_ID_CSS_CLOUD_BLACK_CELL_API_C,
    PS_FILE_ID_CSS_CLOUD_BLACK_CELL_AT_MSG_PROC_C,
    PS_FILE_ID_CSS_CLOUD_BLACK_CELL_COMM_MSG_PROC_C,
    PS_FILE_ID_CSS_CLOUD_BLACK_CELL_PUBLIC_C,

    PS_FILE_ID_CSS_CLOUD_BAND_FREQ_PUBLIC_C,
    PS_FILE_ID_CSS_CLOUD_BAND_FREQ_API_C,
    PS_FILE_ID_CSS_CLOUD_BAND_FREQ_AT_MSG_PROC_C,
    PS_FILE_ID_CSS_CLOUD_BAND_FREQ_NV_PROC_C,
    PS_FILE_ID_CSS_CLOUD_BAND_FREQ_COMM_MSG_PROC_C,

    PS_FILE_ID_CSS_PLMN_DEPLOY_API_C,
    PS_FILE_ID_CSS_PLMN_DEPLOY_RPT_C,
    PS_FILE_ID_CSS_PLMN_DEPLOY_AT_MSG_PROC_C,
    PS_FILE_ID_CSS_PLMN_DEPLOY_PUBLIC_C,

    PS_FILE_ID_CSS_CLOUD_LINE_API_C,
    PS_FILE_ID_CSS_CLOUD_LINE_AS_MSG_PROC_C,
    PS_FILE_ID_CSS_CLOUD_LINE_AT_MSG_COMM_PROC_C,
    PS_FILE_ID_CSS_CLOUD_LINE_AT_MSG_GSM_PROC_C,
    PS_FILE_ID_CSS_CLOUD_LINE_AT_MSG_LTE_NR_PROC_C,
    PS_FILE_ID_CSS_CLOUD_LINE_PUBLIC_C,

    PS_FILE_ID_CSS_EMC_SRCH_PROC_C,

    PS_FILE_ID_NAS_LPP_DECODE_C,
    PS_FILE_ID_NAS_LPP_EMM_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_ENCODE_C,
    PS_FILE_ID_NAS_LPP_ENCODE_BASE_C,
    PS_FILE_ID_NAS_LPP_ENCODE_ECID_AND_OTDOA_C,
    PS_FILE_ID_NAS_LPP_ENCODE_EPDU_C,
    PS_FILE_ID_NAS_LPP_ENCODE_GNSS_C,
    PS_FILE_ID_NAS_LPP_ENCODE_GNSS_ASSIST_REQ_C,
    PS_FILE_ID_NAS_LPP_ENCODE_GNSS_LOCATION_C,
    PS_FILE_ID_NAS_LPP_INTRA_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_LRRC_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_MAIN_C,
    PS_FILE_ID_NAS_LPP_MTA_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_PUBLIC_C,
    PS_FILE_ID_NAS_LPP_TIMER_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_FSM_C,
    PS_FILE_ID_NAS_LPP_OM_C,
    PS_FILE_ID_NAS_LPP_ETC_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_LCS_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_FILL_NRECID_UPLINK_MSG_C,
    PS_FILE_ID_NAS_LPP_ENCODE_NRECID_MSG_C,
    PS_FILE_ID_NAS_LPP_DECODE_NRECID_MSG_C,
    PS_FILE_ID_NAS_LPP_MMA_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_NRMM_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_NRRC_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_NRRC_MSG_SEND_C,
    PS_FILE_ID_NAS_LPP_LOG_FILTER_C,
    PS_FILE_ID_NAS_LPP_CTX_C,
    PS_FILE_ID_NAS_LPP_READ_NV_C,
    PS_FILE_ID_NAS_LPP_TIMER_PULIC_C,
    PS_FILE_ID_NAS_LPP_FILL_UPLINK_MSG_OTDOA_C,
    PS_FILE_ID_NAS_LPP_FILL_UPLINK_MSG_ECID_C,
    PS_FILE_ID_NAS_LPP_FILL_UPLINK_MSG_EPDU_C,
    PS_FILE_ID_NAS_LPP_FILL_UPLINK_MSG_GNSS_C,
    PS_FILE_ID_NAS_LPP_FILL_UPLINK_MSG_C,
    PS_FILE_ID_NAS_LPP_AIR_MSG_OTDOA_PROC_C,
    PS_FILE_ID_NAS_LPP_AIR_MSG_GNSS_PROC_C,
    PS_FILE_ID_NAS_LPP_SESSION_TRANS_MANAGEMENT_C,
    PS_FILE_ID_NAS_LPP_AIR_MSG_PROC_C,
    PS_FILE_ID_NAS_LPP_DECODE_BASE_C,
    PS_FILE_ID_NAS_LPP_DECODE_EPDU_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_COMM_ASSISTDATA_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_GENERIC_ASSISTDATA_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_GENERIC_ASSISTDATA_ALMANAC_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_GENERIC_ASSISTDATA_EXT_BDS_C,
    PS_FILE_ID_NAS_LPP_DECODE_GNSS_GENERIC_ASSISTDATA_NAV_MODEL_C,
    PS_FILE_ID_NAS_LPP_DECODE_OTDOA_AND_ECID_C,
    PS_FILE_ID_NAS_LPP_UPLINK_MSGBUF_MANAGE_C,

    PS_FILE_ID_NASCOMMPUBLIC_C,

    PS_FILE_ID_NASTHROTALGMAIN_C,
    PS_FILE_ID_NASTHROTALGCOMM_C,
    PS_FILE_ID_NASTHROTALGFOROTHEROPERATOR_C,
    PS_FILE_ID_NASTHROTALGFOR3GPP_C,
    PS_FILE_ID_NASTHROTSMTHROTPROC_C,
    PS_FILE_ID_NASTHROTALGFORWIFIPROC_C,

    PS_FILE_ID_NASETCLRRCMSGPROC_C,
    PS_FILE_ID_NASTCTHROTMSGPROC_C,
    PS_FILE_ID_NASTCNRMMMSGPROC_C,
    PS_FILE_ID_NASTCSDAPMSGPROC_C,
    PS_FILE_ID_NASTCNRRCMSGPROC_C,
    PS_FILE_ID_NASTHROTALGOM_C,
    PS_FILE_ID_VNASMAIN_C,
    PS_FILE_ID_VNASTIMERMSGPROC_C,
    PS_FILE_ID_VNASMTAMSGPROC_C,
    PS_FILE_ID_VNASVRRCMSGPROC_C,
    PS_FILE_ID_VNASPUBLIC_C,
    PS_FILE_ID_NASTHROT3GPPLADNT3396_C,
    PS_FILE_ID_NASTHROT3GPPBACKOFF_C,
    PS_FILE_ID_VNASATPROC_C,
    PS_FILE_ID_VNASPROC_C,

    PS_FILE_ID_VTCMAIN_C,
    PS_FILE_ID_VTCPUBLIC_C,
    PS_FILE_ID_VTCATMSGPROC_C,
    PS_FILE_ID_VTCCDSMSGPROC_C,
    PS_FILE_ID_VTCTIMERMSGPROC_C,
    PS_FILE_ID_VTCVMACMSGPROC_C,
    PS_FILE_ID_VTCVPDCPMSGPROC_C,
    PS_FILE_ID_VTCVRRCMSGPROC_C,
    PS_FILE_ID_NASTHROT3GPPECALL_C,
    PS_FILE_ID_NAS_THROT_OM_KEY_EVENT_C,
    PS_FILE_ID_NAS_THROT_MAX_PDN_NUM_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_SUBSCRIBE_PROC_C,
    PS_FILE_ID_NAS_THROT_IMS_APN_REL_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_IMS_APN_REL_PROC_C,
    PS_FILE_ID_NAS_THROT_APN_CTRL_LIST_PROC_C,
    PS_FILE_ID_NAS_THROT_PDN_ESCAPE_CTRL_C,
    PS_FILE_ID_NAS_THROT_TIMER_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3346_PROC_C,
    PS_FILE_ID_NAS_THROT_T3346_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3396_PROC_C,
    PS_FILE_ID_NAS_THROT_T3396_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3396_LADN_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3396_LADN_PROC_C,
    PS_FILE_ID_NAS_THROT_T3396_CUSTOMIZED_BY_PLMN_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3396_CUSTOMIZED_BY_PLMN_PROC_C,
    PS_FILE_ID_NAS_THROT_BACKOFF_TIMER_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_BACKOFF_TIMER_PROC_C,
    PS_FILE_ID_NAS_THROT_ECALL_TIMER_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_ECALL_TIMER_PROC_C,
    PS_FILE_ID_NAS_THROT_T3584_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3584_PROC_C,
    PS_FILE_ID_NAS_THROT_T3585_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_T3585_PROC_C,
    PS_FILE_ID_NAS_THROT_SBM_TIMER_PROC_C,
    PS_FILE_ID_NAS_THROT_MMC_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_TC_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_EMM_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_IMSA_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_NRSM_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_NRTHROT_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_TIMER_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_USIM_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_AT_MSG_PROC_C,
    PS_FILE_ID_NAS_THROT_API_COMM_C,
    PS_FILE_ID_NAS_THROT_API_ESM_C,
    PS_FILE_ID_NAS_THROT_API_MMC_C,
    PS_FILE_ID_NAS_THROT_PUBLIC_C,
    PS_FILE_ID_NAS_THROT_COMM_CONTEXT_C,

    PS_FILE_ID_NASLMMCOMPATIBILITYOM_C,

    /* emm/its */
    PS_FILE_ID_NAS_EMM_ITS_CTX_C,
    PS_FILE_ID_NAS_EMM_ITS_MMC_RESUME_COMM_C,
    PS_FILE_ID_NAS_EMM_ITS_MMC_RESUME_GU2L_C,
    PS_FILE_ID_NAS_EMM_ITS_MMC_RESUME_NR2L_C,
    PS_FILE_ID_NAS_EMM_ITS_MMC_SUSPEND_C,
    PS_FILE_ID_NAS_EMM_ITS_RESUME_COMM_C,
    PS_FILE_ID_NAS_EMM_ITS_REVERSE_C,
    PS_FILE_ID_NAS_EMM_ITS_RRC_RESUME_COMM_C,
    PS_FILE_ID_NAS_EMM_ITS_RRC_RESUME_GU2L_C,
    PS_FILE_ID_NAS_EMM_ITS_RRC_RESUME_NR2L_C,
    PS_FILE_ID_NAS_EMM_ITS_RRC_SUSPEND_C,
    PS_FILE_ID_NAS_EMM_ITS_SUSPEND_COMM_C,
    PS_FILE_ID_NAS_EMM_ITS_SYSCFG_PROC_C,
    PS_FILE_ID_NAS_EMM_ITS_TIMER_C,
    PS_FILE_ID_NAS_EMM_ITS_PUBLIC_C,

    /* emm/interface */
    PS_FILE_ID_NAS_EMM_ERABM_SND_MSG_C,
    PS_FILE_ID_NAS_EMM_ESM_SND_MSG_C,
    PS_FILE_ID_NAS_EMM_LRRC_SND_MSG_C,
    PS_FILE_ID_NAS_EMM_MMC_SND_MSG_C,
    PS_FILE_ID_NAS_EMM_NRMM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_GMM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_USIM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_THROT_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_TAF_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_TC_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_MM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_INTRA_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_RRM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_LRRC_RECV_MSG_C,
    PS_FILE_ID_NAS_EMM_ESM_RECV_MSG_C,
    PS_FILE_ID_NAS_EMM_REGM_SND_MSG_C,
    PS_FILE_ID_NAS_EMM_REGM_SND_ATTACH_RSLT_C,
    PS_FILE_ID_NAS_EMM_REGM_SND_TAU_RSLT_C,
    PS_FILE_ID_NAS_EMM_REGM_RECV_MSG_C,
    PS_FILE_ID_NAS_EMM_REGM_NR_ACTION_RSLT_PROC_C,
    PS_FILE_ID_NAS_EMM_REGM_ATTACH_REQ_PROC_C,
    PS_FILE_ID_NAS_EMM_REGM_DETACH_REQ_PROC_C,
    PS_FILE_ID_NAS_EMM_LCS_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_BASTET_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_IMSA_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_INTER_MODEM_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_LPP_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_MMC_RECV_MSG_C,
    PS_FILE_ID_NAS_EMM_SMS_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_MTA_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_COMM_API_C,
    PS_FILE_ID_NAS_EMM_LRRC_API_C,
    PS_FILE_ID_NAS_EMM_USIM_OUT_PROC_C,
    PS_FILE_ID_NAS_EMM_GU_ACTION_RESULT_PROC_C,
    PS_FILE_ID_NAS_EMM_GUNAS_API_ENCAPSULE_C,
    PS_FILE_ID_NAS_EMM_LRRC_SND_PLMN_SEARCH_MSG_C,
    PS_FILE_ID_NAS_EMM_PSOM_MSG_PROC_C,

    /* emm/cm */
    PS_FILE_ID_NAS_EMM_CM_CDMA_ESR_C,
    PS_FILE_ID_NAS_EMM_CM_AIR_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_CM_CTX_C,
    PS_FILE_ID_NAS_EMM_CM_DECODE_C,
    PS_FILE_ID_NAS_EMM_CM_ENCODE_C,
    PS_FILE_ID_NAS_EMM_CM_OM_C,
    PS_FILE_ID_NAS_EMM_CM_PUBLIC_C,
    PS_FILE_ID_NAS_EMM_CM_TIMER_C,
    PS_FILE_ID_NAS_EMM_CM_EMC_ESR_C,
    PS_FILE_ID_NAS_EMM_CM_MRRC_CONN_EST_C,
    PS_FILE_ID_NAS_EMM_CM_MRRC_REL_C,
    PS_FILE_ID_NAS_EMM_CM_MRRC_DATA_REQ_C,
    PS_FILE_ID_NAS_EMM_CM_NRM_ESR_C,
    PS_FILE_ID_NAS_EMM_CM_SER_ABNORMAL_C,
    PS_FILE_ID_NAS_EMM_CM_SER_MRRC_DATA_REQ_C,
    PS_FILE_ID_NAS_EMM_CM_SER_REJECT_C,
    PS_FILE_ID_NAS_EMM_CM_SER_SUCC_C,
    PS_FILE_ID_NAS_EMM_CM_SER_TRIGGER_C,

    /* emm/cp */
    PS_FILE_ID_NAS_EMM_CP_GUTI_C,
    PS_FILE_ID_NAS_EMM_CP_IDEN_C,
    PS_FILE_ID_NAS_EMM_CP_AUTH_CTX_C,
    PS_FILE_ID_NAS_EMM_CP_BSP_API_C,
    PS_FILE_ID_NAS_EMM_CP_DECODE_C,
    PS_FILE_ID_NAS_EMM_CP_ENCODE_C,
    PS_FILE_ID_NAS_EMM_CP_OM_C,
    PS_FILE_ID_NAS_EMM_CP_PUBLIC_C,
    PS_FILE_ID_NAS_EMM_CP_TIMER_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_AUTH_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_CTX_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_FSM_TBL_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_KEY_DERIVE_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_PROTECT_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_SMC_C,
    PS_FILE_ID_NAS_EMM_CP_SECU_UNPROTECT_C,

    /* emm/sp */
    PS_FILE_ID_NAS_EMM_SP_ATTACH_ABNORMAL_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_ACCEPT_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_REJECT_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_TRIGGER_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_CTX_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_DECODE_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_MRRC_DATA_REQ_C,
    PS_FILE_ID_NAS_EMM_SP_ATTACH_ENCODE_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_MRRC_DATA_REQ_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_CONLLISION_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_CTX_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_TRIGGER_PARA_CHANGE_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_TRIGGER_COMM_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_TRIGGER_SYSINFO_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_DECODE_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_ABNORMAL_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_ACCEPT_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_REJECT_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_ENCODE_C,
    PS_FILE_ID_NAS_EMM_SP_TAU_TRIGGER_INTER_SYSINFO_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_CTX_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_ABNORMAL_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_TRIGGER_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_MRRC_DATA_REQ_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_ENCODE_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_CN_MSG_PROC_C,
    PS_FILE_ID_NAS_EMM_SP_DETACH_DECODE_C,
    PS_FILE_ID_NAS_EMM_SP_PROTOCAL_TIMER_C,
    PS_FILE_ID_NAS_EMM_SP_NON_PROTOCAL_TIMER_C,
    PS_FILE_ID_NAS_EMM_SP_ENCODE_C,
    PS_FILE_ID_NAS_EMM_SP_OM_C,
    PS_FILE_ID_NAS_EMM_SP_PUBLIC_C,
    PS_FILE_ID_NAS_EMM_SP_RADIO_CAPABILITY_CHANGE_C,
    PS_FILE_ID_NAS_EMM_SP_DECODE_C,
    PS_FILE_ID_NAS_EMM_SP_RADIO_CAPABILITY_CHANGE_LRRC_TRIGGER_C,
    PS_FILE_ID_NAS_EMM_SP_RADIO_CAPABILITY_CHANGE_ESM_TRIGGER_C,
    PS_FILE_ID_NAS_EMM_SP_RADIO_CAPABILITY_CHANGE_MMC_TRIGGER_C,

    /* emm/comm */
    PS_FILE_ID_NAS_EMM_COMM_FSM_C,
    PS_FILE_ID_NAS_EMM_COMM_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_DT_C,
    PS_FILE_ID_NAS_EMM_COMM_DECODE_C,
    PS_FILE_ID_NAS_EMM_COMM_OM_C,
    PS_FILE_ID_NAS_EMM_COMM_GUNAS_API_ENCAPSULE_C,
    PS_FILE_ID_NAS_EMM_COMM_DATA_STATISTIC_OM_C,
    PS_FILE_ID_NAS_EMM_COMM_BASE_CFG_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_COMPATIBILITY_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_CHR_C,
    PS_FILE_ID_NAS_EMM_COMM_CHR_QUERY_REPORT_C,
    PS_FILE_ID_NAS_EMM_COMM_CHR_DIRECT_STATISTIC_REPORT_C,
    PS_FILE_ID_NAS_EMM_COMM_CHR_DIRECT_NON_STATISTIC_REPORT_C,
    PS_FILE_ID_NAS_EMM_COMM_CHR_NON_DIRECT_REPORT_C,
    PS_FILE_ID_NAS_EMM_COMM_OPR_CUSTZ_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_PROT_FEAT_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_SECU_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_USR_EXPR_OPT_CTX_C,
    PS_FILE_ID_NAS_EMM_COMM_BUF_MSG_PROC_BEFORE_CLEAR_C,
    PS_FILE_ID_NAS_EMM_COMM_ENTRY_C,
    PS_FILE_ID_NAS_EMM_COMM_TIMER_EXP_PROC_C,
    PS_FILE_ID_NAS_EMM_COMM_FSM_TBL_C,
    PS_FILE_ID_NAS_EMM_COMM_PRE_PROC_TBL_C,
    PS_FILE_ID_NAS_EMM_COMM_PRE_PROC_AIR_MSG_C,
    PS_FILE_ID_NAS_EMM_COMM_INTRA_MSG_MANAGEMENT_C,
    PS_FILE_ID_NAS_EMM_COMM_MSG_BUF_MANAGEMENT_C,
    PS_FILE_ID_NAS_EMM_COMM_NETWORK_CFG_C,
    PS_FILE_ID_NAS_EMM_COMM_NR_PUBLIC_C,
    PS_FILE_ID_NAS_EMM_COMM_PLMN_TA_FUNC_C,
    PS_FILE_ID_NAS_EMM_COMM_PTL_T3402_TIMER_C,
    PS_FILE_ID_NAS_EMM_COMM_PTL_TIMER_C,
    PS_FILE_ID_NAS_EMM_COMM_PUBLIC_C,
    PS_FILE_ID_NAS_EMM_COMM_STACK_C,
    PS_FILE_ID_NAS_EMM_COMM_STATE_TIMER_C,
    PS_FILE_ID_NAS_EMM_COMM_TIMER_C,


    /* emm/pwr */
    PS_FILE_ID_NAS_EMM_PWR_OFF_C,
    PS_FILE_ID_NAS_EMM_PWR_OM_C,
    PS_FILE_ID_NAS_EMM_PWR_ON_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_COMM_CAP_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_NR_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_NV_COMM_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_OPR_CUSTZ_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_PROT_FEAT_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_SECU_COMPAT_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_READ_USR_EXPR_OPT_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_SECU_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_TIMER_C,
    PS_FILE_ID_NAS_EMM_PWR_USIM_BACKUP_C,
    PS_FILE_ID_NAS_EMM_PWR_USIM_BASE_OPT_C,
    PS_FILE_ID_NAS_EMM_PWR_USIM_CODEC_C,
    PS_FILE_ID_NAS_EMM_PWR_UTIL_C,
    PS_FILE_ID_NAS_EMM_PWR_WRITE_NV_C,
    PS_FILE_ID_NAS_EMM_PWR_CTX_C,

    /* emm/feature */
    PS_FILE_ID_NAS_EMM_FEATURE_ECALL_C,
    PS_FILE_ID_NAS_EMM_FEATURE_MBB_CUSTOMIZED_C,
    PS_FILE_ID_NAS_EMM_FEATURE_UNPROTECT_REJECT_C,
    PS_FILE_ID_NAS_EMM_FEATURE_ADAPT_CAUSE_C,
    PS_FILE_ID_NAS_EMM_FEATURE_COMPATIBILITY_ESCAPE_C,
    PS_FILE_ID_NAS_EMM_FEATURE_CSG_C,
    PS_FILE_ID_NAS_EMM_FEATURE_DFS_C,
    PS_FILE_ID_NAS_EMM_FEATURE_DSDS_C,
    PS_FILE_ID_NAS_EMM_FEATURE_FAKE_ENODEB_C,
    PS_FILE_ID_NAS_EMM_FEATURE_GRADUAL_FORBIDDEN_C,
    PS_FILE_ID_NAS_EMM_FEATURE_TEMP_FORBIDDEN_C,
    PS_FILE_ID_NAS_EMM_FEATURE_THROT_C,

    PS_FILE_ID_NASBACKOFFALGMAIN_C,

    PS_FILE_ID_NASCOMMDIRCHRPROC_C,
    PS_FILE_ID_NASCOMMLOGFILTER_C,
    PS_FILE_ID_NASCOMM_NRCORE_LOGFILTER_C,
    PS_FILE_ID_NASCOMM_NRCORE_LOGFILTER_REGFUNC_C,

    PS_FILE_ID_PSNVIMINTERFACE_C,
    PS_FILE_ID_NAS_ITT_STUB_COMM_C,
    PS_FILE_ID_NAS_ITT_SOCKET_C,
    PS_FILE_ID_NASMMPUBMTEST_C,
    PS_FILE_ID_NASSTUB_C,
    PS_FILE_ID_NASLCSLPPMSGPROCTEST_CPP,
    PS_FILE_ID_NASLCSDECODETEST_CPP,
    PS_FILE_ID_NASLCSEMMMSGPROCTEST_CPP,
    PS_FILE_ID_NASLCSMMMSGPROCTEST_CPP,
    PS_FILE_ID_NASLCSENCODETEST_CPP,
    PS_FILE_ID_NAS_LPP_SUPL_PUBLIC_C,
    PS_FILE_ID_NAS_LPP_SUPL_MSG_PROC_C,
    PS_FILE_ID_NAS_LCS_DECODE_RETURN_RSLT_MSG_C,

    LNAS_FILE_ID_BUTT
}LNAS_FILE_ID_DEFINE_ENUM;

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */


#endif


