/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2020. All rights reserved.
 * foss@huawei.com
 *
 * If distributed as part of the Linux kernel, the following license terms
 * apply:
 *
 * * This program is free software; you can redistribute it and/or modify
 * * it under the terms of the GNU General Public License version 2 and
 * * only version 2 as published by the Free Software Foundation.
 * *
 * * This program is distributed in the hope that it will be useful,
 * * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * * GNU General Public License for more details.
 * *
 * * You should have received a copy of the GNU General Public License
 * * along with this program; if not, write to the Free Software
 * * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA
 *
 * Otherwise, the following license terms apply:
 *
 * * Redistribution and use in source and binary forms, with or without
 * * modification, are permitted provided that the following conditions
 * * are met:
 * * 1) Redistributions of source code must retain the above copyright
 * *    notice, this list of conditions and the following disclaimer.
 * * 2) Redistributions in binary form must reproduce the above copyright
 * *    notice, this list of conditions and the following disclaimer in the
 * *    documentation and/or other materials provided with the distribution.
 * * 3) Neither the name of Huawei nor the names of its contributors may
 * *    be used to endorse or promote products derived from this software
 * *    without specific prior written permission.
 *
 * * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef PS_LOG_CPROC_FILE_ID_DEFINE_H
#define PS_LOG_CPROC_FILE_ID_DEFINE_H

#include "ps_log_file_id_base.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

/* CPROC */
typedef enum
{
    
    /* FWK */
    PS_FILE_ID_FWK_DLLIST_C = CPROC_TEAM_FILE_ID,
    PS_FILE_ID_FWK_ESS_C,
    PS_FILE_ID_FWK_ESS_MALLOC_C,
    PS_FILE_ID_FWK_FSM_C,
    PS_FILE_ID_UFSM_C,
    PS_FILE_ID_UFSM_LOGING_C,
    PS_FILE_ID_IFF_DUMPER_C,
    /* 1X */
    PS_FILE_ID_CDMA_SYSTEM_TIME_C,
    PS_FILE_ID_CPORC_1X_LOG_C,
    PS_FILE_ID_CPROC_1X_UTIL_ESS_DRIVER_C,
    PS_FILE_ID_CPROC_ENTRY_C,
    PS_FILE_ID_CPROC_UTIL_BOOT_C,
    PS_FILE_ID_CPROC_1X_CM_C,
    PS_FILE_ID_CPROC_1X_CM_AFC_PPM_C,
    PS_FILE_ID_CPROC_1X_CM_COMMON_CH_CONFIG_C,
    PS_FILE_ID_CPROC_1X_CM_IDLE_NON_SLOTTED_MODE_C,
    PS_FILE_ID_CPROC_1X_CM_COMMON_CH_CONFIG_PARAMS_C,
    PS_FILE_ID_CPROC_1X_CM_COMMON_CH_CONFIG_SDRC_C,
    PS_FILE_ID_CPROC_1X_CM_ENTRY_C,
    PS_FILE_ID_CPROC_1X_CM_FCH_DCCH_C,
    PS_FILE_ID_CPROC_1X_CM_FTCH_SUPERVISION_C,
    PS_FILE_ID_CPROC_1X_CM_PC_C,
    PS_FILE_ID_CPROC_1X_CM_PILOT_SEARCH_C,
    PS_FILE_ID_CPROC_1X_CM_POWER_UP_C,
    PS_FILE_ID_CPROC_1X_CM_SET_TIMING_C,
    PS_FILE_ID_CPROC_1X_CM_SET_WORK_MODE_C,
    PS_FILE_ID_CPROC_1X_CM_SIGNAL_LEVEL_SCAN_C,
    PS_FILE_ID_CPROC_1X_CM_TRAFFIC_CH_CONFIG_C,
    PS_FILE_ID_CPROC_1X_SM_MEAS_HANDLING_C,
    PS_FILE_ID_CPROC_1X_SM_MPS_HANDLING_C,
    PS_FILE_ID_CPROC_1X_PDB_C,
    PS_FILE_ID_CPROC_1X_PDB_MEAS_C,
    PS_FILE_ID_CPROC_1X_PDB_MEASCFG_C,
    PS_FILE_ID_CPROC_1X_DRX_RFA_C,
    PS_FILE_ID_CPROC_1X_DRX_AGPS_C,
    PS_FILE_ID_CPROC_1X_DRX_RFA_RELEASE_ALL_C,
    PS_FILE_ID_CPROC_1X_SM_C,
    PS_FILE_ID_CPROC_1X_DRX_SM_C,
    PS_FILE_ID_CPROC_1X_SM_IPS_C,
    PS_FILE_ID_CPROC_1X_DSP_ENTRY_C,
    PS_FILE_ID_CPROC_1X_SM_ENTRY_C,
    PS_FILE_ID_CPROC_1X_CM_IDLE_SLOTTED_MODE_C,
    PS_FILE_ID_CPROC_1X_CM_RELEASE_ALL_C,
    PS_FILE_ID_CPROC_1X_DRX_CM_C,
    PS_FILE_ID_CPROC_1X_DRX_CM_QPCH_C,
    PS_FILE_ID_CPROC_1X_RFA_C,
    PS_FILE_ID_CPROC_1X_SM_RELEASE_ALL_C,
    PS_FILE_ID_CPROC_1x_UTIL_NV_C,
    PS_FILE_ID_CPROC_1X_GUC_PHY_NV_C,
    PS_FILE_ID_CPROC_1X_DM_C,
    PS_FILE_ID_CPROC_1X_DM_RULE_OF_ACCESS_C,
    PS_FILE_ID_CPROC_1X_DM_RULE_OF_FER_C,
    PS_FILE_ID_CPROC_1X_DM_RULE_OF_IDLE_CRC_C,
    PS_FILE_ID_CPROC_1X_DM_RULE_OF_IDLE_MEAS_C,
    PS_FILE_ID_CPROC_1X_DRX_RFA_RF_RESET_C,
    PS_FILE_ID_CPROC_1X_ERIC_MANAGE_C,
    PS_FILE_ID_CPROC_1X_ET_DELAY_C,
    /* RM */
    PS_FILE_ID_CPROC_RM_ASSIGNMENT_C,
    PS_FILE_ID_CPROC_RM_COMM_FUNC_C,
    PS_FILE_ID_CPROC_RM_COMM_MSG_C,
    PS_FILE_ID_CPROC_RM_PRIO_C,
    PS_FILE_ID_CPROC_RM_RAT_TOP_C,
    PS_FILE_ID_CPROC_RM_C,
    PS_FILE_ID_CPROC_RM_ENTRY_C,
    PS_FILE_ID_CPROC_RM_TIME_UTIL_C,
    PS_FILE_ID_CPROC_RM_WAIT_PAGING_C,
    /* HRPD */
    PS_FILE_ID_CPROC_HRPD_ENTRY_C,
    PS_FILE_ID_CPROC_HRPD_UTIL_NV_C,
    PS_FILE_ID_CPROC_HRPD_ESS_DRIVER_C,
    PS_FILE_ID_CPROC_HRPD_CM_C,
    PS_FILE_ID_CPROC_HRPD_CM_AC_CH_C,
    PS_FILE_ID_CPROC_HRPD_CM_CC_CH_C,
    PS_FILE_ID_CPROC_HRPD_CM_DCXO_C,
    PS_FILE_ID_CPROC_HRPD_CM_DRX_C,
    PS_FILE_ID_CPROC_HRPD_CM_DRX_IRAT_C,
    PS_FILE_ID_CPROC_HRPD_CM_LTE_IRAT_C,
    PS_FILE_ID_CPROC_HRPD_CM_PAGING_C,
    PS_FILE_ID_CPROC_HRPD_CM_SLS_C,
    PS_FILE_ID_CPROC_HRPD_CM_SUSPEND_C,
    PS_FILE_ID_CPROC_HRPD_CM_TCH_C,
    PS_FILE_ID_CPROC_HRPD_CM_TCH_HO_C,
    PS_FILE_ID_CPROC_HRPD_CM_CC_C,
    PS_FILE_ID_CPROC_HRPD_CM_SLAVE_C,
    PS_FILE_ID_CPROC_HRPD_CM_AC_C,
    PS_FILE_ID_CPROC_HRPD_CM_PILOT_SEARCH_C,
    PS_FILE_ID_CPROC_HRPD_CM_POWER_ON_C,
    PS_FILE_ID_CPROC_HRPD_CM_RESET_C,
    PS_FILE_ID_CPROC_HRPD_CM_SET_MODE_C,
    PS_FILE_ID_CPROC_HRPD_CM_ENTRY_C,
    PS_FILE_ID_CPROC_HRPD_CM_TCH_COMMON_C,
    PS_FILE_ID_CPROC_HRPD_SM_MEASUREMENT_C,
    PS_FILE_ID_CPROC_HRPD_SM_PILOTDATABASE_C,
    PS_FILE_ID_CPROC_HRPD_SM_MEASMODE_C,
    PS_FILE_ID_CPROC_HRPD_SM_SLAVEMEASUREMENT_C,
    PS_FILE_ID_CPROC_HRPD_SM_ENTRY_C,
    PS_FILE_ID_CPROC_HRPD_SM_MPS_C,
    PS_FILE_ID_CPROC_HRPD_SM_PS_C,
    PS_FILE_ID_CPROC_HRPD_SM_RESET_C,
    PS_FILE_ID_CPROC_HRPD_SM_SLS_C,
    PS_FILE_ID_CPROC_HRPD_CM_LPHY_WAKEUP_C,
    PS_FILE_ID_CPROC_HRPD_CM_ET_DELAY_C,
    PS_FILE_ID_CPROC_1X_CCBT_C,
    PS_FILE_ID_CPROC_1X_CM_SCH_C,


    /* TAS */
    PS_FILE_ID_CPROC_TAS_PROXY_C,
    PS_FILE_ID_CPROC_TAS_C,
    PS_FILE_ID_CPROC_TAS_ACCESS_ON_C,
    PS_FILE_ID_CPROC_TAS_TCH_ON_C,
    PS_FILE_ID_CPROC_TAS_SLS_C,

    PS_FILE_ID_CPROC_1X_NONPROTOCOL_C,
    PS_FILE_ID_CPROC_HRPD_CM_NONPROTOCOL_C,

    PS_FILE_ID_CPROC_1X_CM_CH_SUPERVISION_C,
    PS_FILE_ID_CPROC_1X_CM_CH_TCH_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_CSDR_CMD_MUX_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_DEFAULT_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_ESTABLISH_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_EVENT_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_HANDOFF_REVERT_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_HANDOFF_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_RECONFIG_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_RELEASE_SEQ_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_SUSPEND_CTRL_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_LONG_CODE_TOP_C,
    PS_FILE_ID_CPROC_1X_CM_TCH_LONG_CODE_SUB_C,
    PS_FILE_ID_CPROC_1X_CM_STATISTICS_C,
    PS_FILE_ID_CPROC_1X_ERR_LOG_C,
    PS_FILE_ID_CPROC_HRPD_ERR_LOG_C,
    PS_FILE_ID_CPROC_1X_LOG_C,
    PS_FILE_ID_CPROC_STATISTICS_C,
    PS_FILE_ID_CPROC_1X_STATISTICS_C,
    PS_FILE_ID_CPROC_HRPD_STATISTICS_C,

    PS_FILE_ID_CPROC_UTIL_FUNC_C,
    PS_FILE_ID_CPROC_MNTN_C,
    PS_FILE_ID_CPROC_1X_MNTN_C,
    PS_FILE_ID_CPROC_HRPD_MNTN_C,
    PS_FILE_ID_CPROC_RM_MNTN_C,
    PS_FILE_ID_CPROC_1X_CCB_C,
    PS_FILE_ID_CPROC_HRPD_CCB_C,
    PS_FILE_ID_CDMA_TIMING_DRV_C,
    PS_FILE_ID_CPROC_BUTT
    /* CDMA CPROC FILE ID END */
}CPROC_FILE_ID_DEFINE_ENUM;
typedef unsigned long  CPROC_FILE_ID_DEFINE_ENUM_UINT32;

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */


#endif


