EXTRA_CFLAGS += -Idrivers/hisi/slimbus/
EXTRA_CFLAGS += -Idrivers/devkit/audiokit/
EXTRA_CFLAGS += -Idrivers/hisi/da_combine_dsp/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Idrivers/hisi/da_combine_dsp/config/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/adapter/

snd-soc-da-combine-v3-objs :=da_combine_v3.o
snd-soc-kcontrol-objs :=kcontrol.o
snd-soc-resource-widget-objs :=resource_widget.o
snd-soc-path-widget-objs :=path_widget.o
snd-soc-switch-widget-objs :=switch_widget.o
snd-soc-route-objs :=route.o
snd-soc-headset-config-objs :=headset_config.o

obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-da-combine-v3.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-kcontrol.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-resource-widget.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-path-widget.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-switch-widget.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-route.o
obj-$(CONFIG_SND_SOC_DA_COMBINE_V3) += snd-soc-headset-config.o
