#
# Makefile for the memory technology device drivers.
#
# Core functionality.
-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/balong_product_config.mk


obj-y				+= ppm_port_switch.o
obj-y				+= ppm_common.o 
obj-y				+= ppm_socket.o 
obj-y				+= ppm_usb.o 
obj-y				+= ppm_vcom.o 



