
ccflags-y += -I$(srctree)/drivers/contexthub/
ccflags-y += -I$(srctree)/drivers/contexthub/inputhub_as/
ccflags-y += -I$(srctree)/drivers/contexthub/inputhub_as/fingerprint/

ccflags-y += -I$(srctree)/include/linux/hisi/contexthub/
ccflags-y += -I$(srctree)/include/linux/hisi/contexthub/inputhub_as/


obj-$(CONFIG_FINGERPRINT_CHANNEL) += fingerprint_channel.o
obj-$(CONFIG_FINGERPRINT_CHANNEL) += common_func.o
