// ****************************************************************************** 
// Copyright     :  Copyright (C) 2020, Hisilicon Technologies Co. Ltd.
// File name     :  mpi_u2_pl_reg_addr_define.h
// Project line  :  Platform And Key Technologies Development
// Department    :  CAD Development Department
// Author        :  xxx
// Version       :  1.0
// Date          :  2018/9/28
// Description   :  The description of xxx project
// Others        :  Generated automatically by nManager V5.1 
// History       :  xxx 2020/09/15 10:14:52 Create file
// ******************************************************************************

#ifndef __MPI_U2_PL_REG_ADDR_DEFINE_H__
#define __MPI_U2_PL_REG_ADDR_DEFINE_H__

/////////////////////////////////////////////
////    global parameters, begin         ////
/////////////////////////////////////////////
#define    MPI_U2_PL_REG_BASE_ADDR                    0x20000

////             offset address for MPI_U2_PL_REG registers
#define MPI_U2_PL_REG_MPI_RDY_NUM_OFFSET 0x0
#define MPI_U2_PL_REG_RDY_LAST_NUM_MASK 0xFF0000
#define MPI_U2_PL_REG_RDY_LAST_NUM_SHIFT 16
#define MPI_U2_PL_REG_RDY_LAST_NUM_LEN 8
#define MPI_U2_PL_REG_RDY_LAST_NUM_RESETVAL 0x00
#define MPI_U2_PL_REG_RDY_DELAY_NUM_MASK 0xFF
#define MPI_U2_PL_REG_RDY_DELAY_NUM_SHIFT 0
#define MPI_U2_PL_REG_RDY_DELAY_NUM_LEN 8
#define MPI_U2_PL_REG_RDY_DELAY_NUM_RESETVAL 0x04

#define MPI_U2_PL_REG_HS_EOF_TIME_OFFSET 0x4
#define MPI_U2_PL_REG_HS_EOF1_UFRAME_TIMES_MASK 0x1FFF0000
#define MPI_U2_PL_REG_HS_EOF1_UFRAME_TIMES_SHIFT 16
#define MPI_U2_PL_REG_HS_EOF1_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_HS_EOF1_UFRAME_TIMES_RESETVAL 0x1C5A
#define MPI_U2_PL_REG_HS_EOF2_UFRAME_TIMES_MASK 0x1FFF
#define MPI_U2_PL_REG_HS_EOF2_UFRAME_TIMES_SHIFT 0
#define MPI_U2_PL_REG_HS_EOF2_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_HS_EOF2_UFRAME_TIMES_RESETVAL 0x1D44

#define MPI_U2_PL_REG_FS_EOF_TIME_OFFSET 0x8
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_NUM_MASK 0xE0000000
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_NUM_SHIFT 29
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_NUM_RESETVAL 0x7
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_TIMES_MASK 0x1FFF0000
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_TIMES_SHIFT 16
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_FS_EOF1_UFRAME_TIMES_RESETVAL 0x1B80
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_NUM_MASK 0xE000
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_NUM_SHIFT 13
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_NUM_RESETVAL 0x7
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_TIMES_MASK 0x1FFF
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_TIMES_SHIFT 0
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_FS_EOF2_UFRAME_TIMES_RESETVAL 0x1D1A

#define MPI_U2_PL_REG_LS_EOF_TIME_OFFSET 0xC
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_NUM_MASK 0xE0000000
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_NUM_SHIFT 29
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_NUM_RESETVAL 0x7
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_TIMES_MASK 0x1FFF0000
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_TIMES_SHIFT 16
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_LS_EOF1_UFRAME_TIMES_RESETVAL 0x0EEC
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_NUM_MASK 0xE000
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_NUM_SHIFT 13
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_NUM_RESETVAL 0x7
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_TIMES_MASK 0x1FFF
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_TIMES_SHIFT 0
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_TIMES_LEN 13
#define MPI_U2_PL_REG_LS_EOF2_UFRAME_TIMES_RESETVAL 0x1BBC

#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_OFFSET 0x14
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_2X_MASK 0x1FFF0000
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_2X_SHIFT 16
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_2X_LEN 13
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_2X_RESETVAL 0x1950
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_MASK 0x1FFF
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_SHIFT 0
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_LEN 13
#define MPI_U2_PL_REG_HS_LPM_PRC_TIME_RESETVAL 0x1B4E

#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_OFFSET 0x18
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_2X_MASK 0xE0000000
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_2X_SHIFT 29
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_2X_LEN 3
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_2X_RESETVAL 0x7
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_2X_MASK 0x1FFF0000
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_2X_SHIFT 16
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_2X_LEN 13
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_2X_RESETVAL 0x0CE4
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_MASK 0xE000
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_SHIFT 13
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_FS_LPM_PRC_UFRAME_NUM_RESETVAL 0x7
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_MASK 0x1FFF
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_SHIFT 0
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_LEN 13
#define MPI_U2_PL_REG_FS_LPM_PRC_TIME_RESETVAL 0x1518

#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_OFFSET 0x1C
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_2X_MASK 0xE0000000
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_2X_SHIFT 29
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_2X_LEN 3
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_2X_RESETVAL 0x2
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_2X_MASK 0x1FFF0000
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_2X_SHIFT 16
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_2X_LEN 13
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_2X_RESETVAL 0x0000
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_MASK 0xE000
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_SHIFT 13
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_LEN 3
#define MPI_U2_PL_REG_LS_LPM_PRC_UFRAME_NUM_RESETVAL 0x5
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_MASK 0x1FFF
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_SHIFT 0
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_LEN 13
#define MPI_U2_PL_REG_LS_LPM_PRC_TIME_RESETVAL 0x0000

#define MPI_U2_PL_REG_T_L1_TOKEN_RETRY_OFFSET 0x20
#define MPI_U2_PL_REG_T_L1_TOKEN_RETRY_MASK 0xFFF
#define MPI_U2_PL_REG_T_L1_TOKEN_RETRY_SHIFT 0
#define MPI_U2_PL_REG_T_L1_TOKEN_RETRY_LEN 12
#define MPI_U2_PL_REG_T_L1_TOKEN_RETRY_RESETVAL 0x140

#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_HS_OFFSET 0x24
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_HS_MASK 0xFFF
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_HS_SHIFT 0
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_HS_LEN 12
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_HS_RESETVAL 0x010

#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_FS_OFFSET 0x28
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_FS_MASK 0xFFF
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_FS_SHIFT 0
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_FS_LEN 12
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_FS_RESETVAL 0x015

#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_LS_OFFSET 0x2C
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_LS_MASK 0xFFF
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_LS_SHIFT 0
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_LS_LEN 12
#define MPI_U2_PL_REG_T_TIMEOUT_RX2RX_LS_RESETVAL 0x0AD

#define MPI_U2_PL_REG_T_LPM_START_DELAY_OFFSET 0x30
#define MPI_U2_PL_REG_LS_LPM_START_DELAY_MASK 0xFFE00000
#define MPI_U2_PL_REG_LS_LPM_START_DELAY_SHIFT 21
#define MPI_U2_PL_REG_LS_LPM_START_DELAY_LEN 11
#define MPI_U2_PL_REG_LS_LPM_START_DELAY_RESETVAL 0x610
#define MPI_U2_PL_REG_FS_LPM_START_DELAY_MASK 0x1FFC00
#define MPI_U2_PL_REG_FS_LPM_START_DELAY_SHIFT 10
#define MPI_U2_PL_REG_FS_LPM_START_DELAY_LEN 11
#define MPI_U2_PL_REG_FS_LPM_START_DELAY_RESETVAL 0x258
#define MPI_U2_PL_REG_HS_LPM_START_DELAY_MASK 0x3FF
#define MPI_U2_PL_REG_HS_LPM_START_DELAY_SHIFT 0
#define MPI_U2_PL_REG_HS_LPM_START_DELAY_LEN 10
#define MPI_U2_PL_REG_HS_LPM_START_DELAY_RESETVAL 0x03C

#define MPI_U2_PL_REG_HOST_ISO_STOP_CFG_OFFSET 0x34
#define MPI_U2_PL_REG_CSR_ISO_UNDERSIZE_STOP_ENABLE_MASK 0x1
#define MPI_U2_PL_REG_CSR_ISO_UNDERSIZE_STOP_ENABLE_SHIFT 0
#define MPI_U2_PL_REG_CSR_ISO_UNDERSIZE_STOP_ENABLE_LEN 1
#define MPI_U2_PL_REG_CSR_ISO_UNDERSIZE_STOP_ENABLE_RESETVAL 0x1

#define MPI_U2_PL_REG_PROTOCAL_OVERHEAD_TIME_HS_OFFSET 0x38
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_SPLIT_MASK 0xFFF000
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_SPLIT_SHIFT 12
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_SPLIT_LEN 12
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_SPLIT_RESETVAL 0x04B
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_NONSPLIT_MASK 0xFFF
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_NONSPLIT_SHIFT 0
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_NONSPLIT_LEN 12
#define MPI_U2_PL_REG_CSR_OVERHEAD_HS_NONSPLIT_RESETVAL 0x037

#define MPI_U2_PL_REG_PROTOCAL_OVERHEAD_TIME_FS_OFFSET 0x3C
#define MPI_U2_PL_REG_CSR_OVERHEAD_FS_MASK 0xFFFF
#define MPI_U2_PL_REG_CSR_OVERHEAD_FS_SHIFT 0
#define MPI_U2_PL_REG_CSR_OVERHEAD_FS_LEN 16
#define MPI_U2_PL_REG_CSR_OVERHEAD_FS_RESETVAL 0x0208

#define MPI_U2_PL_REG_PROTOCAL_OVERHEAD_TIME_LS_OFFSET 0x40
#define MPI_U2_PL_REG_CSR_OVERHEAD_LS_MASK 0xFFFF
#define MPI_U2_PL_REG_CSR_OVERHEAD_LS_SHIFT 0
#define MPI_U2_PL_REG_CSR_OVERHEAD_LS_LEN 16
#define MPI_U2_PL_REG_CSR_OVERHEAD_LS_RESETVAL 0x1900

#define MPI_U2_PL_REG_DEV_PROTOCAL_CFG_OFFSET 0x100
#define MPI_U2_PL_REG_HOST_SETUP_STALL_MODE_MASK 0x40
#define MPI_U2_PL_REG_HOST_SETUP_STALL_MODE_SHIFT 6
#define MPI_U2_PL_REG_HOST_SETUP_STALL_MODE_LEN 1
#define MPI_U2_PL_REG_HOST_SETUP_STALL_MODE_RESETVAL 0x0
#define MPI_U2_PL_REG_HOST_HS_STATUS_NYET_MODE_MASK 0x20
#define MPI_U2_PL_REG_HOST_HS_STATUS_NYET_MODE_SHIFT 5
#define MPI_U2_PL_REG_HOST_HS_STATUS_NYET_MODE_LEN 1
#define MPI_U2_PL_REG_HOST_HS_STATUS_NYET_MODE_RESETVAL 0x0
#define MPI_U2_PL_REG_HOST_HS_ISO_DATA1_MODE_MASK 0x10
#define MPI_U2_PL_REG_HOST_HS_ISO_DATA1_MODE_SHIFT 4
#define MPI_U2_PL_REG_HOST_HS_ISO_DATA1_MODE_LEN 1
#define MPI_U2_PL_REG_HOST_HS_ISO_DATA1_MODE_RESETVAL 0x0
#define MPI_U2_PL_REG_HOST_STATUS_DATA0_MODE_MASK 0x8
#define MPI_U2_PL_REG_HOST_STATUS_DATA0_MODE_SHIFT 3
#define MPI_U2_PL_REG_HOST_STATUS_DATA0_MODE_LEN 1
#define MPI_U2_PL_REG_HOST_STATUS_DATA0_MODE_RESETVAL 0x0
#define MPI_U2_PL_REG_DEV_FS_PING_ENABLE_MASK 0x4
#define MPI_U2_PL_REG_DEV_FS_PING_ENABLE_SHIFT 2
#define MPI_U2_PL_REG_DEV_FS_PING_ENABLE_LEN 1
#define MPI_U2_PL_REG_DEV_FS_PING_ENABLE_RESETVAL 0x0
#define MPI_U2_PL_REG_DEV_TIMEOUT_RX2RX_ENABLE_MASK 0x2
#define MPI_U2_PL_REG_DEV_TIMEOUT_RX2RX_ENABLE_SHIFT 1
#define MPI_U2_PL_REG_DEV_TIMEOUT_RX2RX_ENABLE_LEN 1
#define MPI_U2_PL_REG_DEV_TIMEOUT_RX2RX_ENABLE_RESETVAL 0x0
#define MPI_U2_PL_REG_DEV_TIMEOUT_TX2RX_ENABLE_MASK 0x1
#define MPI_U2_PL_REG_DEV_TIMEOUT_TX2RX_ENABLE_SHIFT 0
#define MPI_U2_PL_REG_DEV_TIMEOUT_TX2RX_ENABLE_LEN 1
#define MPI_U2_PL_REG_DEV_TIMEOUT_TX2RX_ENABLE_RESETVAL 0x1

#define MPI_U2_PL_REG_DEV_SE0_NAK_CFG_OFFSET 0x104
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_EPT_MASK 0x2
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_EPT_SHIFT 1
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_EPT_LEN 1
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_EPT_RESETVAL 0x0
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_ADDR_MASK 0x1
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_ADDR_SHIFT 0
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_ADDR_LEN 1
#define MPI_U2_PL_REG_CSR_DEV_SE0_NAK_IGNORE_ADDR_RESETVAL 0x0

#define MPI_U2_PL_REG_DFX_EN_OFFSET 0x700
#define MPI_U2_PL_REG_DFX_RUNNING_MASK 0x2
#define MPI_U2_PL_REG_DFX_RUNNING_SHIFT 1
#define MPI_U2_PL_REG_DFX_RUNNING_LEN 1
#define MPI_U2_PL_REG_DFX_RUNNING_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_EN_MASK 0x1
#define MPI_U2_PL_REG_DFX_EN_SHIFT 0
#define MPI_U2_PL_REG_DFX_EN_LEN 1
#define MPI_U2_PL_REG_DFX_EN_RESETVAL 0x0

#define MPI_U2_PL_REG_DFX_EN_TIMER_OFFSET 0x704
#define MPI_U2_PL_REG_DFX_EN_TIMER_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_EN_TIMER_SHIFT 0
#define MPI_U2_PL_REG_DFX_EN_TIMER_LEN 32
#define MPI_U2_PL_REG_DFX_EN_TIMER_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_REC_BYTE_NUM_OFFSET 0x708
#define MPI_U2_PL_REG_DFX_REC_BYTE_NUM_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_BYTE_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_BYTE_NUM_LEN 48
#define MPI_U2_PL_REG_DFX_REC_BYTE_NUM_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_SEND_BYTE_NUM_OFFSET 0x710
#define MPI_U2_PL_REG_DFX_SEND_BYTE_NUM_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_SEND_BYTE_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_SEND_BYTE_NUM_LEN 48
#define MPI_U2_PL_REG_DFX_SEND_BYTE_NUM_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_REC_PKT_NUM_MASK_OFFSET 0x718
#define MPI_U2_PL_REG_DFX_REC_PKT_NUM_MASK_MASK 0xFFFF
#define MPI_U2_PL_REG_DFX_REC_PKT_NUM_MASK_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_PKT_NUM_MASK_LEN 16
#define MPI_U2_PL_REG_DFX_REC_PKT_NUM_MASK_RESETVAL 0xFFFF

#define MPI_U2_PL_REG_DFX_REC_GOOD_PKT_NUM_OFFSET 0x71C
#define MPI_U2_PL_REG_DFX_REC_GOOD_PKT_NUM_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_GOOD_PKT_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_GOOD_PKT_NUM_LEN 32
#define MPI_U2_PL_REG_DFX_REC_GOOD_PKT_NUM_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_REC_BAD_PKT_NUM_OFFSET 0x720
#define MPI_U2_PL_REG_DFX_REC_BAD_PKT_NUM_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_BAD_PKT_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_BAD_PKT_NUM_LEN 32
#define MPI_U2_PL_REG_DFX_REC_BAD_PKT_NUM_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK_OFFSET 0x724
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK_MASK 0xFFFF
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK_SHIFT 0
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK_LEN 16
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK_RESETVAL 0xFFFF

#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_OFFSET 0x728
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_LEN 32
#define MPI_U2_PL_REG_DFX_SEND_PKT_NUM_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_STATEMACHINE_OFFSET 0x72C
#define MPI_U2_PL_REG_DFX_STATEMACHINE_MASK 0xF
#define MPI_U2_PL_REG_DFX_STATEMACHINE_SHIFT 0
#define MPI_U2_PL_REG_DFX_STATEMACHINE_LEN 4
#define MPI_U2_PL_REG_DFX_STATEMACHINE_RESETVAL 0x0

#define MPI_U2_PL_REG_DFX_OUT_TOGGLE_OFFSET 0x730
#define MPI_U2_PL_REG_DFX_OUT_TOGGLE_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_OUT_TOGGLE_SHIFT 0
#define MPI_U2_PL_REG_DFX_OUT_TOGGLE_LEN 32
#define MPI_U2_PL_REG_DFX_OUT_TOGGLE_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_IN_TOGGLE_OFFSET 0x734
#define MPI_U2_PL_REG_DFX_IN_TOGGLE_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_IN_TOGGLE_SHIFT 0
#define MPI_U2_PL_REG_DFX_IN_TOGGLE_LEN 32
#define MPI_U2_PL_REG_DFX_IN_TOGGLE_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_OUT_EPT_TYPE_OFFSET 0x738
#define MPI_U2_PL_REG_DFX_OUT_EPT_TYPE_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_OUT_EPT_TYPE_SHIFT 0
#define MPI_U2_PL_REG_DFX_OUT_EPT_TYPE_LEN 32
#define MPI_U2_PL_REG_DFX_OUT_EPT_TYPE_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_IN_EPT_TYPE_OFFSET 0x73C
#define MPI_U2_PL_REG_DFX_IN_EPT_TYPE_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_IN_EPT_TYPE_SHIFT 0
#define MPI_U2_PL_REG_DFX_IN_EPT_TYPE_LEN 32
#define MPI_U2_PL_REG_DFX_IN_EPT_TYPE_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_EPT_EN_OFFSET 0x740
#define MPI_U2_PL_REG_DFX_EPT_EN_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_EPT_EN_SHIFT 0
#define MPI_U2_PL_REG_DFX_EPT_EN_LEN 32
#define MPI_U2_PL_REG_DFX_EPT_EN_RESETVAL 0x00000000

#define MPI_U2_PL_REG_DFX_ERROR_OFFSET 0x744
#define MPI_U2_PL_REG_DFX_ERR_MASK 0xFFFF
#define MPI_U2_PL_REG_DFX_ERR_SHIFT 0
#define MPI_U2_PL_REG_DFX_ERR_LEN 16
#define MPI_U2_PL_REG_DFX_ERR_RESETVAL 0x0000

#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_CFG_OFFSET 0x748
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_EN_MASK 0x1000
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_EN_SHIFT 12
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_EN_LEN 1
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_EN_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_ID_MASK 0xFFF
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_ID_SHIFT 0
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_ID_LEN 12
#define MPI_U2_PL_REG_DFX_CNT_REC_SEL_ID_RESETVAL 0x000

#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_CNT_OFFSET 0x74C
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_BYTE_CNT_OFFSET 0x754
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_BYTE_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_BYTE_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_BYTE_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_REC_DP_GOOD_BYTE_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_REC_DP_BAD_CNT_OFFSET 0x75C
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_REC_DP_BAD_BYTE_CNT_OFFSET 0x764
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_BYTE_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_BYTE_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_BYTE_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_REC_DP_BAD_BYTE_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_CFG_OFFSET 0x76C
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_EN_MASK 0x1000
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_EN_SHIFT 12
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_EN_LEN 1
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_EN_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_ID_MASK 0xFFF
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_ID_SHIFT 0
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_ID_LEN 12
#define MPI_U2_PL_REG_DFX_CNT_SEND_SEL_ID_RESETVAL 0x000

#define MPI_U2_PL_REG_DFX_SEND_DP_CNT_OFFSET 0x770
#define MPI_U2_PL_REG_DFX_SEND_DP_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_SEND_DP_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_SEND_DP_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_SEND_DP_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_SEND_DP_GOOD_BYTE_CNT_OFFSET 0x778
#define MPI_U2_PL_REG_DFX_SEND_DP_GOOD_BYTE_CNT_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_DFX_SEND_DP_GOOD_BYTE_CNT_SHIFT 0
#define MPI_U2_PL_REG_DFX_SEND_DP_GOOD_BYTE_CNT_LEN 48
#define MPI_U2_PL_REG_DFX_SEND_DP_GOOD_BYTE_CNT_RESETVAL 0x000000000000

#define MPI_U2_PL_REG_DFX_ERR_INJECT_EN_OFFSET 0x780
#define MPI_U2_PL_REG_DFX_ERR_INJECT_ONCE_MASK 0x2
#define MPI_U2_PL_REG_DFX_ERR_INJECT_ONCE_SHIFT 1
#define MPI_U2_PL_REG_DFX_ERR_INJECT_ONCE_LEN 1
#define MPI_U2_PL_REG_DFX_ERR_INJECT_ONCE_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_ERR_INJECT_EN_MASK 0x1
#define MPI_U2_PL_REG_DFX_ERR_INJECT_EN_SHIFT 0
#define MPI_U2_PL_REG_DFX_ERR_INJECT_EN_LEN 1
#define MPI_U2_PL_REG_DFX_ERR_INJECT_EN_RESETVAL 0x0

#define MPI_U2_PL_REG_DFX_ERR_INJECT_CFG_OFFSET 0x784
#define MPI_U2_PL_REG_DFX_ERR_INJECT_CFG_MASK 0x3F
#define MPI_U2_PL_REG_DFX_ERR_INJECT_CFG_SHIFT 0
#define MPI_U2_PL_REG_DFX_ERR_INJECT_CFG_LEN 6
#define MPI_U2_PL_REG_DFX_ERR_INJECT_CFG_RESETVAL 0x00

#define MPI_U2_PL_REG_DFX_ERR_INJECT_VALUE_OFFSET 0x788
#define MPI_U2_PL_REG_DFX_ERR_INJECT_VALUE_MASK 0x1FFFFFF
#define MPI_U2_PL_REG_DFX_ERR_INJECT_VALUE_SHIFT 0
#define MPI_U2_PL_REG_DFX_ERR_INJECT_VALUE_LEN 25
#define MPI_U2_PL_REG_DFX_ERR_INJECT_VALUE_RESETVAL 0x0000000

#define MPI_U2_PL_REG_DFX_SMP_CTRL_OFFSET 0x78C
#define MPI_U2_PL_REG_DFX_SMP_TRIG_STATE_MASK 0x200
#define MPI_U2_PL_REG_DFX_SMP_TRIG_STATE_SHIFT 9
#define MPI_U2_PL_REG_DFX_SMP_TRIG_STATE_LEN 1
#define MPI_U2_PL_REG_DFX_SMP_TRIG_STATE_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_EN_MASK 0x100
#define MPI_U2_PL_REG_DFX_SMP_TRIG_EN_SHIFT 8
#define MPI_U2_PL_REG_DFX_SMP_TRIG_EN_LEN 1
#define MPI_U2_PL_REG_DFX_SMP_TRIG_EN_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SEL_MASK 0xF0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SEL_SHIFT 4
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SEL_LEN 4
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SEL_RESETVAL 0x0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_PID_MASK 0xF
#define MPI_U2_PL_REG_DFX_SMP_TRIG_PID_SHIFT 0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_PID_LEN 4
#define MPI_U2_PL_REG_DFX_SMP_TRIG_PID_RESETVAL 0x0

#define MPI_U2_PL_REG_DFX_SMP_LEN_OFFSET 0x790
#define MPI_U2_PL_REG_DFX_SMP_TRIG_KEEP_LEN_MASK 0x3FF0000
#define MPI_U2_PL_REG_DFX_SMP_TRIG_KEEP_LEN_SHIFT 16
#define MPI_U2_PL_REG_DFX_SMP_TRIG_KEEP_LEN_LEN 10
#define MPI_U2_PL_REG_DFX_SMP_TRIG_KEEP_LEN_RESETVAL 0x1FF
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SKP_NUM_MASK 0xFFFF
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SKP_NUM_SHIFT 0
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SKP_NUM_LEN 16
#define MPI_U2_PL_REG_DFX_SMP_TRIG_SKP_NUM_RESETVAL 0x0001

#define MPI_U2_PL_REG_U2PL_RSVD_OFFSET 0x7FC
#define MPI_U2_PL_REG_U2PL_RSVD_MASK 0xFFFFFFFF
#define MPI_U2_PL_REG_U2PL_RSVD_SHIFT 0
#define MPI_U2_PL_REG_U2PL_RSVD_LEN 32
#define MPI_U2_PL_REG_U2PL_RSVD_RESETVAL 0x00000000


#endif // __MPI_U2_PL_REG_ADDR_DEFINE_H__
