obj-$(CONFIG_RPMB_AGENT) += agent_rpmb/
obj-$(CONFIG_TZDRIVER) += auth/
obj-$(CONFIG_TZDRIVER) += core/
obj-$(CONFIG_TZDRIVER) += ion/
obj-$(CONFIG_TZDRIVER) += tlogger/
obj-$(CONFIG_TZDRIVER) += tui/
