obj-$(CONFIG_PHY_HI6220_USB)		+= phy-hi6220-usb.o
obj-$(CONFIG_PHY_HIX5HD2_SATA)		+= phy-hix5hd2-sata.o
obj-$(CONFIG_PHY_HISI_USB2_ULPI)		+= hisi-usb2-phy-ulpi.o
obj-$(CONFIG_PHY_HISI_USB2_T5)		+= hisi-usb2-phy-t5.o
obj-$(CONFIG_PHY_HISI_COMBOPHY)		+= phy-hisi-combophy.o hisi-combophy-mcu.o
