# MD5: 2fb5af78957ae02c49c31e473bc1c91f
CFG_TLPHY_CSU_DATA_SAMPLE_ENABLED      := YES
CFG_TLPHY_OM_RPT_ENABLED               := YES
CFG_TL_RFD_READ_ENABLED               := YES
CFG_TLPHY_DESENSITIZATION_OFF          := YES
CFG_TLPHY_ASSERT_ENABLED               := YES
