obj-$(CONFIG_HUAWEI_SPEAKER_CHARGER) += series_batt_speaker_charge_adapter.o
obj-$(CONFIG_HUAWEI_SPEAKER_CHARGER) += series_batt_speaker_charger.o
obj-$(CONFIG_HUAWEI_SPEAKER_CHARGER) += series_batt_speaker_charger_check.o
