obj-$(CONFIG_CHIP_USB_REG_CFG)		+= hisi_usb_reg_cfg.o
obj-$(CONFIG_CHIP_USB_HELPER)		+= hisi_usb_helper.o
obj-$(CONFIG_CHIP_USB_MISC_CTRL)	+= hisi_usb_misc_ctrl.o
obj-$(CONFIG_CHIP_USB_DEBUG_MODULE) 	+= hisi_usb_debug_framework.o hisi_usb_debug_notify.o
