
-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/balong_product_config.mk

subdir-ccflags-y := -Wall -Werror
obj-y       += msg_alias.o
obj-y       += msg_base.o
obj-y       += msg_tskque.o
obj-y       += msg_event.o
obj-y       += msg_mem.o
obj-y       += msg_core.o
obj-y       += msg_lite.o
obj-y       += msg_cmsg.o
obj-y       += msg_fixed.o
obj-y       += msg_mntn.o
