/*
 * asp_codec_kcontrol.c -- asp codec kcontrol driver
 *
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 */

#include "asp_codec_kcontrol.h"

#include <sound/core.h>
#include "audio_log.h"
#include "asp_codec_utils.h"
#include "asp_codec_regs.h"

#ifdef CONFIG_AUDIO_DEBUG
#define LOG_TAG "asp_codec"
#else
#define LOG_TAG "Analog_less_v1"
#endif

#define S1_I2S_CFG_KCONTROLS \
	SOC_SINGLE("FS_S1_IF_I2S", \
		I2S1_CTRL_REG, FS_I2S1_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S1_LEN), 0), \
	SOC_SINGLE("S1_FUNC_MODE", \
		I2S1_CTRL_REG, I2S1_FUNC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S1_FUNC_MODE_LEN), 0), \
	SOC_SINGLE("S1_I2S_DIRECT_MODE", \
		I2S1_CTRL_REG, I2S1_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(I2S1_DIRECT_LOOP_LEN), 0), \
	SOC_SINGLE("S1_FRAME_MODE", \
		I2S1_CTRL_REG, I2S1_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S1_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("S1_RX_CLK_SEL", \
		I2S1_CTRL_REG, I2S1_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S1_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S1_TX_CLK_SEL", \
		I2S1_CTRL_REG, I2S1_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S1_TX_CLK_SEL_LEN), 0) \

#define S1_TDM_CFG_KCONTROLS \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_I0", \
		I2S1_TDM_CTRL0_REG, S1_TDM_RX_SLOT_SEL_I0_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_I0_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_V0", \
		I2S1_TDM_CTRL0_REG, S1_TDM_RX_SLOT_SEL_V0_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_V0_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_I1", \
		I2S1_TDM_CTRL0_REG, S1_TDM_RX_SLOT_SEL_I1_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_I1_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_V1", \
		I2S1_TDM_CTRL0_REG, S1_TDM_RX_SLOT_SEL_V1_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_V1_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_I2", \
		I2S1_TDM_CTRL1_REG, S1_TDM_RX_SLOT_SEL_I2_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_I2_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_V2", \
		I2S1_TDM_CTRL1_REG, S1_TDM_RX_SLOT_SEL_V2_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_V2_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_I3", \
		I2S1_TDM_CTRL1_REG, S1_TDM_RX_SLOT_SEL_I3_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_I3_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_SLOT_SEL_V3", \
		I2S1_TDM_CTRL1_REG, S1_TDM_RX_SLOT_SEL_V3_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_SLOT_SEL_V3_LEN), 0), \
	SOC_SINGLE("S1_TDM_RX_CLK_SEL", \
		I2S1_TDM_CTRL0_REG, S1_TDM_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S1_TDM_TX_CLK_SEL", \
		I2S1_TDM_CTRL0_REG, S1_TDM_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_TX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S1_TDM_DIRECT_MODE", \
		I2S1_TDM_CTRL0_REG, S1_TDM_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_DIRECT_LOOP_LEN), 0), \
	SOC_SINGLE("S1_TDM_FRAME_MODE", \
		I2S1_TDM_CTRL0_REG, S1_TDM_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(S1_TDM_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("FS_S1_TDM", \
		FS_CTRL7_REG, FS_S1_TDM_OFFSET, \
		MAX_VAL_ON_BIT(FS_S1_TDM_LEN), 0) \

#define S2_CFG_KCONTROLS \
	SOC_SINGLE("FS_S2_IF_I2S", \
		I2S2_PCM_CTRL_REG, FS_I2S2_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_LEN), 0), \
	SOC_SINGLE("S2_FUNC_MODE", \
		I2S2_PCM_CTRL_REG, I2S2_FUNC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_FUNC_MODE_LEN), 0), \
	SOC_SINGLE("S2_I2S_DIRECT_MODE", \
		I2S2_PCM_CTRL_REG, I2S2_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_DIRECT_LOOP_LEN), 0), \
	SOC_SINGLE("S2_FRAME_MODE", \
		I2S2_PCM_CTRL_REG, I2S2_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("S2_RX_CLK_SEL", \
		I2S2_PCM_CTRL_REG, I2S2_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S2_TX_CLK_SEL", \
		I2S2_PCM_CTRL_REG, I2S2_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S2_CODEC_IO_WORDLENGTH", \
		I2S2_PCM_CTRL_REG, I2S2_CODEC_IO_WORDLENGTH_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_CODEC_IO_WORDLENGTH_LEN), 0) \

#define S3_CFG_KCONTROLS \
	SOC_SINGLE("S3_I2S_RX_CLK_SEL", \
		I2S3_PCM_CTRL_REG, I2S3_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S3_I2S_TX_CLK_SEL", \
		I2S3_PCM_CTRL_REG, I2S3_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_TX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S3_I2S_FRAME_MODE", \
		I2S3_PCM_CTRL_REG, I2S3_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("S3_I2S_FUNC_MODE", \
		I2S3_PCM_CTRL_REG, I2S3_FUNC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_FUNC_MODE_LEN), 0), \
	SOC_SINGLE("S3_DIRECT_LOOP", \
		I2S3_PCM_CTRL_REG, I2S3_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_DIRECT_LOOP_LEN), 0), \
	SOC_SINGLE("S3_MST_SLV_SEL", \
		I2S3_PCM_CTRL_REG, I2S3_MST_SLV_OFFSET, \
		MAX_VAL_ON_BIT(I2S3_MST_SLV_LEN), 0) \

#define S4_I2S_CFG_KCONTROLS \
	SOC_SINGLE("S4_I2S_RX_CLK_SEL", \
		I2S4_CTRL_REG, I2S4_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S4_I2S_TX_CLK_SEL", \
		I2S4_CTRL_REG, I2S4_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_TX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S4_I2S_FRAME_MODE", \
		I2S4_CTRL_REG, I2S4_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("S4_I2S_FUNC_MODE", \
		I2S4_CTRL_REG, I2S4_FUNC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_FUNC_MODE_LEN), 0), \
	SOC_SINGLE("S4_I2S_DIRECT_LOOP", \
		I2S4_CTRL_REG, I2S4_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_DIRECT_LOOP_LEN), 0), \
	SOC_SINGLE("S4_MST_SLV_SEL", \
		I2S4_CTRL_REG, I2S4_MST_SLV_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_MST_SLV_LEN), 0), \
	SOC_SINGLE("FS_S4_IF_I2S", \
		I2S4_CTRL_REG, FS_I2S4_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S4_LEN), 0), \
	SOC_SINGLE("S4_CODEC_IO_WORDLENGTH", \
		I2S4_CTRL_REG, I2S4_CODEC_IO_WORDLENGTH_OFFSET, \
		MAX_VAL_ON_BIT(I2S4_CODEC_IO_WORDLENGTH_LEN), 0) \

#define S4_TDM_CFG_KCONTROLS \
	SOC_SINGLE("S4_TDM_RX_CLK_SEL", \
		I2S4_TDM_CTRL0_REG, S4_TDM_RX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(S4_TDM_RX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S4_TDM_TX_CLK_SEL", \
		I2S4_TDM_CTRL0_REG, S4_TDM_TX_CLK_SEL_OFFSET, \
		MAX_VAL_ON_BIT(S4_TDM_TX_CLK_SEL_LEN), 0), \
	SOC_SINGLE("S4_TDM_FRAME_MODE", \
		I2S4_TDM_CTRL0_REG, S4_TDM_FRAME_MODE_OFFSET, \
		MAX_VAL_ON_BIT(S4_TDM_FRAME_MODE_LEN), 0), \
	SOC_SINGLE("S4_TDM_DIRECT_LOOP", \
		I2S4_TDM_CTRL0_REG, S4_TDM_DIRECT_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(S4_TDM_DIRECT_LOOP_LEN), 0) \

#define SIF_KCONTROLS \
	SOC_SINGLE("SIF_DIRECT_LOOP", \
		SIF_CTRL_REG, SIF_S2P_LOOP_OFFSET, \
		MAX_VAL_ON_BIT(SIF_S2P_LOOP_LEN), 0) \

#define PGA_BYPASS_KCONTROLS \
	SOC_SINGLE("AUDIO_UP_L_PGA_BYPASS", \
		AUDIO_L_UP_PGA_CTRL_REG, AUDIO_L_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_L_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("AUDIO_UP_R_PGA_BYPASS", \
		AUDIO_R_UP_PGA_CTRL_REG, AUDIO_R_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_R_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("VOICE_UP_L_PGA_BYPASS", \
		VOICE_L_UP_PGA_CTRL_REG, VOICE_L_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(VOICE_L_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("VOICE_UP_R_PGA_BYPASS", \
		VOICE_R_UP_PGA_CTRL_REG, VOICE_R_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(VOICE_R_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("MIC3_UP_PGA_BYPASS", \
		MIC3_UP_PGA_CTRL_REG, MIC3_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(MIC3_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("MIC4_UP_PGA_BYPASS", \
		MIC4_UP_PGA_CTRL_REG, MIC4_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(MIC4_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("MDM5G_UP_L_PGA_BYPASS", \
		MDM_5G_L_UP_PGA_CTRL_REG, MDM_5G_L_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(MDM_5G_L_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("MDM5G_UP_R_PGA_BYPASS", \
		MDM_5G_R_UP_PGA_CTRL_REG, MDM_5G_R_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(MDM_5G_R_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("CODEC3_DN_L_PGA_BYPASS", \
		CODEC3_L_DN_PGA_CTRL_REG, CODEC3_L_DN_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(CODEC3_L_DN_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("CODEC3_DN_R_PGA_BYPASS", \
		CODEC3_R_DN_PGA_CTRL_REG, CODEC3_R_DN_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(CODEC3_R_DN_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("ADC1_UP_PGA_BYPASS", \
		ADC1_UP_PGA_CTRL_REG, ADC1_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(ADC1_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("ADC2_UP_PGA_BYPASS", \
		ADC2_UP_PGA_CTRL_REG, ADC2_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(ADC2_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("ADC3_UP_PGA_BYPASS", \
		ADC3_UP_PGA_CTRL_REG, ADC3_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(ADC3_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("ADC4_UP_PGA_BYPASS", \
		ADC4_UP_PGA_CTRL_REG, ADC4_UP_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(ADC4_UP_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("AUDIO_DN_L_PGA_BYPASS", \
		AUDIO_L_DN_PGA_CTRL_REG, AUDIO_L_DN_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_L_DN_PGA_BYPASS_LEN), 0), \
	SOC_SINGLE("AUDIO_DN_R_PGA_BYPASS", \
		AUDIO_R_DN_PGA_CTRL_REG, AUDIO_R_DN_PGA_BYPASS_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_R_DN_PGA_BYPASS_LEN), 0) \

#define PGA_KCONTROLS \
	SOC_SINGLE("FS_AUDIO_DN_L_PGA", \
		FS_CTRL2_REG, FS_AUDIO_L_DN_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_AUDIO_L_DN_PGA_LEN), 0), \
	SOC_SINGLE("FS_AUDIO_DN_R_PGA", \
		FS_CTRL2_REG, FS_AUDIO_R_DN_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_AUDIO_R_DN_PGA_LEN), 0), \
	SOC_SINGLE("FS_CODEC3_DN_L_PGA", \
		FS_CTRL2_REG, FS_CODEC3_L_DN_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_CODEC3_L_DN_PGA_LEN), 0), \
	SOC_SINGLE("FS_CODEC3_DN_R_PGA", \
		FS_CTRL2_REG, FS_CODEC3_R_DN_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_CODEC3_R_DN_PGA_LEN), 0), \
	SOC_SINGLE("FS_I2S2_RX_L_PGA", \
		FS_CTRL3_REG, FS_I2S2_RX_L_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_L_PGA_LEN), 0), \
	SOC_SINGLE("FS_I2S2_RX_R_PGA", \
		FS_CTRL3_REG, FS_I2S2_RX_R_PGA_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_R_PGA_LEN), 0) \

#define MIXER_PGA_GIN_KCONTROLS \
	SOC_SINGLE("AUDIO_DN_L_PGA_GAIN", \
		AUDIO_L_DN_PGA_CTRL_REG, AUDIO_L_DN_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_L_DN_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("AUDIO_DN_R_PGA_GAIN", \
		AUDIO_R_DN_PGA_CTRL_REG, AUDIO_R_DN_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_R_DN_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("CODEC3_DN_L_PGA_GAIN", \
		CODEC3_L_DN_PGA_CTRL_REG, CODEC3_L_DN_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(CODEC3_L_DN_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("CODEC3_DN_R_PGA_GAIN", \
		CODEC3_R_DN_PGA_CTRL_REG, CODEC3_R_DN_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(CODEC3_R_DN_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_PGA_GAIN", \
		PGA_GAINOFFSET_CTRL3_REG, I2S2_RX_L_PGA_GAINOFFSET_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_L_PGA_GAINOFFSET_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_PGA_GAIN", \
		PGA_GAINOFFSET_CTRL3_REG, I2S2_RX_R_PGA_GAINOFFSET_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_R_PGA_GAINOFFSET_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_S1_GAIN", \
		DACL_MIXER4_CTRL0_REG, DACL_MIXER4_GAIN1_OFFSET, \
		MAX_VAL_ON_BIT(DACL_MIXER4_GAIN1_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_S2_GAIN", \
		DACL_MIXER4_CTRL0_REG, DACL_MIXER4_GAIN2_OFFSET, \
		MAX_VAL_ON_BIT(DACL_MIXER4_GAIN2_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_S3_GAIN", \
		DACL_MIXER4_CTRL0_REG, DACL_MIXER4_GAIN3_OFFSET, \
		MAX_VAL_ON_BIT(DACL_MIXER4_GAIN3_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_S4_GAIN", \
		DACL_MIXER4_CTRL0_REG, DACL_MIXER4_GAIN4_OFFSET, \
		MAX_VAL_ON_BIT(DACL_MIXER4_GAIN4_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_S1_GAIN", \
		DACR_MIXER4_CTRL0_REG, DACR_MIXER4_GAIN1_OFFSET, \
		MAX_VAL_ON_BIT(DACR_MIXER4_GAIN1_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_S2_GAIN", \
		DACR_MIXER4_CTRL0_REG, DACR_MIXER4_GAIN2_OFFSET, \
		MAX_VAL_ON_BIT(DACR_MIXER4_GAIN2_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_S3_GAIN", \
		DACR_MIXER4_CTRL0_REG, DACR_MIXER4_GAIN3_OFFSET, \
		MAX_VAL_ON_BIT(DACR_MIXER4_GAIN3_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_S4_GAIN", \
		DACR_MIXER4_CTRL0_REG, DACR_MIXER4_GAIN4_OFFSET, \
		MAX_VAL_ON_BIT(DACR_MIXER4_GAIN4_LEN), 0), \
	SOC_SINGLE("DACL_S_MIXER2_S1_GAIN", \
		DACL_S_MIXER2_CTRL_REG, DACL_S_MIXER2_GAIN1_OFFSET, \
		MAX_VAL_ON_BIT(DACL_S_MIXER2_GAIN1_LEN), 0), \
	SOC_SINGLE("DACL_S_MIXER2_S2_GAIN", \
		DACL_S_MIXER2_CTRL_REG, DACL_S_MIXER2_GAIN2_OFFSET, \
		MAX_VAL_ON_BIT(DACL_S_MIXER2_GAIN2_LEN), 0), \
	SOC_SINGLE("DACR_S_MIXER2_S1_GAIN", \
		DACR_S_MIXER2_CTRL_REG, DACR_S_MIXER2_GAIN1_OFFSET, \
		MAX_VAL_ON_BIT(DACR_S_MIXER2_GAIN1_LEN), 0), \
	SOC_SINGLE("DACR_S_MIXER2_S2_GAIN", \
		DACR_S_MIXER2_CTRL_REG, DACR_S_MIXER2_GAIN2_OFFSET, \
		MAX_VAL_ON_BIT(DACR_S_MIXER2_GAIN2_LEN), 0), \
	SOC_SINGLE("I2S2_TX_MIXER2_S1_GAIN", \
		I2S2_TX_MIXER2_CTRL_REG, I2S2_TX_MIXER2_GAIN1_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_MIXER2_GAIN1_LEN), 0), \
	SOC_SINGLE("I2S2_TX_MIXER2_S2_GAIN", \
		I2S2_TX_MIXER2_CTRL_REG, I2S2_TX_MIXER2_GAIN2_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_MIXER2_GAIN2_LEN), 0), \
	SOC_SINGLE("AUDIO_UP_L_PGA_GAIN", \
		AUDIO_L_UP_PGA_CTRL_REG, AUDIO_L_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_L_UP_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("AUDIO_UP_R_PGA_GAIN", \
		AUDIO_R_UP_PGA_CTRL_REG, AUDIO_R_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_R_UP_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("VOICE_UP_L_PGA_GAIN", \
		VOICE_L_UP_PGA_CTRL_REG, VOICE_L_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(VOICE_L_UP_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("VOICE_UP_R_PGA_GAIN", \
		VOICE_R_UP_PGA_CTRL_REG, VOICE_R_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(VOICE_R_UP_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("MIC3_PGA_GAIN", \
		MIC3_UP_PGA_CTRL_REG, MIC3_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(MIC3_UP_PGA_GAIN_LEN), 0), \
	SOC_SINGLE("MIC4_PGA_GAIN", \
		MIC4_UP_PGA_CTRL_REG, MIC4_UP_PGA_GAIN_OFFSET, \
		MAX_VAL_ON_BIT(MIC4_UP_PGA_GAIN_LEN), 0) \

#define SRC_KCONTROLS \
	SOC_SINGLE("DACL_MIXER4_SRCUP_CLKEN", \
		CODEC_CLK_EN1_REG, DACL_MIXER4_SRCUP_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(DACL_MIXER4_SRCUP_CLKEN_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_SRCUP_CLKEN", \
		CODEC_CLK_EN1_REG, DACR_MIXER4_SRCUP_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(DACR_MIXER4_SRCUP_CLKEN_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_SRCUP_DIN", \
		FS_CTRL4_REG, FS_DACL_MIXER4_SRCUP_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACL_MIXER4_SRCUP_DIN_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_SRCUP_DOUT", \
		FS_CTRL4_REG, FS_DACL_MIXER4_SRCUP_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACL_MIXER4_SRCUP_DOUT_LEN), 0), \
	SOC_SINGLE("DACL_MIXER4_SRCUP_MODE", \
		SRCUP_CTRL_REG, DACL_SRCUP_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(DACL_SRCUP_SRC_MODE_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_SRCUP_DIN", \
		FS_CTRL4_REG, FS_DACR_MIXER4_SRCUP_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACR_MIXER4_SRCUP_DIN_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_SRCUP_DOUT", \
		FS_CTRL4_REG, FS_DACR_MIXER4_SRCUP_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACR_MIXER4_SRCUP_DOUT_LEN), 0), \
	SOC_SINGLE("DACR_MIXER4_SRCUP_MODE", \
		SRCUP_CTRL_REG, DACR_SRCUP_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(DACR_SRCUP_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_TX_L_SRCDN_CLKEN", \
		CODEC_CLK_EN2_REG, I2S2_TX_L_SRCDN_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_L_SRCDN_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_TX_L_SRCDN_DIN", \
		FS_CTRL6_REG, FS_I2S2_TX_L_SRCDN_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_TX_L_SRCDN_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_TX_L_SRCDN_DOUT", \
		FS_CTRL6_REG, FS_I2S2_TX_L_SRCDN_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_TX_L_SRCDN_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_TX_L_SRCDN_MODE", \
		SRCDN_CTRL1_REG, I2S2_TX_L_SRCDN_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_L_SRCDN_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_TX_R_SRCDN_CLKEN", \
		CODEC_CLK_EN2_REG, I2S2_TX_R_SRCDN_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_R_SRCDN_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_TX_R_SRCDN_DIN", \
		FS_CTRL6_REG, FS_I2S2_TX_R_SRCDN_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_TX_R_SRCDN_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_TX_R_SRCDN_DOUT", \
		FS_CTRL6_REG, FS_I2S2_TX_R_SRCDN_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_TX_R_SRCDN_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_TX_R_SRCDN_MODE", \
		SRCDN_CTRL1_REG, I2S2_TX_R_SRCDN_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_TX_R_SRCDN_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCUP_CLKEN", \
		CODEC_CLK_EN1_REG, I2S2_RX_L_SRCUP_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_L_SRCUP_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCUP_DIN", \
		FS_CTRL3_REG, FS_I2S2_RX_L_SRCUP_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_L_SRCUP_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCUP_DOUT", \
		FS_CTRL3_REG, FS_I2S2_RX_L_SRCUP_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_L_SRCUP_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCUP_MODE", \
		SRCUP_CTRL_REG, I2S2_RX_L_SRCUP_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_L_SRCUP_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCUP_CLKEN", \
		CODEC_CLK_EN1_REG, I2S2_RX_R_SRCUP_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_R_SRCUP_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCUP_DIN", \
		FS_CTRL4_REG, FS_I2S2_RX_R_SRCUP_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_R_SRCUP_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCUP_DOUT", \
		FS_CTRL4_REG, FS_I2S2_RX_R_SRCUP_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_R_SRCUP_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCUP_MODE", \
		SRCUP_CTRL_REG, I2S2_RX_R_SRCUP_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_R_SRCUP_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCDN_CLKEN", \
		CODEC_CLK_EN1_REG, I2S2_RX_L_SRCDN_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_L_SRCDN_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCDN_DIN", \
		FS_CTRL5_REG, FS_I2S2_RX_L_SRCDN_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_L_SRCDN_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCDN_DOUT", \
		FS_CTRL5_REG, FS_I2S2_RX_L_SRCDN_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_L_SRCDN_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_RX_L_SRCDN_MODE", \
		SRCDN_CTRL1_REG, I2S2_RX_L_SRCDN_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_L_SRCDN_SRC_MODE_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCDN_CLKEN", \
		CODEC_CLK_EN1_REG, I2S2_RX_R_SRCDN_CLKEN_OFFSET, \
		MAX_VAL_ON_BIT(I2S2_RX_R_SRCDN_CLKEN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCDN_DIN", \
		FS_CTRL6_REG, FS_I2S2_RX_R_SRCDN_DIN_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_R_SRCDN_DIN_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCDN_DOUT", \
		FS_CTRL6_REG, FS_I2S2_RX_R_SRCDN_DOUT_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_RX_R_SRCDN_DOUT_LEN), 0), \
	SOC_SINGLE("I2S2_RX_R_SRCDN_MODE", \
		SRCDN_CTRL1_REG, AUDIO_R_UP_SRCDN_SRC_MODE_OFFSET, \
		MAX_VAL_ON_BIT(AUDIO_R_UP_SRCDN_SRC_MODE_LEN), 0) \

#define MIXER_FS_KCONTROLS \
	SOC_SINGLE("FS_DACL_S_MIXER2", \
		FS_CTRL6_REG, FS_DACLS_MIXER2_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACLS_MIXER2_LEN), 0), \
	SOC_SINGLE("FS_DACR_S_MIXER2", \
		FS_CTRL6_REG, FS_DACRS_MIXER2_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACRS_MIXER2_LEN), 0), \
	SOC_SINGLE("FS_DACL_MIXER4", \
		FS_CTRL6_REG, FS_DACL_MIXER4_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACL_MIXER4_LEN), 0), \
	SOC_SINGLE("FS_DACR_MIXER4", \
		FS_CTRL6_REG, FS_DACR_MIXER4_OFFSET, \
		MAX_VAL_ON_BIT(FS_DACR_MIXER4_LEN), 0), \
	SOC_SINGLE("FS_I2S2_TX_MIXER2", \
		FS_CTRL7_REG, FS_I2S2_TX_MIXER2_OFFSET, \
		MAX_VAL_ON_BIT(FS_I2S2_TX_MIXER2_LEN), 0) \

static const struct snd_kcontrol_new snd_controls[] = {
	S1_I2S_CFG_KCONTROLS,
	S1_TDM_CFG_KCONTROLS,
	S2_CFG_KCONTROLS,
	S3_CFG_KCONTROLS,
	S4_I2S_CFG_KCONTROLS,
	S4_TDM_CFG_KCONTROLS,
	SIF_KCONTROLS,
	PGA_BYPASS_KCONTROLS,
	PGA_KCONTROLS,
	MIXER_PGA_GIN_KCONTROLS,
	SRC_KCONTROLS,
	MIXER_FS_KCONTROLS,
};

int asp_codec_add_kcontrols(struct snd_soc_component *codec)
{
	if (codec == NULL) {
		AUDIO_LOGE("input is null");
		return -EINVAL;
	}

	return snd_soc_add_component_controls(codec, snd_controls,
		ARRAY_SIZE(snd_controls));
}

