obj-$(CONFIG_HUAWEI_VIBRATOR) += aw86907/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw8697/
obj-$(CONFIG_DRV2605) += drv2605/
obj-$(CONFIG_CLASSD_VIBRATOR) += classd_vibrator/
obj-$(CONFIG_HISI_EXT_VIBRATOR) += ext_vibrator/
