obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_ic_intf.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_fod.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_chrg_curve.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_protection.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_alarm.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_volt_check.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_acc.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx_auth.o
