subdir-ccflags-$(CONFIG_HISI_BB)        += -Idrivers/hisi/mntn/blackbox/platform_lpm3

obj-$(CONFIG_SR)    += pm.o
obj-$(CONFIG_SR_DEBUG) 				+= lpregs.o
obj-$(CONFIG_PM_LPCTRL)				+= pm_lpctrl.o
obj-$(CONFIG_SR_SYNC)					+= suspend.o


