obj-$(CONFIG_LP_ENABLE_GET_VAL) += cpufreq_get_volt.o
obj-$(CONFIG_HISI_CPUFREQ_DT)	+= lpcpu_cpufreq_dt.o
obj-$(CONFIG_LPCPU_FREQ_LINK)	+= lpcpu_cpuddr_freq_link.o
obj-$(CONFIG_LPCPU_CPUFREQ_LOWTEMP)	+= lpcpu_cpufreq_lowtemp.o
obj-$(CONFIG_HISI_FREQ_STATS_COUNTING_IDLE) += time_in_state.o
