obj-$(CONFIG_HISI_CLK)                  += clk.o
obj-$(CONFIG_HISI_CLK)                  += plat-clk-gate.o
obj-$(CONFIG_HISI_CLK)                  += clk-ppll.o
obj-$(CONFIG_HISI_CLK)                  += plat-clk-div.o
obj-$(CONFIG_HISI_CLK)                  += clk-xfreq.o
obj-$(CONFIG_HISI_CLK)                  += clk-pmu.o
obj-$(CONFIG_HISI_CLK)                  += clk-fast-dvfs.o

obj-$(CONFIG_HISI_CLK)                  += platform/
obj-$(CONFIG_HISI_CLK_DEBUG)            += debug/
obj-$(CONFIG_HISI_CLK_MAILBOX_SUPPORT)  += clk-mailbox.o
obj-$(CONFIG_HISI_MCLK_SUPPORT)         += clk-mclk.o

obj-$(CONFIG_HISI_CLK)                  += clk-dvfs.o
obj-$(CONFIG_HISI_CLK_PM_MONITOR)       += clk-pm-monitor.o
obj-$(CONFIG_HISI_PLL_UNLOCK_DETECT)    += clk-intr.o
obj-$(CONFIG_HISI_PERIDVFS)             += dvfs/
obj-$(CONFIG_HISI_CKM_MODULE)           += clk-monitor.o
obj-$(CONFIG_HISI_CLK_SMC_SUPPORT)      += clk-smc.o
