cflags-$(CONFIG_HYPERHOLD) += -I$(srctree)/mm
obj-$(CONFIG_HISI_SLOW_PATH_COUNT) += slowpath_count.o
obj-$(CONFIG_HISI_PAGE_TRACE) += mem_trace.o buddy_track.o
obj-$(CONFIG_HISI_MEM_OFFLINE) += mem_offline.o
obj-$(CONFIG_HYPERHOLD) += memcg_control.o
obj-$(CONFIG_HYPERHOLD) += memcg_reclaim.o
obj-$(CONFIG_VM_COPY) += vm_copy.o
