EXTRA_CFLAGS += -Idrivers/hisi/da_separate/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/da_separate/
EXTRA_CFLAGS += -Isound/soc/codecs/hisi/adapter/

snd-soc-da_separate_v3-objs :=da_separate_v3.o
obj-$(CONFIG_SND_SOC_CODEC_DA_SEPARATE_V3) += snd-soc-da_separate_v3.o


