
obj-$(CONFIG_THERMAL_TSENSOR)	+= tsens.o
obj-$(CONFIG_THERMAL_PERIPHERAL)	+= peripheral_tm.o ntc_tm_table.o
obj-$(CONFIG_IPA_THERMAL)	+= ipa_thermal.o
obj-$(CONFIG_IPA_THERMAL)	+= board_cooling.o
obj-$(CONFIG_THERMAL_SHELL) += shell_temp.o
obj-$(CONFIG_THERMAL_AMBIENT) += ambient_temp.o
obj-$(CONFIG_HKADC_MODEM) += modem_hkadc_temp.o
obj-$(CONFIG_ITS) += its.o
obj-$(CONFIG_THERMAL_NPU) += npu_thermal.o
obj-$(CONFIG_PERF_CTRL) += thermal_perf_ctrl.o
obj-y += hw_dpm/
