#
# Copyright (c) Huawei Technologies Co., Ltd. 2014-2021. All rights reserved.
# Description: This file describe GPU hardware related features
# Create: 2014-2-24
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#
ifeq ($(CONFIG_DEVFREQ_THERMAL),y)
include $(src)/$(MALI_PLATFORM_DIR)/gpu_ipa/Kbuild
endif

ifeq ($(CONFIG_GPU_GMC_GENERIC), y)
include $(src)/$(MALI_PLATFORM_DIR)/gmc/Kbuild
endif

ifeq ($(CONFIG_GPU_DPM_PCR), y)
include $(src)/$(MALI_PLATFORM_DIR)/dpm/Kbuild
endif

mali_kbase-y += \
        $(MALI_PLATFORM_DIR)/mali_kbase_config_platform.o \
        $(MALI_PLATFORM_DIR)/mali_kbase_gpu_callback.o \
        $(MALI_PLATFORM_DIR)/mali_kbase_gpu_dev_frequency.o

mali_kbase-$(CONFIG_GPU_AI_FENCE_INFO) += \
        $(MALI_PLATFORM_DIR)/mali_kbase_gpu_ai_freq.o

mali_kbase-$(CONFIG_GPU_CORE_HOTPLUG) += \
        $(MALI_PLATFORM_DIR)/mali_kbase_gpu_core_hotplug.o

mali_kbase-$(CONFIG_GPU_VIRTUAL_DEVFREQ) += \
        $(MALI_PLATFORM_DIR)/mali_kbase_gpu_virtual_devfreq.o

# Compile the hisilicon base drivers.
include $(src)/$(MALI_PLATFORM_DIR)/base/Kbuild
