#
# RPMB Makefile
#

obj-$(CONFIG_VENDOR_RPMB)			+= vendor_rpmb.o
obj-$(CONFIG_RPMB_MMC)		+= rpmb_mmc.o
obj-$(CONFIG_RPMB_UFS)		+= rpmb_ufs.o

obj-$(CONFIG_RPMB_STORAGE_INTERFACE)		+= rpmb_fs.o

obj-$(CONFIG_RPMB_DEBUG_FS)		+= rpmb_debugfs.o
