#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r2p0-03rel0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r4p0-01rel0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r6p0-cet/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r7p0-00cet0/
obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r18p0-01rel0/

#obj-$(CONFIG_MALI_SIGURD) += bifrost-r7p0-00cet0/
obj-$(CONFIG_MALI_SIGURD) += bifrost-r18p0-01rel0/

#obj-$(CONFIG_MALI_NORR) += bifrost-r6p0-cet/
#obj-$(CONFIG_MALI_NORR) += bifrost-r7p0-00cet0/
obj-$(CONFIG_MALI_NORR) += bifrost-r18p0-01rel0/

obj-$(CONFIG_MALI_NORR_PHX) += bifrost-r18p0-01rel0/

obj-$(CONFIG_MALI_GONDUL) += bifrost-r18p0-01rel0/




obj-$(CONFIG_MALI_ODIN) += valhall-r27p0-01eac0/

obj-$(CONFIG_MALI_ODIN_LEX) += valhall-r27p0-01eac0/

obj-$(CONFIG_MALI_ODIN_LEX_BASE) += valhall-r27p0-01eac0-base/
