#ifndef __DDR_ASIC_3690_DEFINE_H__
#define __DDR_ASIC_3690_DEFINE_H__ 
#define MAX_RANK_NUM_PER_DMC (2)
#define MAX_DDR_DENSITY (11)
#define DDR_DENSITY_12GBIT (5)
#define DDR_TYPE_LPDDR3 (0)
#define DDR_TYPE_LPDDR4 (1)
#define DDR_TYPE_UNKNOW (2)
#define DDR_HPM_SENSOR_NUM (5)
#define DDR_HPM_PARA_NUM ((DDR_HPM_SENSOR_NUM) + 1)
#define DDR_AVS_TEMP_RECOUP_0 (0)
#define DDR_AVS_TEMP_RECOUP_1 (1)
#define DDR_AVS_TEMP_RECOUP_2 (2)
#define DDR_AVS_TEMP_RECOUP_3 (3)
#define DDR_AVS_TEMP_RECOUP_NUM (4)
#define DDR_AVS_TZONE_0 (0)
#define DDR_AVS_TZONE_1 (20)
#define DDR_AVS_TZONE_2 (40)
#define DDR_AVS_TZONE_3 (60)
#define DDR_AVS_CHIP_TYPE_NOT_SAVE 0x0
#define DDR_AVS_CHIP_TYPE_SAVE 0x1
#if (defined HIBENCH_XLOADER || defined __SLT_FEATURE__)
#define DDR_AVS_SLT_VOLT_NOT_INIT 0x0
#define DDR_AVS_SLT_VOLT_INIT 0x1
#endif
#define DDR_SECTION_RDQSCYC_NUM (11)
#define DDR_SECTION_BASE_NUM (1)
#define DDR_SECTION_MAX_NUM (DDR_SECTION_RDQSCYC_NUM + DDR_SECTION_BASE_NUM)
#define DDR_SECTION_VOLT_STEP (25)
#define DDR_SECTION_VOLT_ROUND_UP(vol) ((((unsigned int)(vol) + (unsigned int)DDR_SECTION_VOLT_STEP - (unsigned int)1) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_VOLT_ROUND_DOWN(vol) (((unsigned int)(vol) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_VOLT_ROUND(vol) ((((unsigned int)(vol) + ((unsigned int)DDR_SECTION_VOLT_STEP >> 1)) / (unsigned int)DDR_SECTION_VOLT_STEP) * (unsigned int)DDR_SECTION_VOLT_STEP)
#define DDR_SECTION_RDQSCYC_RATIO_SHIFT (0x8)
#define PLL_INIT_ID (1)
#define TRAINING_TYPE_DLYMEAS_ID (2)
#define TRAINING_TYPE_ZCAl_ID (3)
#define TRAINING_TYPE_WL_ID (4)
#define TRAINING_TYPE_GT_ID (5)
#define TRAINING_TYPE_GDST_ID (6)
#define TRAINING_TYPE_WL2_ID (7)
#define TRAINING_TYPE_RDET_ID (8)
#define TRAINING_TYPE_WDET_ID (9)
#define TRAINING_TYPE_DRAMINIT_ID (10)
#define TRAINING_TYPE_CAT_ID (11)
#define TRAINING_TYPE_DRAMRST_ID (12)
#define TRAINING_TYPE_DVREFT_ID (16)
#define TRAINING_TYPE_HVREFT_ID (17)
#define TRAINING_TYPE_DXDVREFS_ID (18)
#define TRAINING_TYPE_ACDVREFT_ID (19)
#define TRAINING_TYPE_ACHVREFT_ID (20)
#define TRAINING_TYPE_ACDVREFS_ID (21)
#define TRAINING_TYPE_CST_ID (22)
#define TRAINING_TYPE_RESERVED_ID (23)
#define TRAINING_TYPE_MAX_ID (TRAINING_TYPE_RESERVED_ID + 1)
#define PLL_INIT (1 << PLL_INIT_ID)
#define TRAINING_TYPE_DLYMEAS (1 << TRAINING_TYPE_DLYMEAS_ID)
#define TRAINING_TYPE_ZCAl (1 << TRAINING_TYPE_ZCAl_ID)
#define TRAINING_TYPE_WL (1 << TRAINING_TYPE_WL_ID)
#define TRAINING_TYPE_GT (1 << TRAINING_TYPE_GT_ID)
#define TRAINING_TYPE_GDST (1 << TRAINING_TYPE_GDST_ID)
#define TRAINING_TYPE_WL2 (1 << TRAINING_TYPE_WL2_ID)
#define TRAINING_TYPE_RDET (1 << TRAINING_TYPE_RDET_ID)
#define TRAINING_TYPE_WDET (1 << TRAINING_TYPE_WDET_ID)
#define TRAINING_TYPE_DRAMINIT (1 << TRAINING_TYPE_DRAMINIT_ID)
#define TRAINING_TYPE_CAT (1 << TRAINING_TYPE_CAT_ID)
#define TRAINING_TYPE_DRAMRST (1 << TRAINING_TYPE_DRAMRST_ID)
#define TRAINING_TYPE_DVREFT (1 << TRAINING_TYPE_DVREFT_ID)
#define TRAINING_TYPE_HVREFT (1 << TRAINING_TYPE_HVREFT_ID)
#define TRAINING_TYPE_DXDVREFS (1 << TRAINING_TYPE_DXDVREFS_ID)
#define TRAINING_TYPE_ACDVREFT (1 << TRAINING_TYPE_ACDVREFT_ID)
#define TRAINING_TYPE_ACHVREFT (1 << TRAINING_TYPE_ACHVREFT_ID)
#define TRAINING_TYPE_ACDVREFS (1 << TRAINING_TYPE_ACDVREFS_ID)
#define TRAINING_TYPE_CST (1 << TRAINING_TYPE_CST_ID)
#define TMOD_REFRESH_RATE_0 (0)
#define TMOD_REFRESH_RATE_1 (1)
#define TMOD_REFRESH_RATE_2 (2)
#define TMOD_REFRESH_RATE_3 (3)
#define TMOD_REFRESH_RATE_4 (4)
#define TMOD_REFRESH_RATE_5 (5)
#define TMOD_REFRESH_RATE_6 (6)
#define TMOD_REFRESH_RATE_MAX (7)
#define XTREFI_1P4 (((TMOD_REFRESH_RATE_5) << 3) | (TMOD_REFRESH_RATE_5))
#define TRANS_TO_LPM3_PROFILE_NUM(x) (((x) > 1U) ? ((x) - 1U) : (x))
#define TRANS_TO_LPM3_FREQ_IDX(x) (((x) > 0U) ? ((x) - 1U) : 0U)
#define TRANS_TO_LPM3_PROFILE_START_IDX(x,profile_num) (((profile_num) > 1U) ? ((x) + 1U) : (x))
#define FREQ_NUM_MAX (8U)
#define LPMCU_FREQ_NUM_MAX TRANS_TO_LPM3_PROFILE_NUM(FREQ_NUM_MAX)
#define FREQ_RANGE_EXT (4U)
#define DDR_TRAIN_PARAM_NUM_MAX (LPMCU_FREQ_NUM_MAX + FREQ_RANGE_EXT)
#define DDR_VREF_NUM_MAX (DDR_TRAIN_PARAM_NUM_MAX + 1)
#define DDR_FREQ_2133 (2133)
#define DDR_FREQ_2132 (2132)
#define DDR_FREQ_1866 (1866)
#define DDR_FREQ_1660 (1660)
#define DDR_FREQ_1600 (1600)
#define DDR_FREQ_1370 (1370)
#define DDR_FREQ_1333 (1333)
#define DDR_FREQ_1245 (1245)
#define DDR_FREQ_1244 (1244)
#define DDR_FREQ_1066 (1066)
#define DDR_FREQ_830 (830)
#define DDR_FREQ_800 (800)
#define DDR_FREQ_673 (673)
#define DDR_FREQ_667 (667)
#define DDR_FREQ_600 (600)
#define DDR_FREQ_533 (533)
#define DDR_FREQ_415 (415)
#define DDR_FREQ_400 (400)
#define DDR_FREQ_266 (266)
#define DDR_FREQ_133 (133)
#define DDR_FREQ_55 (55)
#define DDR_FREQ_MAX DDR_FREQ_2133
#define DDR_DTS_SELF_ADAPT_MAX_FREQ (DDR_FREQ_1866)
#define LOAD_LPM3_CONFIG_TARGET (0x5)
#define LOAD_LPM3_CONFIG_DMSS_FREQ (0x6)
#define DMSS_FREQ_830 (830)
#define DDR_MODE_SDR (0)
#define DDR_MODE_HDR (1)
#define DDR_PHYPLL_BYPASS (0)
#define DDR_PHYPLL_MISSION (1)
#define DDR_SDR (0)
#define DDR_HDR (1)
#define DDR_QDR (2)
#define IO_WIDTH_X16 (0)
#define IO_WIDTH_X8 (1)
#define IO_WIDTH_X32 (2)
#define ONE_BYTE_PER_DIE (1)
#define TWO_BYTE_PER_DIE (2)
#define ONE_DIE_PER_RANK (1)
#define TWO_DIE_PER_RANK (2)
#define DDR_MEM_COL_REG_START_BIT (8)
#define DDR_MEM_ROW_REG_START_BIT (11)
#define RANK_ID_0 0
#define RANK_ID_1 1
#define RANK_MAX_NR (2)
#define BYTELANE_LPDDR4_MAX_NR (2)
#define EDGETYPE_MAX_NR (2)
#define BYTELANE_MAX_NUM (BYTELANE_LPDDR4_MAX_NR)
#define RANK_MAX_NUM (RANK_MAX_NR)
#ifdef DDR_SINGLE_CHANNEL
#define CHANNEL_LPDDR4_MAX_NR (1)
#define DMSS_CHANS_MAX_NUM (1)
#define PACK_MAX_NUM (1)
#define PHY_MAX_NUM (1)
#define DMC_MAX_NUM (1)
#define ZCAL_START_PACK (0)
#define ZCAL_EN_MASK (1 << ZCAL_START_PACK)
#define LPDDR4_DMC_INIT_MASK (0x1)
#define LPDDR4_PACK_INIT_MASK (0x1)
#define LPDDR4_PHY_INIT_MASK (0x1)
#elif defined(DDR_TWO_CHANNEL)
#define CHANNEL_LPDDR4_MAX_NR (2)
#define DMSS_CHANS_MAX_NUM (2)
#define PACK_MAX_NUM (2)
#define PHY_MAX_NUM (2)
#define DMC_MAX_NUM (2)
#define ZCAL_START_PACK (1)
#define ZCAL_EN_MASK (1 << ZCAL_START_PACK)
#define LPDDR4_DMC_INIT_MASK (0x3)
#define LPDDR4_PACK_INIT_MASK (0x3)
#define LPDDR4_PHY_INIT_MASK (0x3)
#elif defined(DDR_FOUR_CHANNEL)
#define CHANNEL_LPDDR4_MAX_NR (4)
#define DMSS_CHANS_MAX_NUM (4)
#define PACK_MAX_NUM (4)
#define PHY_MAX_NUM (4)
#define DMC_MAX_NUM (4)
#define ZCAL_START_PACK (3)
#define ZCAL_EN_MASK (1 << ZCAL_START_PACK)
#define LPDDR4_DMC_INIT_MASK (0xF)
#define LPDDR4_PACK_INIT_MASK (0xF)
#define LPDDR4_PHY_INIT_MASK (0xF)
#endif
#define UCE_NUM_MAX (CHANNEL_LPDDR4_MAX_NR)
#define UCE_MBX_ID_0 0
#define UCE_MBX_ID_1 1
#define IPC_LPM3_PROCESS_ID 0x0
#define IPC_UCE_PROCESS_ID 0x1
#define LPDDR4_PHY_BYTELANE_NUM (2)
#define LPDDR4_PACK_BYTELANE_NUM (2)
#define CHANNEL_ID_A 0
#define CHANNEL_ID_B 1
#define CHANNEL_ID_C 2
#define CHANNEL_ID_D 3
#define CHANNEL_MAX_NUM CHANNEL_LPDDR4_MAX_NR
#define DDR_PACK_NUM PACK_MAX_NUM
#define DDR_DMC_MASK LPDDR4_DMC_INIT_MASK
#define DDR_PACK_MASK LPDDR4_PACK_INIT_MASK
#define DDR_PHY_MASK LPDDR4_PHY_INIT_MASK
#define LPDDR_WDQNBDL_MAX (127)
#define LPDDR_RDQNBDL_MAX (127)
#define DDR_INIT_TYPE_ONCE (0)
#define DDR_INIT_TYPE_STEP (1)
#define DDR_INIT_TYPE_STEP_EC (2)
#define DDR_INIT_TYPE_STEP_JUMP (3)
#define DDR_TARGET_PRARA_STATIC (0)
#define DDR_TARGET_PRARA_MODIFY (1)
#define DDR_CBT_X16_MODE (0x0)
#define DDR_CBT_X8_MODE (0x1)
#define TRAINING_TYPE_HW (1)
#define TRAINING_TYPE_SW (2)
#define TRAINING_TYPE_EYET (1)
#define TRAINING_TYPE_VREFT (2)
#define TRAINING_TYPE_NODCCT (0)
#define TRAINING_TYPE_IODCCT (1)
#define TRAINING_TYPE_PHYDCCT (2)
#define TYPE_CAT (1)
#define TYPE_CST (2)
#define LEFTBOUND (1)
#define ADDRBDL (1 << 1)
#define RDQNBDL (1 << 2)
#define DXNWDQBDL (1 << 3)
#define XSREF (0x10C)
#define ZQCAL (0x13D2A)
#define ZQLATCH (0x1454A)
#define AREF (0x1001E3)
#define DMC_RINT_CLEAR_VALUE 0xFFFFFFFF
#define REG_EN_FOR_RANK(rank_num) ((0x1U << (rank_num)) - 1)
#define DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE (0)
#define DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NORMAL (1)
#define DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_INIT (2)
#ifdef PRODUCT_DDR_AGING_TEST
#define DDR_CORE_VOL_AVS_BIAS_HIGH 0
#define DDR_CORE_VOL_AVS_BIAS_NORMAL 0
#define DDR_CORE_VOL_AVS_BIAS_LOW (-15)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE)
#define DDR_CORE_VOL_AVS_BIAS_LOW_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_HPM_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_HPM_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_LOW_HPM_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_VOL_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_VOL_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_LOW_VOL_RECOUP (1)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_OVERFLOW_CHECK (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_OVERFLOW_CHECK (0)
#define DDR_CORE_VOL_AVS_BIAS_LOW_OVERFLOW_CHECK (0)
#define DDR_VOLTE_415MHZ_HIGH 635
#define DDR_CORE_VOL_HIGH_0 645
#define DDR_CORE_VOL_HIGH_1 665
#define DDR_CORE_VOL_HIGH_2 720
#define DDR_CORE_VOL_HIGH_3 770
#define DDR_CORE_VOL_HIGH_4 820
#define DDR_VOLTE_415MHZ_NORMAL 620
#define DDR_CORE_VOL_NORMAL_0 630
#define DDR_CORE_VOL_NORMAL_1 650
#define DDR_CORE_VOL_NORMAL_2 700
#define DDR_CORE_VOL_NORMAL_3 750
#define DDR_CORE_VOL_NORMAL_4 800
#define DDR_VOLTE_415MHZ_LOW 605
#define DDR_CORE_VOL_LOW_0 615
#define DDR_CORE_VOL_LOW_1 635
#define DDR_CORE_VOL_LOW_2 680
#define DDR_CORE_VOL_LOW_3 730
#define DDR_CORE_VOL_LOW_4 780
#define DDR_VDDQ_VOL_HIGH 600
#define DDR_VDDQ_VOL_NORMAL 600
#define DDR_VDDQ_VOL_LOW 600
#define DDR_VDD2_VOL_HIGH 1150
#define DDR_VDD2_VOL_NORMAL 1120
#define DDR_VDD2_VOL_LOW 1090
#define DDR_VDD1_VOL_HIGH 1850
#define DDR_VDD1_VOL_NORMAL 1800
#define DDR_VDD1_VOL_LOW 1750
#define DDR_PHYPLL_VOL_HIGH 1235
#define DDR_PHYPLL_VOL_NORMAL 1200
#define DDR_PHYPLL_VOL_LOW 1165
#define DDR_MEM_VOL_HIGH 800
#define DDR_MEM_VOL_NORMAL 800
#define DDR_MEM_VOL_LOW 800
#else
#define DDR_CORE_VOL_AVS_BIAS_HIGH 0
#define DDR_CORE_VOL_AVS_BIAS_NORMAL 0
#define DDR_CORE_VOL_AVS_BIAS_LOW (-20)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NONE)
#define DDR_CORE_VOL_AVS_BIAS_LOW_TEMP_RECOUP (DDR_CORE_VOL_AVS_BIAS_TEMP_RECOUP_NORMAL)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_HPM_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_HPM_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_LOW_HPM_RECOUP (1)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_VOL_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_VOL_RECOUP (0)
#define DDR_CORE_VOL_AVS_BIAS_LOW_VOL_RECOUP (1)
#define DDR_CORE_VOL_AVS_BIAS_HIGH_OVERFLOW_CHECK (0)
#define DDR_CORE_VOL_AVS_BIAS_NORMAL_OVERFLOW_CHECK (1)
#define DDR_CORE_VOL_AVS_BIAS_LOW_OVERFLOW_CHECK (0)
#if (defined CONFIG_HISI_DDR_AVS_TEST || defined HIBENCH_XLOADER || defined __SLT_FEATURE__)
#define DDR_VOLTE_415MHZ_HIGH 650
#endif
#define DDR_CORE_VOL_HIGH_0 660
#define DDR_CORE_VOL_HIGH_1 680
#define DDR_CORE_VOL_HIGH_2 735
#define DDR_CORE_VOL_HIGH_3 785
#define DDR_CORE_VOL_HIGH_4 840
#if (defined CONFIG_HISI_DDR_AVS_TEST || defined HIBENCH_XLOADER || defined __SLT_FEATURE__)
#define DDR_VOLTE_415MHZ_NORMAL 620
#endif
#define DDR_CORE_VOL_NORMAL_0 630
#define DDR_CORE_VOL_NORMAL_1 650
#define DDR_CORE_VOL_NORMAL_2 700
#define DDR_CORE_VOL_NORMAL_3 750
#define DDR_CORE_VOL_NORMAL_4 800
#if (defined CONFIG_HISI_DDR_AVS_TEST || defined HIBENCH_XLOADER || defined __SLT_FEATURE__)
#define DDR_VOLTE_415MHZ_LOW 590
#endif
#define DDR_CORE_VOL_LOW_0 600
#define DDR_CORE_VOL_LOW_1 620
#define DDR_CORE_VOL_LOW_2 665
#define DDR_CORE_VOL_LOW_3 715
#define DDR_CORE_VOL_LOW_4 760
#define DDR_VDDQ_VOL_HIGH 630
#define DDR_VDDQ_VOL_NORMAL 600
#define DDR_VDDQ_VOL_LOW 570
#define DDR_VDD2_VOL_HIGH 1170
#define DDR_VDD2_VOL_NORMAL 1120
#define DDR_VDD2_VOL_LOW 1070
#define DDR_VDD1_VOL_HIGH 1890
#define DDR_VDD1_VOL_NORMAL 1800
#define DDR_VDD1_VOL_LOW 1710
#define DDR_PHYPLL_VOL_HIGH 1260
#define DDR_PHYPLL_VOL_NORMAL 1200
#define DDR_PHYPLL_VOL_LOW 1140
#define DDR_MEM_VOL_HIGH 840
#define DDR_MEM_VOL_NORMAL 800
#define DDR_MEM_VOL_LOW 760
#endif
#define DDR_VOL_LEVEL0 (0)
#define DDR_VOL_LEVEL1 (1)
#define DDR_VOL_LEVEL2 (2)
#define DDR_VOL_LEVEL3 (3)
#define DDR_VOL_LEVEL4 (4)
#define FREQ_VOLT_RANGE (5)
#define DDR_SCENE_ID_NT_0 (0)
#define DDR_SCENE_ID_LT (1)
#define DDR_SCENE_ID_NT_20 (2)
#define DDR_SCENE_ID_NT_40 (3)
#define DDR_SCENE_ID_NT_60 (4)
#define DDR_SCENE_ID_MAX (5)
#define DDR_NORMALTEMP (0)
#define DDR_LOWTEMP (1)
#define TRAINING_RESULT_IDX_MAP_INVALID_VALUE (0xFF)
#define MANU_ID_SAMSUNG (0x1)
#define MANU_ID_MICRON (0xff)
#define MANU_ID_HYNIX (0x6)
#define HOST_ODT_VDDQ_2 (1)
#define HOST_ODT_3VDDQ_5 (2)
#define DRAM_ODT_VDDQ_2 (1)
#define DRAM_ODT_3VDDQ_5 (2)
#define HOST_PU_CAL_VDDQ_2 (0)
#define HOST_PU_CAL_3VDDQ_5 (1)
#define DRAM_PU_CAL_VDDQ_2 (0)
#define DRAM_PU_CAL_3VDDQ_5 (1)
#define CK_ODT_1RANK (1)
#define CK_ODT_2RANK (2)
#define PHASE_SEL_ADDRPH_A (1)
#define PHASE_SEL_CMD1TPH (2)
#define PHASE_SEL_STATIC_REG (3)
#define PHASE_SEL_ACCTL_POSEDGE (4)
#define PHASE_360 (0x40)
#define PHASE_180 (0x20)
#define PHASE_90 (0x10)
#define PHASE_60 (0x8)
#define PHASE_45 (0x6)
#define PHASE_30 (0x4)
#define PHASE_15 (0x2)
#define PHASE_0 (0x0)
#define DYNAMIC_TRACK_TYPE0 (0)
#define DYNAMIC_TRACK_TYPE1 (1)
#define PHYGATE_TYPE_GCNT (1)
#define PHYGATE_TYPE_AUTO (2)
#define PHYGATE_TYPE_DIG_EN (3)
#define PLL_SOURCE_SCPLL (0)
#define PLL_SOURCE_FNPLL (1)
typedef enum {
 DDR_CORE_VOL = 0,
 DDR_VDDQ_VOL,
 DDR_VDD2_VOL,
 DDR_VDD1_VOL,
 DDR_PHYPLL_VOL,
 DDR_MEM_VOL,
 DDR_VOL_MAX,
} DDR_VOL_ID;
typedef enum {
 DDRC_NUM_0 = 0,
#ifndef DDR_SINGLE_CHANNEL
 DDRC_NUM_1,
#endif
 DDRC_NUM_MAX,
} DDRC_NUM;
typedef enum {
 DMC_NUM_0 = 0,
#ifndef DDR_SINGLE_CHANNEL
 DMC_NUM_1,
#endif
 DMC_NUM_MAX,
} DMC_NUM;
typedef enum {
 DDR_PLL0 = 0,
 DDR_PLL1,
 DDR_PLL4,
 DDR_PLL2,
 DDR_PLL_MAX,
} DDR_PLL_IDX;
typedef enum {
 ASIC = 0,
 FPGA,
 EMULATOR,
} DDR_BOARD_TYPE;
#define DDR_BURST_LEN_16 (0)
#define DDR_BURST_LEN_32 (1)
#define DDR_BURST_LEN_OTF (2)
typedef enum {
 DDR_AUTOFSGT_ENABLE = 1,
 DDR_AUTOFSGT_DISABLE,
 DDR_AUTOFSGT_LOGIC_EN,
 DDR_AUTOFSGT_LOGIC_DIS,
} DDR_AUTOFSGT_CMD_ID;
typedef enum {
 DDR_AUTOFSGT_CLIENT_LPMCU = 0,
 DDR_AUTOFSGT_CLIENT_BL31 = 1,
 DDR_AUTOFSGT_PROXY_CLIENT_FREQDUMP,
 DDR_AUTOFSGT_PROXY_CLIENT_DDRREG,
 DDR_AUTOFSGT_PROXY_CLIENT_KERNEL_CODE,
 DDR_AUTOFSGT_PROXY_CLIENT_XDUMP,
 DDR_AUTOFSGT_PROXY_CLIENT_EVSOPEN,
 DDR_AUTOFSGT_PROXY_CLIENT_EVSCLOSE,
 DDR_AUTOFSGT_PROXY_CLIENT_DDR_PERFDATA,
 DDR_AUTOFSGT_PROXY_CLIENT_SYSCACHE,
 DDR_AUTOFSGT_CLIENT_SECURE_OS = 10,
 DDR_AUTOFSGT_PROXY_CLIENT_SETSEC = 10,
 DDR_AUTOFSGT_PROXY_CLIENT_CLRSEC = 10,
 DDR_AUTOFSGT_PROXY_CLIENT_CHECKSEC = 10,
 DDR_AUTOFSGT_CLIENT_AP,
 DDR_AUTOFSGT_PROXY_CLIENT_DDRFLUX,
 DDR_AUTOFSGT_PROXY_CLIENT_DMSSPT,
 DDR_AUTOFSGT_PROXY_CLIENT_BUTT,
} DDR_AUTOFSGT_PROXY_CLIENT_ID;
typedef enum {
 DDR_NODE_OPP_FREQ = 0,
 DDR_NODE_OPP_VOL,
 DDR_NODE_OPP_MAX,
} DDR_NODE_OPP_ID;
#ifdef __CORTEX_M3
#if ((DDR_AUTOFSGT_PROXY_CLIENT_BUTT) > 15)
    #error "ddr autofsgt bypass bit overflow!!!"
#endif
#endif
#define DMSS_SEC_REGION_MAX (32)
#define MPU_RAM_SIZE (0x2000)
#define DMSS_ASI_MAX (17)
#define DMSS_DMI_MAX (2)
#define DMSS_AMI_MAX (2)
#define DMSS_PER_ASI_SIZE (0x800)
#define AXI_MAX_PORT DMSS_ASI_MAX
#define DMSS_CHANS_MAX DMSS_CHANS_MAX_NUM
#define SEC_REGION_MAX DMSS_SEC_REGION_MAX
#define SEC_MODE_CNT (1)
#ifdef DDR_BASE_ADDR_LPMCU
#define DDR_DMSS_BASE_ADDR SOC_LPMCU_DMSS_BASE_ADDR
#define DDR_DMCPACK0_BASE_ADDR SOC_LPMCU_DMCPACK0_BASE_ADDR
#define SOC_SCTRL_BASE_ADDR SOC_LPMCU_SCTRL_BASE_ADDR
#else
#define DDR_DMSS_BASE_ADDR SOC_ACPU_DMSS_BASE_ADDR
#define DDR_DMCPACK0_BASE_ADDR SOC_ACPU_DMCPACK0_BASE_ADDR
#define SOC_SCTRL_BASE_ADDR SOC_ACPU_SCTRL_BASE_ADDR
#endif
#define DDR_REG_DMSS (DDR_DMSS_BASE_ADDR)
#define DDR_REG_AXI(n) (DDR_DMSS_BASE_ADDR + 0x800 * (n))
#define DDR_REG_GLOBAL (DDR_DMSS_BASE_ADDR + 0x6000)
#define DDR_REG_EXMBIST (DDR_DMSS_BASE_ADDR + 0x38000)
#define DDR_REG_PACK(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n))
#define DDR_REG_PHY(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x1000)
#define DDR_REG_SW_TRAIN(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x2000)
#define DDRC_REG_DMC(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x4000)
#define DDRC_REG_DUMREG(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x4000)
#define DDR_REG_DMC(m,n) (DDR_DMCPACK0_BASE_ADDR + 0x4000 + 0x20000 * (m * 2) + 0x20000 * (n))
#define DDR_REG_UCE_TCM(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x8000)
#define DDR_REG_UCE_IPC(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x10000)
#define DDR_REG_UCE_UART(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x11000)
#define DDR_REG_UCE_SCTRL(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x12000)
#define DDR_REG_UCE_TIMER(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x13000)
#define DDR_REG_UCE_WDG(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x14000)
#define DDR_REG_UCE_INFO(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x15000)
#define DDR_REG_UCE_PACK(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x18000)
#define DDR_REG_UCE_PHY(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x19000)
#define DDR_REG_UCE_PACK_SWPT(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x1A000)
#define DDR_REG_UCE_DMC(n) (DDR_DMCPACK0_BASE_ADDR + 0x20000 * (n) + 0x1B000)
#define DDR_REG_MPU (DDR_DMSS_BASE_ADDR + 0x20000)
#define DDR_REG_MPU_SIZE (0x2000)
#define UCE_DDR_REG_PACK (SOC_UCE_UCE_PACK_BASE_ADDR)
#define UCE_DDR_REG_PHY (SOC_UCE_UCE_PACK_BASE_ADDR + 0x1000)
#define UCE_DDR_REG_DMC (SOC_UCE_UCE_DMC_BASE_ADDR)
#define UCE_DDR_REG_DUMREG (SOC_UCE_UCE_DMC_BASE_ADDR)
#ifndef REG_BASE_DMSS
#define REG_BASE_DMSS DDR_REG_DMSS
#endif
#define DDR_REG_DMC_CFG(n) (DDRC_REG_DMC(n))
#ifndef DDR_EDA
#define DDR_REG_CFG_CAT_BDL_STEP (0x0)
#define DDR_REG_CFG_DVREFT_STEP (0x1)
#define DDR_REG_CFG_RPAT_CNT_NUM (0xf)
#define DDR_REG_CFG_CAL_ALT_NUM (0x4)
#define DDR_REG_CFG_WDET_MPC_CNT (0xf)
#define DDR_REG_CFG_DUMMY_RD_CNT (0x23366)
#define DDR_REG_CFG_LP_L2_IDLE (0x258)
#define DDR_REG_CFG_LP_L3_IDLE (0x4b0)
#define DDR_REG_CFG_RETRAIN_THRD (0xFFFF)
#define DDR_REG_CFG_ZQ_INTLV_PRD (0x5F5E100)
#define DDR_REG_CFG_GT_BDL_STEP (0x0)
#define DDR_REG_CFG_RPAT_CNT_NUM_OPEN (0xf)
#endif
#define DDR_DYNAMIC_TRACK_DISABLE (0)
#define DDR_DYNAMIC_TRACK_ALL_BIT (1)
#define DDR_DYNAMIC_TRACK_SINGLE_BIT (2)
#define DDR_REG_CFG_EN_DXCTL_RXN_2ND_DQ (0xFF)
#define DDR_REG_CFG_EN_DXCTL_RXP_2ND_DQ (0xFF)
#define DDR_REG_CFG_EN_DXCTL_RXN_2ND_DM (0x1)
#define DDR_REG_CFG_EN_DXCTL_RXP_2ND_DM (0x1)
#define DDR_REG_CFG_EN_REG_DQSDLY_PRI_EN (0x1)
#define DDR_REG_CFG_EN_DXCTL_SW_MARGIN_CODE (0x6)
#define DDR_REG_CFG_SINGLE_BIT_EN_DXCTL_RXN_2ND_DQ (0x1)
#define DDR_REG_CFG_DIS_DXCTL_RXN_2ND_DQ (0x0)
#define DDR_REG_CFG_DIS_DXCTL_RXP_2ND_DQ (0x0)
#define DDR_REG_CFG_DIS_DXCTL_RXN_2ND_DM (0x0)
#define DDR_REG_CFG_DIS_DXCTL_RXP_2ND_DM (0x0)
#define DDR_REG_CFG_DIS_REG_DQSDLY_PRI_EN (0x0)
#define DDR_REG_CFG_DIS_DXCTL_SW_MARGIN_CODE (0x0)
#define DDR_REG_CFG_ZCODE_PDRV_CAL_MAX (0x7F)
#define DDR_REG_CFG_ZCODE_NDRV_CAL_MAX (0x3F)
#define DDR_REG_CFG_UC_ROWACT_TYPE (0x0)
#define DDR_REG_CFG_UC_RT_POPULATE (0x2)
#define DDR_REG_CFG_UC_REGIF_WST (0x1)
#define DDR_REG_CFG_UC_MODE_EN (0x0)
#define DDR_FREQ_SCBAKDATA_ADDR (SOC_SCTRL_SCBAKDATA4_ADDR(SOC_SCTRL_BASE_ADDR))
#define DDR_FREQ_SCBAKDATA_START (8)
#define DDR_FREQ_SCBAKDATA_END (11)
#define DDR_MANU_SCBAKDATA_START 0
#define DDR_MANU_SCBAKDATA_END 7
#define DDR_SIZE_SCBAKDATA_START 8
#define DDR_SIZE_SCBAKDATA_END 15
#define DDR_DRAM_SIZE_8G 8
#define DDR_LPRAM_ADDR_TO_AP_ADDR(addr) (((addr) - SOC_LPMCU_DMCPACK0_BASE_ADDR) + SOC_ACPU_DMCPACK0_BASE_ADDR)
#ifndef DDR_EDA
#define DDR_BUILD_BUG_ON(e) ((void)(sizeof(struct { int:1; int:-((int)!!(e)); })))
#else
#define DDR_BUILD_BUG_ON(e) 
#endif
#define DDR_INFO_SECRET_KEY (0x646472)
#define DMSS_VSET PMIC_BUCK00_VSET_ADDR(0)
#define DMC_CORE_VSET PMIC_BUCK6_VSET_ADDR(0)
#define DMSS_VMIN (400)
#define DMC_CORE_VMIN (400)
#define PMU6421_STEP (5)
#define DDR_SEC_CFG_MODEM_MASK 0x21U
#define DDR_SEC_CFG_AP_MASK (~(DDR_SEC_CFG_MODEM_MASK))
#define DDR_4096M 4096
#define DDR_8192M 8192
#define DDR_12288M 12288
#define DDR_SIZE_8GB 8
#define NEW_BOARDID_FLAG 1
#define NEW_BOARDID_START 31
#define NEW_BOARDID_END 31
#define DDR_SIZE_INFO_START 8
#define DDR_SIZE_INFO_END 15
#define DDR_MPU_CFG_SIZE_4G (0)
#define DDR_MPU_CFG_SIZE_8G (1)
#define DDR_MPU_CFG_SIZE_16G (2)
#define DDR_CAPACITY_1MB 0x100000
#define DDR_SIZE_MBTOB(size_mbyte) ((size_mbyte) * DDR_CAPACITY_1MB)
#define MODEREG01_MR1_START 0
#define MODEREG01_MR1_END 7
#define MODEREG01_MR2_START 8
#define MODEREG01_MR2_END 15
#define MODEREG01_MR3_START 16
#define MODEREG01_MR3_END 23
#define MODEREG01_MR11_START 24
#define MODEREG01_MR11_END 31
#define MODEREG23_MR22_START 0
#define MODEREG23_MR22_END 7
#define MODEREG67_MR13_START 0
#define MODEREG67_MR13_END 7
#define SFC_CMD_MRW 0x0U
#define SFC_CMD_MRR 0xEU
#define SFC_CMD_XPD 0xFU
#define SFC_CMD_PD 0x10U
#define SFC_CMD_MPC 0xAU
#define SFC_CMD_MASK 0x1FU
#define SFC_CMD_OFFSET 0
#define SFC_TIM_TMRD 0x11U
#define SFC_TIM_TMRW 0x12U
#define SFC_TIM_TRRD 0x13U
#define SFC_TIM_TLAST 0x1DU
#define SFC_TIM_TRESERV 0x1EU
#define SFC_TIM_MASK 0x1FU
#define SFC_TIM_OFFSET 5
#define SFC_MRW_MA_OFFSET 10
#define SFC_MRW_MA_MASK 0xFFU
#define SFC_MRW_OP_OFFSET 18
#define SFC_MRW_OP_MASK 0xFFU
#define SFC_MRR_MA_OFFSET 10
#define SFC_MRR_MA_MASK 0xFFU
#define SFC_MRR_OP_MASK 0xFFU
#define SFC_MPC_OP_OFFSET 10
#define SFC_MPC_OP_MASK 0x7FU
#define MPC_NOP ((DRAM_MPC_NOP_OP << SFC_MPC_OP_OFFSET) | (SFC_TIM_TMRD << SFC_TIM_OFFSET) | (SFC_CMD_MPC << SFC_CMD_OFFSET))
#define MPC_ZQCAL_START ((DRAM_MPC_ZQCALSTART_OP << SFC_MPC_OP_OFFSET) | (0x14 << SFC_TIM_OFFSET) | (SFC_CMD_MPC << SFC_CMD_OFFSET))
#define MPC_ZQCAL_LATCH ((DRAM_MPC_ZQCALLATCH_OP << SFC_MPC_OP_OFFSET) | (0xA << SFC_TIM_OFFSET) | (SFC_CMD_MPC << SFC_CMD_OFFSET))
#define DRAM_MPC_NOP_OP 0U
#define DRAM_MPC_ZQCALSTART_OP 0x4FU
#define DRAM_MPC_ZQCALLATCH_OP 0x51U
#define DRAM_MR11_OP_DQODT_START 0
#define DRAM_MR11_OP_DQODT_END 2
#define DRAM_MR11_OP_CAODT_START 4
#define DRAM_MR11_OP_CAODT_END 6
#define DRAM_MR13_OP_VRCG_OFFSET 3
#define DRAM_MR13_OP_RRO_OFFSET 4
#define DRAM_MR13_OP_FSP_WR_OFFSET 6
#define DRAM_MR13_OP_FSP_OP_OFFSET 7
#define DRAM_MR21_OP_SINGLEENDEDMODE_OFFSET 5
#define DRAM_MR22_OP_ODTECK_OFFSET 3
#define DRAM_MR22_OP_ODTDCA_OFFSET 5
#define DRAM_MR51_OP_SEQERD_OFFSET 1
#define DRAM_MR51_OP_SEQEWR_OFFSET 2
#define DRAM_MR51_OP_SECE_OFFSET 3
#define DRAM_MR_OP_MASK 0xFFU
#define DRAM_MR0 0U
#define DRAM_MR1 1U
#define DRAM_MR2 2U
#define DRAM_MR3 3U
#define DRAM_MR4 4U
#define DRAM_MR5 5U
#define DRAM_MR6 6U
#define DRAM_MR7 7U
#define DRAM_MR8 8U
#define DRAM_MR9 9U
#define DRAM_MR10 10U
#define DRAM_MR11 11U
#define DRAM_MR12 12U
#define DRAM_MR13 13U
#define DRAM_MR14 14U
#define DRAM_MR21 21U
#define DRAM_MR22 22U
#define DRAM_MR31 31U
#define DRAM_MR51 51U
#endif
