#ifndef __SOC_EFUSE_INTERFACE_H__
#define __SOC_EFUSE_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#define EFUSE_ATTR_READABLE (0x00000001UL)
#define EFUSE_ATTR_READ_DEVICE (0x00000002UL)
#define EFUSE_ATTR_READ_SRAM (0x00000004UL)
#define EFUSE_ATTR_READ_ZERO (0x00000008UL)
#define EFUSE_ATTR_WRITEABLE (0x00000100UL)
#define EFUSE_ATTR_WRITE_NOT_UPDATE (0x00000200UL)
#define EFUSE_ATTR_WRITE_CHECK (0x00000400UL)
typedef struct {
 unsigned int start_bit;
 unsigned int bit_cnt;
 unsigned int id;
 unsigned int attr;
} efuse_attr_t;
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_HPM_TRIM,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER,
 EFUSE_MODEM_HUK = 20,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE,
 EFUSE_CARRI_INFO,
 EFUSE_FLASH_COUNT,
 EFUSE_INSE_FLAG,
 EFUSE_ROOT_KEY,
 EFUSE_EFUSE2EPS_B,
 EFUSE_EFUSE2EPS_A,
 EFUSE_EFUSE2EPS_GID,
 EFUSE_CC712_KPTRL = 30,
 EFUSE_CHIP_ID,
 EFUSE_SHUTDOWN_SWINGCARD,
 EFUSE_AUTH_KEY,
 EFUSE_DJTAG_CTRL,
 EFUSE_CHIPIDDFTKEY_ZEROES,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HISEE_EFUSE4,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE = 40,
 EFUSE_DFTRD_DISABLE,
 EFUSE_SECDBG_CTRL,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_EPS_GIDRDEN = 50,
 EFUSE_DX_CLKEN,
 EFUSE_UDS_HIGHER,
 EFUSE_UDS_LOWER,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE,
 EFUSE_GPU_VDDPC,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CAMERACPHY3G3_SCREEN,
 EFUSE_MODEM_AVSPASS1,
 EFUSE_MODEM_AVSPASS2 = 60,
 EFUSE_PARTIAL_PASSP1,
 EFUSE_PARTIAL_PASSP2,
 EFUSE_PARTIAL_PASSP3,
 EFUSE_PARTIAL_PASSP4,
 EFUSE_ATE_FLAG,
 EFUSE_CPUL3OROTHER_PARTIAL,
};
#define EFUSE_HUK_VALUE_START 0
#define EFUSE_HUK_VALUE_SIZE 256
#define EFUSE_SCP_VALUE_START 256
#define EFUSE_SCP_VALUE_SIZE 64
#define EFUSE_MP_FLAG_START 320
#define EFUSE_MP_FLAG_SIZE 32
#define EFUSE_HUK_ZEROES_START 320
#define EFUSE_HUK_ZEROES_SIZE 8
#define EFUSE_SCP_ZEROES_START 328
#define EFUSE_SCP_ZEROES_SIZE 7
#define EFUSE_OEMP_FLAG_START 352
#define EFUSE_OEMP_FLAG_SIZE 32
#define EFUSE_HBK1_ZEROES_START 360
#define EFUSE_HBK1_ZEROES_SIZE 8
#define EFUSE_KCE_ZEROES_START 376
#define EFUSE_KCE_ZEROES_SIZE 8
#define EFUSE_KCE_VALUE_START 384
#define EFUSE_KCE_VALUE_SIZE 128
#define EFUSE_HBK0_VALUE_START 512
#define EFUSE_HBK0_VALUE_SIZE 128
#define EFUSE_HBK1_VALUE_START 640
#define EFUSE_HBK1_VALUE_SIZE 128
#define EFUSE_TRB_COUNTER_START 768
#define EFUSE_TRB_COUNTER_SIZE 32
#define EFUSE_NTRB_COUNTER_START 800
#define EFUSE_NTRB_COUNTER_SIZE 224
#define EFUSE_EKCST_VALUE_START 1024
#define EFUSE_EKCST_VALUE_SIZE 128
#define EFUSE_EKCST_ZEROES_START 1152
#define EFUSE_EKCST_ZEROES_SIZE 32
#define EFUSE_DIEID_VALUE_START 1184
#define EFUSE_DIEID_VALUE_SIZE 160
#define EFUSE_IDDQ_VALUE_START 1344
#define EFUSE_IDDQ_VALUE_SIZE 50
#define EFUSE_HPM_TRIM_START 1449
#define EFUSE_HPM_TRIM_SIZE 10
#define EFUSE_SLT_FINISH_START 1644
#define EFUSE_SLT_FINISH_SIZE 3
#define EFUSE_SOFT_COUNTER_START 1647
#define EFUSE_SOFT_COUNTER_SIZE 32
#define EFUSE_MODEM_HUK_START 1679
#define EFUSE_MODEM_HUK_SIZE 128
#define EFUSE_MODEM_HUKZEROES_START 1807
#define EFUSE_MODEM_HUKZEROES_SIZE 8
#define EFUSE_DMHASH_VALUE_START 1815
#define EFUSE_DMHASH_VALUE_SIZE 1
#define EFUSE_CARRI_INFO_START 1816
#define EFUSE_CARRI_INFO_SIZE 88
#define EFUSE_FLASH_COUNT_START 1904
#define EFUSE_FLASH_COUNT_SIZE 8
#define EFUSE_INSE_FLAG_START 3008
#define EFUSE_INSE_FLAG_SIZE 2
#define EFUSE_ROOT_KEY_START 3084
#define EFUSE_ROOT_KEY_SIZE 264
#define EFUSE_DDR_FNPLL_SWITCH_START 3435
#define EFUSE_DDR_FNPLL_SWITCH_SIZE 1
#define EFUSE_EFUSE2EPS_B_START 3545
#define EFUSE_EFUSE2EPS_B_SIZE 22
#define EFUSE_EFUSE2EPS_A_START 3567
#define EFUSE_EFUSE2EPS_A_SIZE 49
#define EFUSE_EFUSE2EPS_GID_START 3616
#define EFUSE_EFUSE2EPS_GID_SIZE 64
#define EFUSE_CC712_KPTRL_START 3680
#define EFUSE_CC712_KPTRL_SIZE 128
#define EFUSE_CHIP_ID_START 3872
#define EFUSE_CHIP_ID_SIZE 64
#define EFUSE_SHUTDOWN_SWINGCARD_START 4081
#define EFUSE_SHUTDOWN_SWINGCARD_SIZE 2
#define EFUSE_AUTH_KEY_START 3936
#define EFUSE_AUTH_KEY_SIZE 64
#define EFUSE_DJTAG_CTRL_START 4050
#define EFUSE_DJTAG_CTRL_SIZE 2
#define EFUSE_CHIPIDDFTKEY_ZEROES_START 4053
#define EFUSE_CHIPIDDFTKEY_ZEROES_SIZE 8
#define EFUSE_MODEM_DBGBYPASS_START 4061
#define EFUSE_MODEM_DBGBYPASS_SIZE 1
#define EFUSE_PAD_DISABLE_START 4065
#define EFUSE_PAD_DISABLE_SIZE 1
#define EFUSE_HISEE_EFUSE4_START 4068
#define EFUSE_HISEE_EFUSE4_SIZE 2
#define EFUSE_HUKRD_DISABLE_START 4070
#define EFUSE_HUKRD_DISABLE_SIZE 1
#define EFUSE_SCPRD_DISABLE_START 4071
#define EFUSE_SCPRD_DISABLE_SIZE 1
#define EFUSE_DFTRD_DISABLE_START 4072
#define EFUSE_DFTRD_DISABLE_SIZE 1
#define EFUSE_SECDBG_CTRL_START 4073
#define EFUSE_SECDBG_CTRL_SIZE 2
#define EFUSE_SECDBG_DBGEN_START 4075
#define EFUSE_SECDBG_DBGEN_SIZE 1
#define EFUSE_SECDBG_NIDEN_START 4076
#define EFUSE_SECDBG_NIDEN_SIZE 1
#define EFUSE_SECDBG_SPIDEN_START 4077
#define EFUSE_SECDBG_SPIDEN_SIZE 1
#define EFUSE_SECDBG_SPNIDEN_START 4078
#define EFUSE_SECDBG_SPNIDEN_SIZE 1
#define EFUSE_SECDBG_DSPJTAGDIS_START 4079
#define EFUSE_SECDBG_DSPJTAGDIS_SIZE 1
#define EFUSE_SECENG_EKCSTRDEN_START 4083
#define EFUSE_SECENG_EKCSTRDEN_SIZE 1
#define EFUSE_KPRTLRD_DISABLE_START 4084
#define EFUSE_KPRTLRD_DISABLE_SIZE 1
#define EFUSE_EPS_GIDRDEN_START 4086
#define EFUSE_EPS_GIDRDEN_SIZE 1
#define EFUSE_DX_CLKEN_START 4092
#define EFUSE_DX_CLKEN_SIZE 1
#define EFUSE_UDS_HIGHER_START 2240
#define EFUSE_UDS_HIGHER_SIZE 192
#define EFUSE_UDS_LOWER_START 2944
#define EFUSE_UDS_LOWER_SIZE 64
#define EFUSE_DICE_EN_START 2925
#define EFUSE_DICE_EN_SIZE 2
#define EFUSE_DCIE_SECENGINE_START 3083
#define EFUSE_DCIE_SECENGINE_SIZE 1
#define EFUSE_GPU_VDDPC_START 1574
#define EFUSE_GPU_VDDPC_SIZE 2
#define EFUSE_OTP_SEVD_ENABLE_START 2927
#define EFUSE_OTP_SEVD_ENABLE_SIZE 1
#define EFUSE_CAMERACPHY3G3_SCREEN_START 1620
#define EFUSE_CAMERACPHY3G3_SCREEN_SIZE 4
#define EFUSE_MODEM_AVSPASS1_START 1602
#define EFUSE_MODEM_AVSPASS1_SIZE 3
#define EFUSE_MODEM_AVSPASS2_START 1918
#define EFUSE_MODEM_AVSPASS2_SIZE 2
#define EFUSE_MODEM_AVSPASS3_START 3014
#define EFUSE_MODEM_AVSPASS3_SIZE 1
#define EFUSE_PARTIAL_PASSP1_START 1624
#define EFUSE_PARTIAL_PASSP1_SIZE 20
#define EFUSE_PARTIAL_PASSP2_START 3438
#define EFUSE_PARTIAL_PASSP2_SIZE 2
#define EFUSE_PARTIAL_PASSP3_START 3541
#define EFUSE_PARTIAL_PASSP3_SIZE 2
#define EFUSE_PARTIAL_PASSP4_START 3828
#define EFUSE_PARTIAL_PASSP4_SIZE 1
#define EFUSE_ATE_FLAG_START 1312
#define EFUSE_ATE_FLAG_SIZE 1
#define EFUSE_CPUL3OROTHER_PARTIAL_START 1344
#define EFUSE_CPUL3OROTHER_PARTIAL_SIZE 20
#define EFUSE_MAX_SIZE 4096
#define EFUSE_ITEM_MAX 264
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
