obj-$(CONFIG_HUAWEI_BATTERY_INFORMATION) += battery_ct/
obj-$(CONFIG_HUAWEI_BATTERY_VOLTAGE) += battery_voltage/
obj-$(CONFIG_HUAWEI_BATTERY_TEMP_FITTING) += battery_temp_fitting/
obj-$(CONFIG_HUAWEI_BATTERY_CAPACITY) += battery_capacity/
