obj-$(CONFIG_WIRELESS_ACCESSORY) += stwlc33/
obj-$(CONFIG_WIRELESS_ACCESSORY) += stwlc68_aux/
obj-$(CONFIG_WIRELESS_ACCESSORY) += wireless_transmitter_aux.o
obj-$(CONFIG_WIRELESS_ACCESSORY) += wireless_keyboard/
