obj-y +=ipc_mailbox.o
obj-y +=ipc_rproc.o
obj-y +=ipc_rproc_id_mgr.o
obj-y +=ipc_mailbox_event.o
obj-y +=ipc_mailbox_mntn.o
obj-$(CONFIG_HISI_RPROC_TESTFILE) +=ipc_rproc_test.o
obj-$(CONFIG_HISI_MAILBOX) +=ipc_mailbox_dev.o
subdir-ccflags-$(CONFIG_HISI_BB)    += -Idrivers/hisi/mntn/blackbox/

