#
# Makefile for the memory technology device drivers.
#
# Core functionality.


obj-y				+= dump_config.o 
obj-y				+= dump_logs.o
obj-y				+= dump_log_agent.o
obj-y                           += dump_logzip.o
