subdir-ccflags-y := -Werror
 -include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/$(OBB_MODEM_CUST_CONFIG_DIR)/config/balong_product_config.mk

obj-y += vdev_core.o vdev_msg.o vdev_app.o vdev_relay.o vdev_atp.o vdev_hmi.o
