obj-$(CONFIG_CPU_EDAC_ARM64) += cpu_edac_arm64.o

ccflags-$(CONFIG_CPU_EDAC_ARM64)  += -Idrivers/edac

obj-$(CONFIG_RAS_TEST) += ras_edac.o
obj-$(CONFIG_RAS_TEST) += ras_err_inj.o
ccflags-$(CONFIG_RAS_TEST)  += -Idrivers/edac
