/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * foss@huawei.com
 *
 * If distributed as part of the Linux kernel, the following license terms
 * apply:
 *
 * * This program is free software; you can redistribute it and/or modify
 * * it under the terms of the GNU General Public License version 2 and
 * * only version 2 as published by the Free Software Foundation.
 * *
 * * This program is distributed in the hope that it will be useful,
 * * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * * GNU General Public License for more details.
 * *
 * * You should have received a copy of the GNU General Public License
 * * along with this program; if not, write to the Free Software
 * * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
 *
 * Otherwise, the following license terms apply:
 *
 * * Redistribution and use in source and binary forms, with or without
 * * modification, are permitted provided that the following conditions
 * * are met:
 * * 1) Redistributions of source code must retain the above copyright
 * *    notice, this list of conditions and the following disclaimer.
 * * 2) Redistributions in binary form must reproduce the above copyright
 * *    notice, this list of conditions and the following disclaimer in the
 * *    documentation and/or other materials provided with the distribution.
 * * 3) Neither the name of Huawei nor the names of its contributors may
 * *    be used to endorse or promote products derived from this software
 * *    without specific prior written permission.
 *
 * * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef __APP_NAS_ERR_CAUSE_H__
#define __APP_NAS_ERR_CAUSE_H__


#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#pragma pack(push, 4)

/* 公共错误码 */
#define APP_ERR_COMMON_SECTION_BEGIN (0)
#define APP_ERR_SM_SECTION_BEGIN (200)
#define APP_ERR_SM_NW_SECTION_BEGIN (400)
#define APP_ERR_MM_SECTION_BEGIN (600)
#define APP_ERR_MM_NW_SECTION_BEGIN (800)
/* Added for HO ATTACH, 2018-12-20 begin */
#define APP_ERR_EHSM_ESM_SECTION_BEGIN (1000)
/* Added for HO ATTACH, 2018-12-20 end */

/* 公共错误码 */
#define APP_SUCCESS (APP_ERR_COMMON_SECTION_BEGIN + 0)
#define APP_FAILURE (APP_ERR_COMMON_SECTION_BEGIN + 1)
#define APP_ERR_NULL_PTR (APP_ERR_COMMON_SECTION_BEGIN + 2)
#define APP_ERR_PARA_ERROR (APP_ERR_COMMON_SECTION_BEGIN + 3)
#define APP_ERR_TIME_OUT (APP_ERR_COMMON_SECTION_BEGIN + 4)
#define APP_ERR_ID_INVALID (APP_ERR_COMMON_SECTION_BEGIN + 5)
#define APP_ERR_NUM_VALUE_INVALID (APP_ERR_COMMON_SECTION_BEGIN + 6)
#define APP_ERR_NUM_LEN_INVALID (APP_ERR_COMMON_SECTION_BEGIN + 7)
#define APP_ERR_CAPABILITY_ERROR (APP_ERR_COMMON_SECTION_BEGIN + 8)
#define APP_ERR_CLIENTID_NO_FREE (APP_ERR_COMMON_SECTION_BEGIN + 9)
#define APP_ERR_CALLBACK_FUNC_ERROR (APP_ERR_COMMON_SECTION_BEGIN + 10)
#define APP_ERR_MSG_DECODING_FAIL (APP_ERR_COMMON_SECTION_BEGIN + 11)
#define APP_ERR_TI_ALLOC_FAIL (APP_ERR_COMMON_SECTION_BEGIN + 12)
#define APP_ERR_TI_GET_FAIL (APP_ERR_COMMON_SECTION_BEGIN + 13)
#define APP_ERR_CMD_TYPE_ERROR (APP_ERR_COMMON_SECTION_BEGIN + 14)
#define APP_ERR_MUX_LINK_EST_FAIL (APP_ERR_COMMON_SECTION_BEGIN + 15)
#define APP_ERR_USIM_SIM_CARD_NOTEXIST (APP_ERR_COMMON_SECTION_BEGIN + 16)
#define APP_ERR_CLIENTID_NOT_EXIST (APP_ERR_COMMON_SECTION_BEGIN + 17)
#define APP_ERR_NEED_PIN1 (APP_ERR_COMMON_SECTION_BEGIN + 18)
#define APP_ERR_NEED_PUK1 (APP_ERR_COMMON_SECTION_BEGIN + 19)
#define APP_ERR_USIM_SIM_INVALIDATION (APP_ERR_COMMON_SECTION_BEGIN + 20)
#define APP_ERR_UNSPECIFIED_ERROR (APP_ERR_COMMON_SECTION_BEGIN + 21)
#define APP_ERR_INSUFFICIENT_RESOURCES (APP_ERR_COMMON_SECTION_BEGIN + 22)

#define APP_ERR_CONN_OR_NO_IMSI (APP_ERR_COMMON_SECTION_BEGIN + 23)
#define APP_ERR_NOT_SUPPORT_NOW (APP_ERR_COMMON_SECTION_BEGIN + 24)
#define APP_ERR_NOT_STARTED_YET (APP_ERR_COMMON_SECTION_BEGIN + 25)

/* MM与APP错误码 */
/* Modified for PDP_CAUSE_RPT,2017-09-11,Begin */
#define APP_ERR_MM_NW_BEAR_NOT_SYNC (APP_ERR_MM_SECTION_BEGIN + 0)
#define APP_ERR_MM_REL_IND (APP_ERR_MM_SECTION_BEGIN + 1)
#define APP_ERR_MM_AUTH_TIME_OUT (APP_ERR_MM_SECTION_BEGIN + 2)
#define APP_ERR_MM_T3410_TIME_OUT (APP_ERR_MM_SECTION_BEGIN + 3)
#define APP_ERR_MM_LINK_ERR (APP_ERR_MM_SECTION_BEGIN + 4)
#define APP_ERR_MM_AUTH_FAIL (APP_ERR_MM_SECTION_BEGIN + 5)
#define APP_ERR_MM_THROT (APP_ERR_MM_SECTION_BEGIN + 6)
#define APP_ERR_MM_PLMN_SRCH_INTERRUPT (APP_ERR_MM_SECTION_BEGIN + 7)
#define APP_ERR_MM_SYS_INFO_INTERRUPT (APP_ERR_MM_SECTION_BEGIN + 8)
#define APP_ERR_MM_SUSPEND_INTERRUPT (APP_ERR_MM_SECTION_BEGIN + 9)
#define APP_ERR_MM_DETACH (APP_ERR_MM_SECTION_BEGIN + 10)
#define APP_ERR_MM_LRRC_ERR_IND (APP_ERR_MM_SECTION_BEGIN + 11)
#define APP_ERR_MM_IMSI_PAGING_DETACH (APP_ERR_MM_SECTION_BEGIN + 12)
#define APP_ERR_MM_ATTACH_EST_FAIL (APP_ERR_MM_SECTION_BEGIN + 13)
#define APP_ERR_MM_STATUS_CANT_TRIGGER (APP_ERR_MM_SECTION_BEGIN + 14)
#define APP_ERR_MM_POWER_OFF (APP_ERR_MM_SECTION_BEGIN + 15)
#define APP_ERR_MM_AREA_LOST (APP_ERR_MM_SECTION_BEGIN + 16)
#define APP_ERR_MM_SYS_CFG_OR_UE_CAP_CHG (APP_ERR_MM_SECTION_BEGIN + 17)
#define APP_ERR_MM_GU_ATTACH_FAIL (APP_ERR_MM_SECTION_BEGIN + 18)
#define APP_ERR_MM_GU_DETACH (APP_ERR_MM_SECTION_BEGIN + 19)
#define APP_ERR_MM_ATTACH_MMC_REL (APP_ERR_MM_SECTION_BEGIN + 20)
#define APP_ERR_MM_ATTACH_CS_CALL_INTERRUPT (APP_ERR_MM_SECTION_BEGIN + 21)
#define APP_ERR_MM_USIM_PULL_OUT (APP_ERR_MM_SECTION_BEGIN + 22)
#define APP_ERR_MM_NW_NOT_SUPPORT_EMC_BEARER (APP_ERR_MM_SECTION_BEGIN + 23)
#define APP_ERR_MM_APP_ABORT_NOTIFY (APP_ERR_MM_SECTION_BEGIN + 24)

#define APP_ERR_MM_UNKNOWN (APP_ERR_MM_SECTION_BEGIN + 199)

/* MM与网侧错误码 */
/* 协议定义的网络拒绝原因值 */

#define APP_ERR_MM_NW_REJ_NULL (APP_ERR_MM_NW_SECTION_BEGIN + 0)
#define APP_ERR_MM_NW_REJ_IMSI_UNKNOWN_IN_HSS (APP_ERR_MM_NW_SECTION_BEGIN + 2)
#define APP_ERR_MM_NW_REJ_ILLEGAL_UE (APP_ERR_MM_NW_SECTION_BEGIN + 3)
#define APP_ERR_MM_NW_REJ_IMEI_NOT_ACCEPTED (APP_ERR_MM_NW_SECTION_BEGIN + 5)
#define APP_ERR_MM_NW_REJ_ILLEGAL_ME (APP_ERR_MM_NW_SECTION_BEGIN + 6)
#define APP_ERR_MM_NW_REJ_EPS_SERV_NOT_ALLOW (APP_ERR_MM_NW_SECTION_BEGIN + 7)
#define APP_ERR_MM_NW_REJ_EPS_SERV_AND_NON_EPS_SERV_NOT_ALLOW (APP_ERR_MM_NW_SECTION_BEGIN + 8)
#define APP_ERR_MM_NW_REJ_UE_ID_NOT_DERIVED (APP_ERR_MM_NW_SECTION_BEGIN + 9)
#define APP_ERR_MM_NW_REJ_IMPLICIT_DETACHED (APP_ERR_MM_NW_SECTION_BEGIN + 10)
#define APP_ERR_MM_NW_REJ_PLMN_NOT_ALLOW (APP_ERR_MM_NW_SECTION_BEGIN + 11)
#define APP_ERR_MM_NW_REJ_TA_NOT_ALLOW (APP_ERR_MM_NW_SECTION_BEGIN + 12)
#define APP_ERR_MM_NW_REJ_ROAM_NOT_ALLOW (APP_ERR_MM_NW_SECTION_BEGIN + 13)
#define APP_ERR_MM_NW_REJ_EPS_SERV_NOT_ALLOW_IN_PLMN (APP_ERR_MM_NW_SECTION_BEGIN + 14)
#define APP_ERR_MM_NW_REJ_NO_SUITABL_CELL (APP_ERR_MM_NW_SECTION_BEGIN + 15)
#define APP_ERR_MM_NW_REJ_MSC_UNREACHABLE (APP_ERR_MM_NW_SECTION_BEGIN + 16)
#define APP_ERR_MM_NW_REJ_NETWORK_FAILURE (APP_ERR_MM_NW_SECTION_BEGIN + 17)
#define APP_ERR_MM_NW_REJ_CS_NOT_AVAIL (APP_ERR_MM_NW_SECTION_BEGIN + 18)
#define APP_ERR_MM_NW_REJ_ESM_FAILURE (APP_ERR_MM_NW_SECTION_BEGIN + 19)
#define APP_ERR_MM_NW_REJ_MAC_FAILURE (APP_ERR_MM_NW_SECTION_BEGIN + 20)
#define APP_ERR_MM_NW_REJ_SYNCH_FAILURE (APP_ERR_MM_NW_SECTION_BEGIN + 21)
#define APP_ERR_MM_NW_REJ_PROCEDURE_CONGESTION (APP_ERR_MM_NW_SECTION_BEGIN + 22)
#define APP_ERR_MM_NW_REJ_UE_SECU_CAP_MISMATCH (APP_ERR_MM_NW_SECTION_BEGIN + 23)
#define APP_ERR_MM_NW_REJ_SECU_MODE_REJECTED_UNSPECIFIED (APP_ERR_MM_NW_SECTION_BEGIN + 24)
#define APP_ERR_MM_NW_REJ_NOT_AUTHORIZED_FOR_THIS_CSG (APP_ERR_MM_NW_SECTION_BEGIN + 25)
#define APP_ERR_MM_NW_REJ_REQUESTED_SER_OPTION_NOT_AUTHORIZED_IN_PLMN (APP_ERR_MM_NW_SECTION_BEGIN + 35)
#define APP_ERR_MM_NW_REJ_CS_FALLBACK_CALL_EST_NOT_ALLOWED (APP_ERR_MM_NW_SECTION_BEGIN + 38)
#define APP_ERR_MM_NW_REJ_CS_DOMAIN_TMP_NOT_ALLOWED (APP_ERR_MM_NW_SECTION_BEGIN + 39)
#define APP_ERR_MM_NW_REJ_NO_EPS_BEARER_CONTEXT_ACTIVATED (APP_ERR_MM_NW_SECTION_BEGIN + 40)
#define APP_ERR_MM_NW_REJ_SERVER_NETWORK_FAILURE (APP_ERR_MM_NW_SECTION_BEGIN + 42)
#define APP_ERR_MM_NW_REJ_SEMANTICALLY_INCORRECT_MSG (APP_ERR_MM_NW_SECTION_BEGIN + 95)
#define APP_ERR_MM_NW_REJ_INVALID_MANDATORY_INF (APP_ERR_MM_NW_SECTION_BEGIN + 96)
#define APP_ERR_MM_NW_REJ_MSG_NONEXIST_NOTIMPLEMENTE (APP_ERR_MM_NW_SECTION_BEGIN + 97)
#define APP_ERR_MM_NW_REJ_MSG_TYPE_NOT_COMPATIBLE (APP_ERR_MM_NW_SECTION_BEGIN + 98)
#define APP_ERR_MM_NW_REJ_IE_NONEXIST_NOTIMPLEMENTED (APP_ERR_MM_NW_SECTION_BEGIN + 99)
#define APP_ERR_MM_NW_REJ_CONDITIONAL_IE_ERROR (APP_ERR_MM_NW_SECTION_BEGIN + 100)
#define APP_ERR_MM_NW_REJ_MSG_NOT_COMPATIBLE (APP_ERR_MM_NW_SECTION_BEGIN + 101)
#define APP_ERR_MM_NW_REJ_PROTOCOL_ERROR (APP_ERR_MM_NW_SECTION_BEGIN + 111)
#define APP_ERR_MM_NW_REJ_OTHERS (APP_ERR_MM_NW_SECTION_BEGIN + 255)
/* Modified for PDP_CAUSE_RPT,2017-09-11,End */

/* SM与APP错误码 */
#define APP_ERR_SM_CALL_CID_INVALID (APP_ERR_SM_SECTION_BEGIN + 0)
#define APP_ERR_SM_CALL_CID_ACTIVE (APP_ERR_SM_SECTION_BEGIN + 1)
#define APP_ERR_SM_CALL_MOD_CID_NOT_MATCH (APP_ERR_SM_SECTION_BEGIN + 2)
#define APP_ERR_SM_CALL_CID_NOT_MATCH_BEARER (APP_ERR_SM_SECTION_BEGIN + 3)
#define APP_ERR_SM_BEARER_TYPE_NOT_DEDICATED (APP_ERR_SM_SECTION_BEGIN + 4)
#define APP_ERR_SM_NO_INCOMING_CALL (APP_ERR_SM_SECTION_BEGIN + 5)
#define APP_ERR_SM_LLC_OR_SNDCP_FAIL (APP_ERR_SM_SECTION_BEGIN + 6)
#define APP_ERR_SM_REACTIV_REQ (APP_ERR_SM_SECTION_BEGIN + 7)
#define APP_ERR_SM_FEATURE_NOT_SUPPORT (APP_ERR_SM_SECTION_BEGIN + 8)
#define APP_ERR_SM_GPRS_ATTACH_FAIL (APP_ERR_SM_SECTION_BEGIN + 9)
#define APP_ERR_SM_OTHER_BEARER_CONT_EXIST (APP_ERR_SM_SECTION_BEGIN + 10)
#define APP_ERR_SM_NSAPI_IN_USE (APP_ERR_SM_SECTION_BEGIN + 11)
#define APP_ERR_SM_COLLISION_WITH_NW (APP_ERR_SM_SECTION_BEGIN + 12)
#define APP_ERR_SM_BEARER_INACTIVE (APP_ERR_SM_SECTION_BEGIN + 13)
#define APP_ERR_SM_DETACHED (APP_ERR_SM_SECTION_BEGIN + 14)
#define APP_ERR_SM_LINK_CID_INVALID (APP_ERR_SM_SECTION_BEGIN + 15)
#define APP_ERR_SM_LINK_BEARER_INACTIVE (APP_ERR_SM_SECTION_BEGIN + 16)
#define APP_ERR_SM_APN_LEN_ILLEGAL (APP_ERR_SM_SECTION_BEGIN + 17)
#define APP_ERR_SM_APN_SYNTACTICAL_ERROR (APP_ERR_SM_SECTION_BEGIN + 18)
#define APP_ERR_SM_SET_APN_BEFORE_SET_AUTH (APP_ERR_SM_SECTION_BEGIN + 19)
#define APP_ERR_SM_AUTH_TYPE_ILLEGAL (APP_ERR_SM_SECTION_BEGIN + 20)
#define APP_ERR_SM_USER_NAME_TOO_LONG (APP_ERR_SM_SECTION_BEGIN + 21)
#define APP_ERR_SM_USER_PASSWORD_TOO_LONG (APP_ERR_SM_SECTION_BEGIN + 22)
#define APP_ERR_SM_ACCESS_NUM_TOO_LONG (APP_ERR_SM_SECTION_BEGIN + 23)
#define APP_ERR_SM_CALL_CID_IN_OPERATION (APP_ERR_SM_SECTION_BEGIN + 24)
#define APP_ERR_SM_BEARER_TYPE_NOT_DEFAULT (APP_ERR_SM_SECTION_BEGIN + 25)
#define APP_ERR_SM_BEARER_TYPE_ILLEGAL (APP_ERR_SM_SECTION_BEGIN + 26)
#define APP_ERR_SM_MUST_EXIST_DEFAULT_TYPE_CID (APP_ERR_SM_SECTION_BEGIN + 27)
#define APP_ERR_SM_PDN_TYPE_ILLEGAL (APP_ERR_SM_SECTION_BEGIN + 28)
#define APP_ERR_SM_IPV4_ADDR_ALLOC_TYPE_ILLEGAL (APP_ERR_SM_SECTION_BEGIN + 29)
#define APP_ERR_SM_SUSPENDED (APP_ERR_SM_SECTION_BEGIN + 30)
#define APP_ERR_SM_MULTI_EMERGENCY_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 31)
#define APP_ERR_SM_NON_EMERGENCY_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 32)
#define APP_ERR_SM_MODIFY_EMERGENCY_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 33)
#define APP_ERR_SM_DEDICATED_FOR_EMERGENCY_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 34)
#define APP_ERR_SM_ONLY_EMERGENCY_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 35)

/* mod for program 2015-01-15 begin */
#define APP_ERR_SM_BACKOFF_ALG_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 36)
/* mod for program 2015-01-15 end */

#define APP_ERR_SM_THROT_ALG_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 37)

/* add for provide PDP_NOT_ALLOWED 2016-05-20 begin */
#define APP_ERR_SM_BACKOFF_ALG_NOT_ALLOWED_IGNORE (APP_ERR_SM_SECTION_BEGIN + 38)
#define APP_ERR_SM_BACKOFF_ALG_NOT_ALLOWED_PERM (APP_ERR_SM_SECTION_BEGIN + 39)
#define APP_ERR_SM_BACKOFF_ALG_NOT_ALLOWED_TEMP (APP_ERR_SM_SECTION_BEGIN + 40)
#define APP_ERR_SM_BACKOFF_ALG_NOT_ALLOWED_RSV (APP_ERR_SM_SECTION_BEGIN + 41)
/* add for provide PDP_NOT_ALLOWED 2016-05-20 end */
#define APP_ERR_SM_THROT_T3396_IS_RUNNING (APP_ERR_SM_SECTION_BEGIN + 42)
#define APP_ERR_SM_NAS_SIG_LOW_PRIORITY_NOT_SUPPROT (APP_ERR_SM_SECTION_BEGIN + 43)

/* Added for Boston_R13_CR_PHASEI, 2016-10-17, Begin */
#define APP_ERR_SM_NAS_MO_SIG_ACCESS_BAR (APP_ERR_SM_SECTION_BEGIN + 44)
/* Added for Boston_R13_CR_PHASEI, 2016-10-17, End */
/* Added for Boston_R13_CR_PHASEII, 2016-12-01, begin */
#define APP_ERR_SM_MAX_EPS_NUM_REACHED (APP_ERR_SM_SECTION_BEGIN + 45)
/* Added for Boston_R13_CR_PHASEII, 2016-12-01, end */
/* Added for Boston_R13_CR_PHASEIII, 2017-01-16, Begin */
#define APP_ERR_SM_THROT_BACKOFF_IS_RUNNING (APP_ERR_SM_SECTION_BEGIN + 46)
/* Added for Boston_R13_CR_PHASEIII, 2017-01-16, End */
/* Added for PDP_CAUSE_RPT,2017-09-11,Begin */
#define APP_ERR_SM_MM_NOT_SYNC (APP_ERR_SM_SECTION_BEGIN + 47)
#define APP_ERR_SM_NW_RECONFIGURE (APP_ERR_SM_SECTION_BEGIN + 48)
#define APP_ERR_SM_DELETE_SDF (APP_ERR_SM_SECTION_BEGIN + 49)
/* Added for PDP_CAUSE_RPT,2017-09-11,End */
#define APP_ERR_SM_NOT_IN_ACL_LIST (APP_ERR_SM_SECTION_BEGIN + 50)
#define APP_ERR_SM_APN_DISABLE (APP_ERR_SM_SECTION_BEGIN + 51)
#define APP_ERR_SM_IMS_DEREG_NOT_ATTACH (APP_ERR_SM_SECTION_BEGIN + 52)
#define APP_ERR_SM_BEARER_ALLOC_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 53)

#define APP_ERR_SM_BEARER_MOD_NOT_ALLOWED (APP_ERR_SM_SECTION_BEGIN + 54)

/* added 2019-03-01,started */
#define APP_ERR_SM_NR_QOS_FLOW_MAP_FAIL (APP_ERR_SM_SECTION_BEGIN + 55)
/* added 2019-03-01,end */

#define APP_ERR_SM_REDIAL (APP_ERR_SM_SECTION_BEGIN + 56)
/* added 2020-04-13,started */
#define APP_ERR_SM_TIME_OUT_WITH_SEND_FAILED (APP_ERR_SM_SECTION_BEGIN + 57)
/* added 2020-04-13,end */


/* SM与网侧错误码 */
#define APP_ERR_SM_NW_OPERATOR_DETERMINED_BARRING (APP_ERR_SM_NW_SECTION_BEGIN + 0)
#define APP_ERR_SM_NW_INSUFFICIENT_RESOURCES (APP_ERR_SM_NW_SECTION_BEGIN + 1)
#define APP_ERR_SM_NW_MISSING_OR_UKNOWN_APN (APP_ERR_SM_NW_SECTION_BEGIN + 2)
#define APP_ERR_SM_NW_UNKNOWN_PDN_TYPE (APP_ERR_SM_NW_SECTION_BEGIN + 3)
#define APP_ERR_SM_NW_USER_AUTH_FAIL (APP_ERR_SM_NW_SECTION_BEGIN + 4)
#define APP_ERR_SM_NW_REQ_REJ_BY_SGW_OR_PGW (APP_ERR_SM_NW_SECTION_BEGIN + 5)
#define APP_ERR_SM_NW_REQ_REJ_UNSPECITY (APP_ERR_SM_NW_SECTION_BEGIN + 6)
#define APP_ERR_SM_NW_SERVICE_OPTION_NOT_SUPPORT (APP_ERR_SM_NW_SECTION_BEGIN + 7)
#define APP_ERR_SM_NW_REQ_SERVICE_NOT_SUBSCRIBE (APP_ERR_SM_NW_SECTION_BEGIN + 8)
#define APP_ERR_SM_NW_SERVICE_OPTION_TEMP_OUT_ORDER (APP_ERR_SM_NW_SECTION_BEGIN + 9)
#define APP_ERR_SM_NW_PTI_ALREADY_IN_USE (APP_ERR_SM_NW_SECTION_BEGIN + 10)
#define APP_ERR_SM_NW_REGULAR_DEACT (APP_ERR_SM_NW_SECTION_BEGIN + 11)
#define APP_ERR_SM_NW_EPS_QOS_NOT_ACCEPT (APP_ERR_SM_NW_SECTION_BEGIN + 12)
#define APP_ERR_SM_NW_NET_FAIL (APP_ERR_SM_NW_SECTION_BEGIN + 13)
#define APP_ERR_SM_NW_SEMANTIC_ERR_IN_TFT (APP_ERR_SM_NW_SECTION_BEGIN + 14)
#define APP_ERR_SM_NW_SYNTACTIC_ERR_IN_TFT (APP_ERR_SM_NW_SECTION_BEGIN + 15)
#define APP_ERR_SM_NW_INVALID_EPS_BERER_IDENTITY (APP_ERR_SM_NW_SECTION_BEGIN + 16)
#define APP_ERR_SM_NW_SEMANTIC_ERR_IN_PACKET_FILTER (APP_ERR_SM_NW_SECTION_BEGIN + 17)
#define APP_ERR_SM_NW_SYNCTACTIC_ERR_IN_PACKET_FILTER (APP_ERR_SM_NW_SECTION_BEGIN + 18)
#define APP_ERR_SM_NW_BEARER_WITHOUT_TFT_ACT (APP_ERR_SM_NW_SECTION_BEGIN + 19)
#define APP_ERR_SM_NW_PTI_MISMATICH (APP_ERR_SM_NW_SECTION_BEGIN + 20)
#define APP_ERR_SM_NW_LAST_PDN_DISCONN_NOT_ALLOWED (APP_ERR_SM_NW_SECTION_BEGIN + 21)
#define APP_ERR_SM_NW_PDN_TPYE_IPV4_ONLY_ALLOWED (APP_ERR_SM_NW_SECTION_BEGIN + 22)
#define APP_ERR_SM_NW_PDN_TPYE_IPV6_ONLY_ALLOWED (APP_ERR_SM_NW_SECTION_BEGIN + 23)
#define APP_ERR_SM_NW_SINGLE_ADDR_BERERS_ONLY_ALLOWED (APP_ERR_SM_NW_SECTION_BEGIN + 24)
#define APP_ERR_SM_NW_ESM_INFO_NOT_RECEIVED (APP_ERR_SM_NW_SECTION_BEGIN + 25)
#define APP_ERR_SM_NW_PDN_CONN_NOT_EXIST (APP_ERR_SM_NW_SECTION_BEGIN + 26)
#define APP_ERR_SM_NW_MULTI_PDN_CONN_FOR_ONE_APN_NOT_ALLOWED (APP_ERR_SM_NW_SECTION_BEGIN + 27)
#define APP_ERR_SM_NW_COLLISION_WITH_NW_INTIAL_REQEST (APP_ERR_SM_NW_SECTION_BEGIN + 28)
#define APP_ERR_SM_NW_INVALID_PTI_VALUE (APP_ERR_SM_NW_SECTION_BEGIN + 29)
#define APP_ERR_SM_NW_SYNCTACTIC_INCORRECT_MSG (APP_ERR_SM_NW_SECTION_BEGIN + 30)
#define APP_ERR_SM_NW_INVALID_MANDATORY_INFOR (APP_ERR_SM_NW_SECTION_BEGIN + 31)
#define APP_ERR_SM_NW_MSG_TYPE_NON_EXIST (APP_ERR_SM_NW_SECTION_BEGIN + 32)
#define APP_ERR_SM_NW_MSG_TYPE_NOT_COMPATIBLE_WITH_PROT (APP_ERR_SM_NW_SECTION_BEGIN + 33)
#define APP_ERR_SM_NW_INFOR_ELEM_NON_EXIST (APP_ERR_SM_NW_SECTION_BEGIN + 34)
#define APP_ERR_SM_NW_CONDITIONAL_IE_ERROR (APP_ERR_SM_NW_SECTION_BEGIN + 35)
#define APP_ERR_SM_NW_MSG_NOT_COMPATIBLE_WITH_PROT (APP_ERR_SM_NW_SECTION_BEGIN + 36)
#define APP_ERR_SM_NW_PROT_ERR_UNSPECIFIED (APP_ERR_SM_NW_SECTION_BEGIN + 37)
#define APP_ERR_SM_NW_APN_RESTRICTION_INCOMPATIBLE_WITH_ACT_EPS_BEARER (APP_ERR_SM_NW_SECTION_BEGIN + 38)
#define APP_ERR_SM_NW_UNSUPPORTED_QCI_VALUE (APP_ERR_SM_NW_SECTION_BEGIN + 39)
#define APP_ERR_SM_NW_APN_NOT_SUPPORT_IN_CURRENT_RAT_AND_PLMN (APP_ERR_SM_NW_SECTION_BEGIN + 40)
#define APP_ERR_SM_NW_REACTIVATION_REQUESTED (APP_ERR_SM_NW_SECTION_BEGIN + 41)
/* Added 2016-10-31, begin */
#define APP_ERR_SM_NW_BEARER_HANDLING_NOT_SUPPORTED (APP_ERR_SM_NW_SECTION_BEGIN + 42)
#define APP_ERR_SM_NW_MAXIMUM_NUMBER_OF_EPS_BEARERS_REACHED (APP_ERR_SM_NW_SECTION_BEGIN + 43)
/* Added 2016-10-31, end */

/* EHSM与ESM 清除承载原因值 */
/* Added for HO ATTACH, 2018-12-20 begin */
#define APP_ERR_EHSM_ESM_SUCCESS (APP_ERR_EHSM_ESM_SECTION_BEGIN + 0)
#define APP_ERR_EHSM_ESM_L2C_HANDOVER_FAIL (APP_ERR_EHSM_ESM_SECTION_BEGIN + 1)
#define APP_ERR_EHSM_ESM_ATTACH_FAIL (APP_ERR_EHSM_ESM_SECTION_BEGIN + 2)
#define APP_ERR_EHSM_ESM_POWER_OFF (APP_ERR_EHSM_ESM_SECTION_BEGIN + 3)
#define APP_ERR_EHSM_ESM_PS_DETACH (APP_ERR_EHSM_ESM_SECTION_BEGIN + 4)
#define APP_ERR_EHSM_ESM_BEARER_SYNC_ERROR (APP_ERR_EHSM_ESM_SECTION_BEGIN + 5)
#define APP_ERR_EHSM_ESM_LOCAL_DEACT (APP_ERR_EHSM_ESM_SECTION_BEGIN + 6)
#define APP_ERR_EHSM_ESM_PPPC_ACTED_PDN_LESS_THAN_EHSM (APP_ERR_EHSM_ESM_SECTION_BEGIN + 7)
#define APP_ERR_EHSM_ESM_NOT_SUPPORT_EHRPD (APP_ERR_EHSM_ESM_SECTION_BEGIN + 8)
#define APP_ERR_EHSM_ESM_PPPC_EXIST_NOT_OPEN_PDN (APP_ERR_EHSM_ESM_SECTION_BEGIN + 9)

/* Added for HO ATTACH, 2018-12-20 end */


#pragma pack(pop)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif /* end of app_nas_err_cause.h */
