obj-$(CONFIG_USB_F_MODEM_ACM)	+= usb_f_modem_acm.o
usb_f_modem_acm-y		:= f_modem_acm.o modem_acm.o usb_vendor.o
usb_f_modem_acm-y		+= chip_adp_acm.o chip_adp_usb.o chip_adp_acm_test.o
usb_f_modem_acm-y	+= hiusb_acm_debug.o

obj-y += chip_adp_interface_fake.o

obj-$(CONFIG_USB_F_SOURCESINK_EXT)	+= f_sourcesink_ext.o
