/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "plat_effect_para.h"

#include "oxf_tm_td4320_6p57.h"

#include "oxf_tm_nt36682a_6p57.h"

#include "oxf_boe_td4320_6p57.h"

#include "oxf_boe_nt36682a_6p57.h"

#include "oxf_tcl_td4320_6p57.h"

#include "oxf_tcl_nt36682a_6p57.h"

#include "oxf_auo_nt36682a_6p57.h"

#include "oxf_5g_tm_td4320_6p57.h"

#include "oxf_5g_tm_nt36682a_6p57.h"

#include "oxf_5g_boe_td4320_6p57.h"

#include "oxf_5g_boe_nt36682a_6p57.h"

#include "oxf_5g_tcl_td4320_6p57.h"

#include "oxf_5g_tcl_nt36682a_6p57.h"

#include "oxf_5g_auo_nt36682a_6p57.h"

#include "oxf_pb_tm_td4320_6p57.h"

#include "oxf_pb_tm_nt36682a_6p57.h"

#include "oxf_pb_boe_td4320_6p57.h"

#include "oxf_pb_boe_nt36682a_6p57.h"

#include "oxf_pb_tcl_td4320_6p57.h"

#include "oxf_pb_tcl_nt36682a_6p57.h"

#include "oxf_pb_auo_nt36682a_6p57.h"

#include "wlz_tm_td4320_6p57.h"

#include "wlz_tm_nt36682a_6p57.h"

#include "wlz_boe_td4320_6p57.h"

#include "wlz_boe_nt36682a_6p57.h"

#include "wlz_tcl_td4320_6p57.h"

#include "wlz_tcl_nt36682a_6p57.h"

#include "wlz_auo_nt36682a_6p57.h"

#include "wlz_pb_tm_td4320_6p57.h"

#include "wlz_pb_tm_nt36682a_6p57.h"

#include "wlz_pb_boe_td4320_6p57.h"

#include "wlz_pb_boe_nt36682a_6p57.h"

#include "wlz_pb_tcl_td4320_6p57.h"

#include "wlz_pb_tcl_nt36682a_6p57.h"

#include "wlz_pb_auo_nt36682a_6p57.h"

#include "tahiti_boe_nt37800_tah_c.h"

#include "tahiti_boe_nt37800eco_tah_c.h"

#include "cdy_boe_ft8719_6p5.h"

#include "cdy_csot_nt36682a_6p5.h"

#include "cdy_tm_nt36682a_6p5.h"

#include "cdy_boe_td4320_6p5.h"

#include "udp_sharp_nt36870_udp.h"

#include "udp_jdi_r63452_udp_2.h"

#include "udp_sharp_nt36870_udp_2.h"

#include "udp_jdi_r63452_udp_3.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
LAYA_TUGL_BOE_R66451_PANEL,
LAYA_TUGL_LG_EA9151_PANEL,
LAYA_TUGL_BOE_R66451_TC2_PANEL,
LAYA_TUGL_LG_EA9151_6P39_TC2_1440PLUS_CMD_PANEL,
ELLE_SAMSUNG_EA8076_PANEL,
ELLE_SAMSUNG_EA8076_V2_PANEL,
TAURUS_SAMSUNG_EA8079_PANEL,
TAURUS_VISI_RM692C9_TAS_PANEL,
TAURUS_5G_SAMSUNG_EA8079_PANEL,
TAURUS_5G_VISI_RM692C9_TAS_PANEL,
LION_LG_NT37280_LION_PANEL,
LION_BOE_SW43103_LION_PANEL,
LION_SM_S6E3HA8_6P53_PANEL,
LION_V3_LG_NT37280_LION_PANEL,
LION_V3_BOE_SW43103_LION_PANEL,
LION_V3_SM_S6E3HA8_6P53_PANEL,
LION_V3_LG_NT37280_6P53_PANEL,
LION_V4_LG_NT37280_LION_PANEL,
LION_V4_BOE_SW43103_LION_PANEL,
LION_V4_BOE_R66458_6P53_PANEL,
LION_V4_SM_S6E3HA8_6P53_PANEL,
LION_5G_LG_NT37280_LION_PANEL,
LION_5G_BOE_SW43103_LION_PANEL,
LION_5G_BOE_R66458_6P53_PANEL,
LION_5G_SM_S6E3HA8_6P53_PANEL,
LION_VN1_LG_NT37280_LION_PANEL,
LION_VN1_BOE_SW43103_LION_PANEL,
LION_VN1_BOE_R66458_6P53_PANEL,
LION_VN1_SM_S6E3HA8_6P53_PANEL,
LION_VN2_LG_NT37280_LION_PANEL,
LION_VN2_BOE_SW43103_LION_PANEL,
LION_VN2_BOE_R66458_6P53_PANEL,
LION_VN2_SM_S6E3HA8_6P53_PANEL,
MARX_AUO_HX5322A_10P8_PANEL,
MARX_BOE_HX5322A_10P8_PANEL,
MARX_TM_HX5322A_10P8_PANEL,
MARX_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
MARX_V3_AUO_HX5322A_10P8_PANEL,
MARX_V3_BOE_HX5322A_10P8_PANEL,
MARX_V3_TM_HX5322A_10P8_PANEL,
MARX_V3_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
MARX_5G_AUO_HX5322A_10P8_PANEL,
MARX_5G_BOE_HX5322A_10P8_PANEL,
MARX_5G_TM_HX5322A_10P8_PANEL,
MARX_5G_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
OXF_TM_TD4320_6P57_PANEL,
OXF_TM_NT36682A_6P57_PANEL,
OXF_BOE_TD4320_6P57_PANEL,
OXF_BOE_NT36682A_6P57_PANEL,
OXF_TCL_TD4320_6P57_PANEL,
OXF_TCL_NT36682A_6P57_PANEL,
OXF_AUO_NT36682A_6P57_PANEL,
OXF_5G_TM_TD4320_6P57_PANEL,
OXF_5G_TM_NT36682A_6P57_PANEL,
OXF_5G_BOE_TD4320_6P57_PANEL,
OXF_5G_BOE_NT36682A_6P57_PANEL,
OXF_5G_TCL_TD4320_6P57_PANEL,
OXF_5G_TCL_NT36682A_6P57_PANEL,
OXF_5G_AUO_NT36682A_6P57_PANEL,
OXF_PB_TM_TD4320_6P57_PANEL,
OXF_PB_TM_NT36682A_6P57_PANEL,
OXF_PB_BOE_TD4320_6P57_PANEL,
OXF_PB_BOE_NT36682A_6P57_PANEL,
OXF_PB_TCL_TD4320_6P57_PANEL,
OXF_PB_TCL_NT36682A_6P57_PANEL,
OXF_PB_AUO_NT36682A_6P57_PANEL,
WLZ_TM_TD4320_6P57_PANEL,
WLZ_TM_NT36682A_6P57_PANEL,
WLZ_BOE_TD4320_6P57_PANEL,
WLZ_BOE_NT36682A_6P57_PANEL,
WLZ_TCL_TD4320_6P57_PANEL,
WLZ_TCL_NT36682A_6P57_PANEL,
WLZ_AUO_NT36682A_6P57_PANEL,
WLZ_PB_TM_TD4320_6P57_PANEL,
WLZ_PB_TM_NT36682A_6P57_PANEL,
WLZ_PB_BOE_TD4320_6P57_PANEL,
WLZ_PB_BOE_NT36682A_6P57_PANEL,
WLZ_PB_TCL_TD4320_6P57_PANEL,
WLZ_PB_TCL_NT36682A_6P57_PANEL,
WLZ_PB_AUO_NT36682A_6P57_PANEL,
ANNA_5G_BOE_NT37700P_6P11_PANEL,
ANNA_BOE_NT37700P_6P11_PANEL,
ELSA_5G_LG_EA9152_6P58_PANEL,
ELSA_5G_BOE_NT37800A_VESA_PANEL,
ELSA_5G_SM_S6E3HC2_6P58_PANEL,
ELSA_V3_BOE_NT37800A_6P58_PANEL,
ELSA_V3_BOE_NT37800_6P58_PANEL,
ELSA_V4_BOE_NT37800A_VESA_PANEL,
ELSA_V4_LG_EA9152_6P58_PANEL,
ELSA_V4_SM_S6E3HC2_6P58_PANEL,
ELSA_VN2_LG_EA9152_6P58_PANEL,
ELSA_VN2_SM_S6E3HC2_6P58_PANEL,
ELSA_VN2_BOE_NT37800A_VESA_PANEL,
TAHITI_BOE_NT37800_TAH_C_PANEL,
TAHITI_BOE_NT37800ECO_TAH_C_PANEL,
CDY_BOE_FT8719_6P5_PANEL,
CDY_CSOT_NT36682A_6P5_PANEL,
CDY_TM_NT36682A_6P5_PANEL,
CDY_BOE_TD4320_6P5_PANEL,
EBG_BOE_NT37700P_6P57_PANEL,
EBG_BOE_EW813P_6P57_PANEL,
EBG_VISI_NT37700C_6P57_PANEL,
EBG_VISI_NT37700C_6P57_ON_PANEL,
EBG_V4_BOE_NT37700P_6P57_PANEL,
EBG_V4_BOE_EW813P_6P57_PANEL,
EBG_V4_VISI_NT37700C_6P57_PANEL,
EBG_V4_VISI_NT37700C_6P57_ON_PANEL,
EBG_ESW_BOE_EW813P_6P57_PANEL,
EBG_ESW_BOE_NT37700P_6P57_PANEL,
EBG_ESW_VISI_NT37700C_6P57_PANEL,
EBG_ESW_VISI_NT37700C_6P57_ON_PANEL,
EBG_ELV_BOE_EW813P_6P57_PANEL,
EBG_ELV_BOE_NT37700P_6P57_PANEL,
EBG_ELV_VISI_NT37700C_6P57_PANEL,
EBG_ELV_VISI_NT37700C_6P57_ON_PANEL,
EBG_90_BOE_EW813P_6P57_PANEL,
EBG_90_BOE_NT37700P_6P57_PANEL,
EBG_90_VISI_NT37700C_6P57_PANEL,
EBG_90_VISI_NT37700C_6P57_ON_PANEL,
JEF_SAMSUNG_EA8076_6P53_PANEL,
JER_BOE_NT37700P_6P57_PANEL,
JER_BOE_EW813P_6P57_PANEL,
JER_VISI_NT37700C_6P57_PANEL,
JER_VISI_NT37700C_6P57_ON_PANEL,
BMH_SAMSUNG_EA8076_6P53_PANEL,
ELSAP_V2_SM_S6E3HC2_6P58_PANEL,
ELSAP_VN2_SM_S6E3HC2_6P58_PANEL,
SCMR_INX_HX8252A_10P7_PANEL,
SCMR_BOE_HX8252A_10P7_PANEL,
SCMR_INX_NT35523_10P7_PANEL,
SCMR_BOEDVT2_NT35523_10P7_PANEL,
BRQ_190_207_6P72_PANEL,
BRQ_310_207_6P72_PANEL,
OCEAN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
OCEAN_190_205_6P506_90_PANEL,
UDP_SAMSUNG_EA8074_UDP_PANEL,
UDP_SHARP_NT36870_UDP_PANEL,
UDP_JDI_R63452_UDP_2_PANEL,
UDP_BOE_NT37700P_UDP_PANEL,
UDP_AUTO_FAKE_PANEL_UDP_DEF_PANEL,
UDP_SAMSUNG_EA8074_UDP_2_PANEL,
UDP_SHARP_NT36870_UDP_2_PANEL,
UDP_JDI_R63452_UDP_3_PANEL,
UDP_BOE_NT37700P_UDP_2_PANEL,
UDP_AUTO_FAKE_PANEL_UDP_DEF_2_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcd_kit_board_map {
    uint8_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcd_kit_board_map lcd_kit_map[] = {
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {LAYA_TUGL_BOE_R66451_PANEL, "boe_r66451", 1000},
    {LAYA_TUGL_LG_EA9151_PANEL, "lg_ea9151", 1000},
    {LAYA_TUGL_BOE_R66451_TC2_PANEL, "boe_r66451_6p39_tc2_1440plus_cmd", 1002},
    {LAYA_TUGL_LG_EA9151_6P39_TC2_1440PLUS_CMD_PANEL, "lg_ea9151_6p39_tc2_1440plus_cmd", 1001},
    {ELLE_SAMSUNG_EA8076_PANEL, "samsung_ea8076", 2000},
    {ELLE_SAMSUNG_EA8076_V2_PANEL, "samsung_ea8076_v2", 2001},
    {TAURUS_SAMSUNG_EA8079_PANEL, "samsung_ea8079_taurus", 2001},
    {TAURUS_VISI_RM692C9_TAS_PANEL, "visi_rm692c9_taurus", 2001},
    {TAURUS_5G_SAMSUNG_EA8079_PANEL, "samsung_ea8079_taurus", 2002},
    {TAURUS_5G_VISI_RM692C9_TAS_PANEL, "visi_rm692c9_taurus", 2002},
    {LION_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1003},
    {LION_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1003},
    {LION_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1003},
    {LION_V3_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1004},
    {LION_V3_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1004},
    {LION_V3_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1004},
    {LION_V3_LG_NT37280_6P53_PANEL, "lg_nt37280_lion", 1004},
    {LION_V4_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1005},
    {LION_V4_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1005},
    {LION_V4_BOE_R66458_6P53_PANEL, "boe_r66458_6p53", 1005},
    {LION_V4_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1005},
    {LION_5G_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1006},
    {LION_5G_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1006},
    {LION_5G_BOE_R66458_6P53_PANEL, "boe_r66458_6p53", 1006},
    {LION_5G_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1006},
    {LION_VN1_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1007},
    {LION_VN1_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1007},
    {LION_VN1_BOE_R66458_6P53_PANEL, "boe_r66458_6p53", 1007},
    {LION_VN1_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1007},
    {LION_VN2_LG_NT37280_LION_PANEL, "lg_nt37280_lion", 1008},
    {LION_VN2_BOE_SW43103_LION_PANEL, "boe_sw43103_lion", 1008},
    {LION_VN2_BOE_R66458_6P53_PANEL, "boe_r66458_6p53", 1008},
    {LION_VN2_SM_S6E3HA8_6P53_PANEL, "sm_s6e3ha8_lion", 1008},
    {MARX_AUO_HX5322A_10P8_PANEL, "auo-hx5322a-10p8-1600p-video", 3001},
    {MARX_BOE_HX5322A_10P8_PANEL, "boe-hx5322a-10p8-1600p-video", 3001},
    {MARX_TM_HX5322A_10P8_PANEL, "tm-hx5322a-10p8-1600p-video", 3001},
    {MARX_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {MARX_V3_AUO_HX5322A_10P8_PANEL, "auo-hx5322a-10p8-1600p-video", 3002},
    {MARX_V3_BOE_HX5322A_10P8_PANEL, "boe-hx5322a-10p8-1600p-video", 3002},
    {MARX_V3_TM_HX5322A_10P8_PANEL, "tm-hx5322a-10p8-1600p-video", 3002},
    {MARX_V3_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {MARX_5G_AUO_HX5322A_10P8_PANEL, "auo-hx5322a-10p8-1600p-video", 3003},
    {MARX_5G_BOE_HX5322A_10P8_PANEL, "boe-hx5322a-10p8-1600p-video", 3003},
    {MARX_5G_TM_HX5322A_10P8_PANEL, "tm-hx5322a-10p8-1600p-video", 3003},
    {MARX_5G_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {OXF_TM_TD4320_6P57_PANEL, "tm_td4320_6p57", 4000},
    {OXF_TM_NT36682A_6P57_PANEL, "tm_nt36682a_6p57", 4000},
    {OXF_BOE_TD4320_6P57_PANEL, "boe_td4320_6p57", 4000},
    {OXF_BOE_NT36682A_6P57_PANEL, "boe_nt36682a_6p57", 4000},
    {OXF_TCL_TD4320_6P57_PANEL, "tcl_td4320_6p57", 4000},
    {OXF_TCL_NT36682A_6P57_PANEL, "tcl_nt36682a_6p57", 4000},
    {OXF_AUO_NT36682A_6P57_PANEL, "auo_nt36682a_6p57", 4000},
    {OXF_5G_TM_TD4320_6P57_PANEL, "tm_td4320_6p57", 4001},
    {OXF_5G_TM_NT36682A_6P57_PANEL, "tm_nt36682a_6p57", 4001},
    {OXF_5G_BOE_TD4320_6P57_PANEL, "boe_td4320_6p57", 4001},
    {OXF_5G_BOE_NT36682A_6P57_PANEL, "boe_nt36682a_6p57", 4001},
    {OXF_5G_TCL_TD4320_6P57_PANEL, "tcl_td4320_6p57", 4001},
    {OXF_5G_TCL_NT36682A_6P57_PANEL, "tcl_nt36682a_6p57", 4001},
    {OXF_5G_AUO_NT36682A_6P57_PANEL, "auo_nt36682a_6p57", 4001},
    {OXF_PB_TM_TD4320_6P57_PANEL, "tm_td4320_6p57", 4002},
    {OXF_PB_TM_NT36682A_6P57_PANEL, "tm_nt36682a_6p57", 4002},
    {OXF_PB_BOE_TD4320_6P57_PANEL, "boe_td4320_6p57", 4002},
    {OXF_PB_BOE_NT36682A_6P57_PANEL, "boe_nt36682a_6p57", 4002},
    {OXF_PB_TCL_TD4320_6P57_PANEL, "tcl_td4320_6p57", 4002},
    {OXF_PB_TCL_NT36682A_6P57_PANEL, "tcl_nt36682a_6p57", 4002},
    {OXF_PB_AUO_NT36682A_6P57_PANEL, "auo_nt36682a_6p57", 4002},
    {WLZ_TM_TD4320_6P57_PANEL, "tm_td4320_6p57", 5000},
    {WLZ_TM_NT36682A_6P57_PANEL, "tm_nt36682a_6p57", 5000},
    {WLZ_BOE_TD4320_6P57_PANEL, "boe_td4320_6p57", 5000},
    {WLZ_BOE_NT36682A_6P57_PANEL, "boe_nt36682a_6p57", 5000},
    {WLZ_TCL_TD4320_6P57_PANEL, "tcl_td4320_6p57", 5000},
    {WLZ_TCL_NT36682A_6P57_PANEL, "tcl_nt36682a_6p57", 5000},
    {WLZ_AUO_NT36682A_6P57_PANEL, "auo_nt36682a_6p57", 5000},
    {WLZ_PB_TM_TD4320_6P57_PANEL, "tm_td4320_6p57", 5001},
    {WLZ_PB_TM_NT36682A_6P57_PANEL, "tm_nt36682a_6p57", 5001},
    {WLZ_PB_BOE_TD4320_6P57_PANEL, "boe_td4320_6p57", 5001},
    {WLZ_PB_BOE_NT36682A_6P57_PANEL, "boe_nt36682a_6p57", 5001},
    {WLZ_PB_TCL_TD4320_6P57_PANEL, "tcl_td4320_6p57", 5001},
    {WLZ_PB_TCL_NT36682A_6P57_PANEL, "tcl_nt36682a_6p57", 5001},
    {WLZ_PB_AUO_NT36682A_6P57_PANEL, "auo_nt36682a_6p57", 5001},
    {ANNA_5G_BOE_NT37700P_6P11_PANEL, "boe_nt37700p_anna_6p11_1080plus_cmd", 6000},
    {ANNA_BOE_NT37700P_6P11_PANEL, "boe_nt37700p_anna_6p11_1080plus_cmd", 6001},
    {ELSA_5G_LG_EA9152_6P58_PANEL, "lg_ea9152_elsa_6p58_1200plus_cmd", 7000},
    {ELSA_5G_BOE_NT37800A_VESA_PANEL, "boe_vesa90_nt37800a_elsa_6p58_1200plus_cmd", 7000},
    {ELSA_5G_SM_S6E3HC2_6P58_PANEL, "sm_s6e3hc2_elsa", 7000},
    {ELSA_V3_BOE_NT37800A_6P58_PANEL, "boe_nt37800a_elsa_6p58_1200plus_cmd", 7001},
    {ELSA_V3_BOE_NT37800_6P58_PANEL, "boe_nt37800f_elsa_6p58_1440plus_cmd", 7002},
    {ELSA_V4_BOE_NT37800A_VESA_PANEL, "boe_vesa90_nt37800a_elsa_6p58_1200plus_cmd", 7003},
    {ELSA_V4_LG_EA9152_6P58_PANEL, "lg_ea9152_elsa_6p58_1200plus_cmd", 7003},
    {ELSA_V4_SM_S6E3HC2_6P58_PANEL, "sm_s6e3hc2_elsa", 7003},
    {ELSA_VN2_LG_EA9152_6P58_PANEL, "lg_ea9152_elsa_6p58_1200plus_cmd", 7004},
    {ELSA_VN2_SM_S6E3HC2_6P58_PANEL, "sm_s6e3hc2_elsa", 7004},
    {ELSA_VN2_BOE_NT37800A_VESA_PANEL, "boe_vesa90_nt37800a_elsa_6p58_1200plus_cmd", 7004},
    {TAHITI_BOE_NT37800_TAH_C_PANEL, "boe-nt37800f-tah-8p03-3lane-2mux-cmd", 8000},
    {TAHITI_BOE_NT37800ECO_TAH_C_PANEL, "boe-nt37800eco-tah-8p03-3lane-2mux-cmd", 8000},
    {CDY_BOE_FT8719_6P5_PANEL, "boe_ft8719_6p5", 9000},
    {CDY_CSOT_NT36682A_6P5_PANEL, "csot_nt36682a_6p5", 9000},
    {CDY_TM_NT36682A_6P5_PANEL, "tm_nt36682a_6p5", 9000},
    {CDY_BOE_TD4320_6P5_PANEL, "boe_td4320_6p5", 9000},
    {EBG_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 10000},
    {EBG_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 10000},
    {EBG_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 10000},
    {EBG_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 10000},
    {EBG_V4_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 10001},
    {EBG_V4_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 10001},
    {EBG_V4_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 10001},
    {EBG_V4_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 10001},
    {EBG_ESW_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 10002},
    {EBG_ESW_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 10002},
    {EBG_ESW_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 10002},
    {EBG_ESW_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 10002},
    {EBG_ELV_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 10003},
    {EBG_ELV_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 10003},
    {EBG_ELV_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 10003},
    {EBG_ELV_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 10003},
    {EBG_90_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 10004},
    {EBG_90_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 10004},
    {EBG_90_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 10004},
    {EBG_90_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 10004},
    {JEF_SAMSUNG_EA8076_6P53_PANEL, "samsung_ea8076_6p53_1080p_cmd", 11000},
    {JER_BOE_NT37700P_6P57_PANEL, "boe_nt37700p_6p57", 11010},
    {JER_BOE_EW813P_6P57_PANEL, "boe_ew813p_6p57", 11010},
    {JER_VISI_NT37700C_6P57_PANEL, "visi_nt37700c_6p57", 11010},
    {JER_VISI_NT37700C_6P57_ON_PANEL, "visi_nt37700c_6p57_on", 11010},
    {BMH_SAMSUNG_EA8076_6P53_PANEL, "samsung_ea8076_6p53_1080p_cmd", 12000},
    {ELSAP_V2_SM_S6E3HC2_6P58_PANEL, "sm_s6e3hc2_elsa", 13000},
    {ELSAP_VN2_SM_S6E3HC2_6P58_PANEL, "sm_s6e3hc2_elsa", 13001},
    {SCMR_INX_HX8252A_10P7_PANEL, "inx-hx8252a-10p7-1600p-video", 14000},
    {SCMR_BOE_HX8252A_10P7_PANEL, "boe-hx8252a-10p7-1600p-video", 14000},
    {SCMR_INX_NT35523_10P7_PANEL, "inx-nt35523-10p7-1600p-video", 14000},
    {SCMR_BOEDVT2_NT35523_10P7_PANEL, "boedvt2-nt35523-10p7-1600p-video", 14000},
    {BRQ_190_207_6P72_PANEL, "190_207_6p72", 15000},
    {BRQ_310_207_6P72_PANEL, "310_207_6p72", 15000},
    {OCEAN_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
    {OCEAN_190_205_6P506_90_PANEL, "190_205_6p506_90", 16000},
    {UDP_SAMSUNG_EA8074_UDP_PANEL, "samsung_ea8074_udp", 50},
    {UDP_SHARP_NT36870_UDP_PANEL, "sharp_nt36870_udp", 50},
    {UDP_JDI_R63452_UDP_2_PANEL, "jdi_r63452_udp_2", 50},
    {UDP_BOE_NT37700P_UDP_PANEL, "boe_nt37700p_udp", 50},
    {UDP_AUTO_FAKE_PANEL_UDP_DEF_PANEL, "auto_fake_panel_udp-def", 50},
    {UDP_SAMSUNG_EA8074_UDP_2_PANEL, "samsung_ea8074_udp-2", 60},
    {UDP_SHARP_NT36870_UDP_2_PANEL, "sharp_nt36870_udp_2", 60},
    {UDP_JDI_R63452_UDP_3_PANEL, "jdi_r63452_udp_3", 60},
    {UDP_BOE_NT37700P_UDP_2_PANEL, "boe_nt37700p_udp_2", 60},
    {UDP_AUTO_FAKE_PANEL_UDP_DEF_2_PANEL, "auto_fake_panel_udp-def-2", 60},
};

static void lcd_kit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    if (pinfo->gamma_support == 1)
    {
        pinfo->gamma_lut_table_R = plat_gamma_lut_table_R;
        pinfo->gamma_lut_table_G = plat_gamma_lut_table_G;
        pinfo->gamma_lut_table_B = plat_gamma_lut_table_B;
        pinfo->gamma_lut_table_len = ARRAY_SIZE(plat_gamma_lut_table_R);
        pinfo->igm_lut_table_R = plat_igm_lut_table_R;
        pinfo->igm_lut_table_G = plat_igm_lut_table_G;
        pinfo->igm_lut_table_B = plat_igm_lut_table_B;
        pinfo->igm_lut_table_len = ARRAY_SIZE(plat_igm_lut_table_R);
        pinfo->gmp_lut_table_low32bit = &plat_gmp_lut_table_low32bit[0][0][0];
        pinfo->gmp_lut_table_high4bit = &plat_gmp_lut_table_high4bit[0][0][0];
        pinfo->gmp_lut_table_len = ARRAY_3_SIZE(plat_gmp_lut_table_low32bit);
        pinfo->xcc_table = plat_xcc_table;
        pinfo->xcc_table_len = ARRAY_SIZE(plat_xcc_table);
    }
    switch (panel_id) {
    case OXF_TM_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_tm_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_tm_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_tm_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_tm_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_tm_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_tm_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_tm_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_tm_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_tm_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_tm_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_tm_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_tm_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_tm_td4320_6p57_xcc_table);
        }
        break;
    case OXF_TM_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_tm_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_tm_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_tm_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_tm_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_tm_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_tm_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_tm_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_tm_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_tm_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_tm_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_tm_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_tm_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_tm_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_BOE_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_boe_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_boe_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_boe_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_boe_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_boe_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_boe_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_boe_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_boe_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_boe_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_boe_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_boe_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_boe_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_boe_td4320_6p57_xcc_table);
        }
        break;
    case OXF_BOE_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_boe_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_boe_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_boe_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_boe_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_boe_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_boe_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_boe_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_boe_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_boe_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_boe_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_boe_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_boe_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_boe_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_TCL_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_tcl_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_tcl_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_tcl_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_tcl_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_tcl_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_tcl_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_tcl_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_tcl_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_tcl_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_tcl_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_tcl_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_tcl_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_tcl_td4320_6p57_xcc_table);
        }
        break;
    case OXF_TCL_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_tcl_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_tcl_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_tcl_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_tcl_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_tcl_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_tcl_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_tcl_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_tcl_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_tcl_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_tcl_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_tcl_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_tcl_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_tcl_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_AUO_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_auo_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_auo_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_auo_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_auo_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_auo_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_auo_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_auo_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_auo_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_auo_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_auo_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_auo_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_auo_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_auo_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_5G_TM_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_tm_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_tm_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_tm_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_tm_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_tm_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_tm_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_tm_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_tm_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_tm_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_tm_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_tm_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_tm_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_tm_td4320_6p57_xcc_table);
        }
        break;
    case OXF_5G_TM_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_tm_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_tm_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_tm_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_tm_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_tm_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_tm_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_tm_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_tm_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_tm_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_tm_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_tm_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_tm_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_tm_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_5G_BOE_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_boe_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_boe_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_boe_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_boe_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_boe_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_boe_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_boe_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_boe_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_boe_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_boe_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_boe_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_boe_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_boe_td4320_6p57_xcc_table);
        }
        break;
    case OXF_5G_BOE_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_boe_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_boe_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_boe_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_boe_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_boe_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_boe_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_boe_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_boe_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_boe_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_boe_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_boe_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_boe_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_boe_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_5G_TCL_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_tcl_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_tcl_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_tcl_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_tcl_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_tcl_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_tcl_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_tcl_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_tcl_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_tcl_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_tcl_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_tcl_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_tcl_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_tcl_td4320_6p57_xcc_table);
        }
        break;
    case OXF_5G_TCL_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_tcl_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_tcl_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_tcl_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_tcl_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_tcl_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_tcl_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_tcl_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_tcl_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_tcl_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_tcl_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_tcl_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_tcl_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_tcl_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_5G_AUO_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_5g_auo_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_5g_auo_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_5g_auo_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_5g_auo_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_5g_auo_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_5g_auo_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_5g_auo_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_5g_auo_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_5g_auo_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_5g_auo_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_5g_auo_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_5g_auo_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_5g_auo_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_PB_TM_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_tm_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_tm_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_tm_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_tm_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_tm_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_tm_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_tm_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_tm_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_tm_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_tm_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_tm_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_tm_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_tm_td4320_6p57_xcc_table);
        }
        break;
    case OXF_PB_TM_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_tm_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_tm_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_tm_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_tm_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_tm_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_tm_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_tm_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_tm_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_tm_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_tm_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_tm_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_tm_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_tm_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_PB_BOE_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_boe_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_boe_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_boe_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_boe_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_boe_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_boe_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_boe_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_boe_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_boe_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_boe_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_boe_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_boe_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_boe_td4320_6p57_xcc_table);
        }
        break;
    case OXF_PB_BOE_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_boe_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_boe_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_boe_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_boe_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_boe_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_boe_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_boe_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_boe_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_boe_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_boe_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_boe_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_boe_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_boe_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_PB_TCL_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_tcl_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_tcl_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_tcl_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_tcl_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_tcl_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_tcl_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_tcl_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_tcl_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_tcl_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_tcl_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_tcl_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_tcl_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_tcl_td4320_6p57_xcc_table);
        }
        break;
    case OXF_PB_TCL_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_tcl_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_tcl_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_tcl_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_tcl_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_tcl_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_tcl_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_tcl_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_tcl_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_tcl_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_tcl_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_tcl_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_tcl_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_tcl_nt36682a_6p57_xcc_table);
        }
        break;
    case OXF_PB_AUO_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = oxf_pb_auo_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = oxf_pb_auo_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = oxf_pb_auo_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(oxf_pb_auo_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = oxf_pb_auo_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = oxf_pb_auo_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = oxf_pb_auo_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(oxf_pb_auo_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &oxf_pb_auo_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &oxf_pb_auo_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(oxf_pb_auo_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = oxf_pb_auo_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(oxf_pb_auo_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_TM_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_tm_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_tm_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_tm_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_tm_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_tm_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_tm_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_tm_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_tm_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_tm_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_tm_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_tm_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_tm_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_tm_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_TM_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_tm_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_tm_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_tm_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_tm_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_tm_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_tm_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_tm_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_tm_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_tm_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_tm_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_tm_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_tm_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_tm_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_BOE_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_boe_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_boe_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_boe_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_boe_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_boe_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_boe_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_boe_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_boe_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_boe_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_boe_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_boe_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_boe_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_boe_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_BOE_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_boe_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_boe_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_boe_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_boe_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_boe_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_boe_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_boe_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_boe_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_boe_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_boe_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_boe_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_boe_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_boe_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_TCL_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_tcl_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_tcl_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_tcl_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_tcl_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_tcl_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_tcl_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_tcl_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_tcl_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_tcl_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_tcl_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_tcl_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_tcl_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_tcl_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_TCL_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_tcl_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_tcl_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_tcl_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_tcl_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_tcl_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_tcl_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_tcl_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_tcl_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_tcl_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_tcl_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_tcl_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_tcl_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_tcl_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_AUO_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_auo_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_auo_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_auo_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_auo_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_auo_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_auo_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_auo_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_auo_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_auo_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_auo_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_auo_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_auo_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_auo_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_PB_TM_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_tm_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_tm_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_tm_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_tm_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_tm_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_tm_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_tm_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_tm_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_tm_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_tm_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_tm_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_tm_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_tm_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_PB_TM_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_tm_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_tm_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_tm_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_tm_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_tm_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_tm_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_tm_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_tm_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_tm_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_tm_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_tm_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_tm_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_tm_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_PB_BOE_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_boe_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_boe_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_boe_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_boe_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_boe_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_boe_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_boe_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_boe_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_boe_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_boe_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_boe_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_boe_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_boe_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_PB_BOE_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_boe_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_boe_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_boe_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_boe_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_boe_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_boe_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_boe_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_boe_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_boe_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_boe_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_boe_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_boe_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_boe_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_PB_TCL_TD4320_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_tcl_td4320_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_tcl_td4320_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_tcl_td4320_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_tcl_td4320_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_tcl_td4320_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_tcl_td4320_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_tcl_td4320_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_tcl_td4320_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_tcl_td4320_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_tcl_td4320_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_tcl_td4320_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_tcl_td4320_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_tcl_td4320_6p57_xcc_table);
        }
        break;
    case WLZ_PB_TCL_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_tcl_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_tcl_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_tcl_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_tcl_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_tcl_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_tcl_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_tcl_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_tcl_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_tcl_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_tcl_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_tcl_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_tcl_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_tcl_nt36682a_6p57_xcc_table);
        }
        break;
    case WLZ_PB_AUO_NT36682A_6P57_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = wlz_pb_auo_nt36682a_6p57_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = wlz_pb_auo_nt36682a_6p57_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = wlz_pb_auo_nt36682a_6p57_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(wlz_pb_auo_nt36682a_6p57_gamma_lut_table_R);
            pinfo->igm_lut_table_R = wlz_pb_auo_nt36682a_6p57_igm_lut_table_R;
            pinfo->igm_lut_table_G = wlz_pb_auo_nt36682a_6p57_igm_lut_table_G;
            pinfo->igm_lut_table_B = wlz_pb_auo_nt36682a_6p57_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(wlz_pb_auo_nt36682a_6p57_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &wlz_pb_auo_nt36682a_6p57_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &wlz_pb_auo_nt36682a_6p57_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(wlz_pb_auo_nt36682a_6p57_gmp_lut_table_low32bit);
            pinfo->xcc_table = wlz_pb_auo_nt36682a_6p57_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(wlz_pb_auo_nt36682a_6p57_xcc_table);
        }
        break;
    case TAHITI_BOE_NT37800_TAH_C_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = tahiti_boe_nt37800_tah_c_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = tahiti_boe_nt37800_tah_c_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = tahiti_boe_nt37800_tah_c_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(tahiti_boe_nt37800_tah_c_gamma_lut_table_R);
            pinfo->igm_lut_table_R = tahiti_boe_nt37800_tah_c_igm_lut_table_R;
            pinfo->igm_lut_table_G = tahiti_boe_nt37800_tah_c_igm_lut_table_G;
            pinfo->igm_lut_table_B = tahiti_boe_nt37800_tah_c_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(tahiti_boe_nt37800_tah_c_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &tahiti_boe_nt37800_tah_c_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &tahiti_boe_nt37800_tah_c_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(tahiti_boe_nt37800_tah_c_gmp_lut_table_low32bit);
            pinfo->xcc_table = tahiti_boe_nt37800_tah_c_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(tahiti_boe_nt37800_tah_c_xcc_table);
        }
        break;
    case TAHITI_BOE_NT37800ECO_TAH_C_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = tahiti_boe_nt37800eco_tah_c_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = tahiti_boe_nt37800eco_tah_c_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = tahiti_boe_nt37800eco_tah_c_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(tahiti_boe_nt37800eco_tah_c_gamma_lut_table_R);
            pinfo->igm_lut_table_R = tahiti_boe_nt37800eco_tah_c_igm_lut_table_R;
            pinfo->igm_lut_table_G = tahiti_boe_nt37800eco_tah_c_igm_lut_table_G;
            pinfo->igm_lut_table_B = tahiti_boe_nt37800eco_tah_c_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(tahiti_boe_nt37800eco_tah_c_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &tahiti_boe_nt37800eco_tah_c_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &tahiti_boe_nt37800eco_tah_c_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(tahiti_boe_nt37800eco_tah_c_gmp_lut_table_low32bit);
            pinfo->xcc_table = tahiti_boe_nt37800eco_tah_c_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(tahiti_boe_nt37800eco_tah_c_xcc_table);
        }
        break;
    case CDY_BOE_FT8719_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_boe_ft8719_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_boe_ft8719_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_boe_ft8719_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_boe_ft8719_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_boe_ft8719_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_boe_ft8719_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_boe_ft8719_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_boe_ft8719_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_boe_ft8719_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_boe_ft8719_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_boe_ft8719_6p5_xcc_table);
        }
        break;
    case CDY_CSOT_NT36682A_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_csot_nt36682a_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_csot_nt36682a_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_csot_nt36682a_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_csot_nt36682a_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_csot_nt36682a_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_csot_nt36682a_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_csot_nt36682a_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_csot_nt36682a_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_csot_nt36682a_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_csot_nt36682a_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_csot_nt36682a_6p5_xcc_table);
        }
        break;
    case CDY_TM_NT36682A_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_tm_nt36682a_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_tm_nt36682a_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_tm_nt36682a_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_tm_nt36682a_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_tm_nt36682a_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_tm_nt36682a_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_tm_nt36682a_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_tm_nt36682a_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_tm_nt36682a_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_tm_nt36682a_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_tm_nt36682a_6p5_xcc_table);
        }
        break;
    case CDY_BOE_TD4320_6P5_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = cdy_boe_td4320_6p5_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = cdy_boe_td4320_6p5_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = cdy_boe_td4320_6p5_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_gamma_lut_table_R);
            pinfo->igm_lut_table_R = cdy_boe_td4320_6p5_igm_lut_table_R;
            pinfo->igm_lut_table_G = cdy_boe_td4320_6p5_igm_lut_table_G;
            pinfo->igm_lut_table_B = cdy_boe_td4320_6p5_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &cdy_boe_td4320_6p5_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &cdy_boe_td4320_6p5_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(cdy_boe_td4320_6p5_gmp_lut_table_low32bit);
            pinfo->xcc_table = cdy_boe_td4320_6p5_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(cdy_boe_td4320_6p5_xcc_table);
        }
        break;
    case UDP_SHARP_NT36870_UDP_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = udp_sharp_nt36870_udp_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = udp_sharp_nt36870_udp_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = udp_sharp_nt36870_udp_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_gamma_lut_table_R);
            pinfo->igm_lut_table_R = udp_sharp_nt36870_udp_igm_lut_table_R;
            pinfo->igm_lut_table_G = udp_sharp_nt36870_udp_igm_lut_table_G;
            pinfo->igm_lut_table_B = udp_sharp_nt36870_udp_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &udp_sharp_nt36870_udp_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &udp_sharp_nt36870_udp_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(udp_sharp_nt36870_udp_gmp_lut_table_low32bit);
            pinfo->xcc_table = udp_sharp_nt36870_udp_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_xcc_table);
        }
        break;
    case UDP_JDI_R63452_UDP_2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = udp_jdi_r63452_udp_2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = udp_jdi_r63452_udp_2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = udp_jdi_r63452_udp_2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = udp_jdi_r63452_udp_2_igm_lut_table_R;
            pinfo->igm_lut_table_G = udp_jdi_r63452_udp_2_igm_lut_table_G;
            pinfo->igm_lut_table_B = udp_jdi_r63452_udp_2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &udp_jdi_r63452_udp_2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &udp_jdi_r63452_udp_2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(udp_jdi_r63452_udp_2_gmp_lut_table_low32bit);
            pinfo->xcc_table = udp_jdi_r63452_udp_2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_2_xcc_table);
        }
        break;
    case UDP_SHARP_NT36870_UDP_2_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = udp_sharp_nt36870_udp_2_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = udp_sharp_nt36870_udp_2_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = udp_sharp_nt36870_udp_2_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_2_gamma_lut_table_R);
            pinfo->igm_lut_table_R = udp_sharp_nt36870_udp_2_igm_lut_table_R;
            pinfo->igm_lut_table_G = udp_sharp_nt36870_udp_2_igm_lut_table_G;
            pinfo->igm_lut_table_B = udp_sharp_nt36870_udp_2_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_2_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &udp_sharp_nt36870_udp_2_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &udp_sharp_nt36870_udp_2_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(udp_sharp_nt36870_udp_2_gmp_lut_table_low32bit);
            pinfo->xcc_table = udp_sharp_nt36870_udp_2_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(udp_sharp_nt36870_udp_2_xcc_table);
        }
        break;
    case UDP_JDI_R63452_UDP_3_PANEL:
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = udp_jdi_r63452_udp_3_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = udp_jdi_r63452_udp_3_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = udp_jdi_r63452_udp_3_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_3_gamma_lut_table_R);
            pinfo->igm_lut_table_R = udp_jdi_r63452_udp_3_igm_lut_table_R;
            pinfo->igm_lut_table_G = udp_jdi_r63452_udp_3_igm_lut_table_G;
            pinfo->igm_lut_table_B = udp_jdi_r63452_udp_3_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_3_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &udp_jdi_r63452_udp_3_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &udp_jdi_r63452_udp_3_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_3_SIZE(udp_jdi_r63452_udp_3_gmp_lut_table_low32bit);
            pinfo->xcc_table = udp_jdi_r63452_udp_3_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(udp_jdi_r63452_udp_3_xcc_table);
        }
        break;
    default:
        LCD_KIT_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcd_kit_get_panel_id(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcd_kit_map); ++i) {
        length = strlen(lcd_kit_map[i].panel_compatible);
        if ((lcd_kit_map[i].product_id == product_id) && !strncmp(lcd_kit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcd_kit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
