obj-$(CONFIG_LCD_KIT_HISI)	+= kernel/hisi/src/
obj-$(CONFIG_LCD_KIT_HISI) 	+= kernel/hisi/adapt/

obj-$(CONFIG_LCD_KIT_HISI)	+= kernel/common/src/
obj-$(CONFIG_LCD_KIT_MTK)	+= kernel/common/src/

obj-$(CONFIG_LCD_KIT_MTK)	+= kernel/mtk/src/
obj-$(CONFIG_LCD_KIT_MTK)	+= kernel/mtk/adapt/

obj-$(CONFIG_LCD_KIT_QCOM)	+= kernel/qcom/common/src/
obj-$(CONFIG_LCD_KIT_QCOM)	+= kernel/qcom/src/
obj-$(CONFIG_LCD_KIT_QCOM)	+= kernel/qcom/adapt/

