obj-$(CONFIG_HKIP_MODULE_ALLOC)	+= hhee_module.o
obj-$(CONFIG_HHEE)		+= hhee_log.o hhee_dev.o hhee_msg.o
obj-$(CONFIG_HHEE)		+= hkip/
obj-$(CONFIG_HHEE_DEBUG)	+= hhee_debugfs.o
obj-y				+= mm/
obj-y				+= cfi_harden/
