#
# Copyright (c) Huawei Technologies Co., Ltd. 2014-2021. All rights reserved.
# Description: This file describe GPU hardware related features
# Create: 2014-2-24
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

# Compile the customize last buffer implementation.
# include $(src)/$(MALI_PLATFORM_DIR)/base/lb/Kbuild

# Compile the customize memory group manager implementation.
#include $(src)/$(MALI_PLATFORM_DIR)/base/mgm/Kbuild

